/** Generated by `src/tools/gen-db-schema.ts` from `acore_auth` (`sql/base/db_auth` plus `data/sql/updates/`). Do not edit. */
import { binaryBytes, varbinaryBytes } from "./columns.ts";
import { mysqlTable, mysqlSchema, type AnyMySqlColumn, int, varchar, timestamp, tinyint, bigint, longtext, char, text, boolean, smallint, float, mysqlEnum, primaryKey, uniqueIndex, index, foreignKey, check } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const account = mysqlTable("account", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	username: varchar({ length: 32 }).default("").notNull(),
	salt: binaryBytes({ length: 32 }).notNull(),
	verifier: binaryBytes({ length: 32 }).notNull(),
	session_key: binaryBytes({ length: 40 }),
	totp_secret: varbinaryBytes({ length: 128 }),
	email: varchar({ length: 255 }).default("").notNull(),
	reg_mail: varchar({ length: 255 }).default("").notNull(),
	joindate: timestamp().defaultNow().notNull(),
	last_ip: varchar({ length: 15 }).default("127.0.0.1").notNull(),
	last_attempt_ip: varchar({ length: 15 }).default("127.0.0.1").notNull(),
	failed_logins: int({ unsigned: true }).default(0).notNull(),
	locked: tinyint({ unsigned: true }).default(0).notNull(),
	lock_country: varchar({ length: 2 }).default("00").notNull(),
	last_login: timestamp(),
	online: int({ unsigned: true }).default(0).notNull(),
	expansion: tinyint({ unsigned: true }).default(2).notNull(),
	Flags: int({ unsigned: true }).default(0).notNull(),
	mutetime: bigint({ mode: 'number' }).default(0).notNull(),
	mutereason: varchar({ length: 255 }).default("").notNull(),
	muteby: varchar({ length: 50 }).default("").notNull(),
	locale: tinyint({ unsigned: true }).default(0).notNull(),
	os: varchar({ length: 3 }).default("").notNull(),
	recruiter: int({ unsigned: true }).default(0).notNull(),
	totaltime: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	uniqueIndex("idx_username").on(table.username),
]);

export const account_access = mysqlTable("account_access", {
	id: int({ unsigned: true }).notNull(),
	gmlevel: tinyint({ unsigned: true }).notNull(),
	RealmID: int().default(-1).notNull(),
	comment: varchar({ length: 255 }).default(""),
},
(table) => [
	primaryKey({ columns: [table.id, table.RealmID] }),]);

export const account_banned = mysqlTable("account_banned", {
	id: int({ unsigned: true }).default(0).notNull(),
	bandate: int({ unsigned: true }).default(0).notNull(),
	unbandate: int({ unsigned: true }).default(0).notNull(),
	bannedby: varchar({ length: 50 }).notNull(),
	banreason: varchar({ length: 255 }).notNull(),
	active: tinyint({ unsigned: true }).default(1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.id, table.bandate] }),]);

export const account_muted = mysqlTable("account_muted", {
	guid: int({ unsigned: true }).default(0).notNull(),
	mutedate: int({ unsigned: true }).default(0).notNull(),
	mutetime: int({ unsigned: true }).default(0).notNull(),
	mutedby: varchar({ length: 50 }).notNull(),
	mutereason: varchar({ length: 255 }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.mutedate] }),]);

export const autobroadcast = mysqlTable("autobroadcast", {
	realmid: int().default(-1).notNull(),
	id: tinyint({ unsigned: true }).autoincrement().notNull(),
	weight: tinyint({ unsigned: true }).default(1),
	text: longtext().notNull(),
},
(table) => [
	primaryKey({ columns: [table.id, table.realmid] }),]);

export const autobroadcast_locale = mysqlTable("autobroadcast_locale", {
	realmid: int().notNull(),
	id: int().notNull(),
	locale: varchar({ length: 4 }).notNull(),
	text: longtext().notNull(),
},
(table) => [
	primaryKey({ columns: [table.realmid, table.id, table.locale] }),]);

export const build_info = mysqlTable("build_info", {
	build: int().primaryKey(),
	majorVersion: int(),
	minorVersion: int(),
	bugfixVersion: int(),
	hotfixVersion: char({ length: 3 }),
	winAuthSeed: varchar({ length: 32 }),
	win64AuthSeed: varchar({ length: 32 }),
	mac64AuthSeed: varchar({ length: 32 }),
	winChecksumSeed: varchar({ length: 40 }),
	macChecksumSeed: varchar({ length: 40 }),
});

export const ip_banned = mysqlTable("ip_banned", {
	ip: varchar({ length: 15 }).default("127.0.0.1").notNull(),
	bandate: int({ unsigned: true }).notNull(),
	unbandate: int({ unsigned: true }).notNull(),
	bannedby: varchar({ length: 50 }).default("[Console]").notNull(),
	banreason: varchar({ length: 255 }).default("no reason").notNull(),
},
(table) => [
	primaryKey({ columns: [table.ip, table.bandate] }),]);

export const logs = mysqlTable("logs", {
	time: int({ unsigned: true }).notNull(),
	realm: int({ unsigned: true }).notNull(),
	type: varchar({ length: 250 }).notNull(),
	level: tinyint({ unsigned: true }).default(0).notNull(),
	string: text(),
});

export const logs_ip_actions = mysqlTable("logs_ip_actions", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	account_id: int({ unsigned: true }).notNull(),
	character_guid: int({ unsigned: true }).notNull(),
	type: tinyint({ unsigned: true }).notNull(),
	ip: varchar({ length: 15 }).default("127.0.0.1").notNull(),
	systemnote: text(),
	unixtime: int({ unsigned: true }).notNull(),
	time: timestamp().defaultNow().notNull(),
	comment: text(),
});

export const motd = mysqlTable("motd", {
	realmid: int().primaryKey(),
	text: longtext(),
});

export const motd_localized = mysqlTable("motd_localized", {
	realmid: int().notNull(),
	locale: varchar({ length: 4 }).notNull(),
	text: longtext(),
},
(table) => [
	primaryKey({ columns: [table.realmid, table.locale] }),]);

export const rbac_account_permissions = mysqlTable("rbac_account_permissions", {
	accountId: int({ unsigned: true }).notNull().references(() => account.id, { onDelete: "cascade" } ),
	permissionId: int({ unsigned: true }).notNull().references(() => rbac_permissions.id, { onDelete: "cascade" } ),
	granted: boolean().default(true).notNull(),
	realmId: int().default(-1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.accountId, table.permissionId, table.realmId] }),]);

export const rbac_default_permissions = mysqlTable("rbac_default_permissions", {
	secId: int({ unsigned: true }).notNull(),
	permissionId: int({ unsigned: true }).notNull().references(() => rbac_permissions.id),
	realmId: int().default(-1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.secId, table.permissionId, table.realmId] }),]);

export const rbac_linked_permissions = mysqlTable("rbac_linked_permissions", {
	id: int({ unsigned: true }).notNull().references(() => rbac_permissions.id, { onDelete: "cascade" } ),
	linkedId: int({ unsigned: true }).notNull().references(() => rbac_permissions.id, { onDelete: "cascade" } ),
},
(table) => [
	primaryKey({ columns: [table.id, table.linkedId] }),]);

export const rbac_permissions = mysqlTable("rbac_permissions", {
	id: int({ unsigned: true }).default(0).primaryKey(),
	name: varchar({ length: 100 }).notNull(),
});

export const realmcharacters = mysqlTable("realmcharacters", {
	realmid: int({ unsigned: true }).default(0).notNull(),
	acctid: int({ unsigned: true }).notNull(),
	numchars: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.realmid, table.acctid] }),	index("acctid").on(table.acctid),
]);

export const realmlist = mysqlTable("realmlist", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	name: varchar({ length: 32 }).default("").notNull(),
	address: varchar({ length: 255 }).default("127.0.0.1").notNull(),
	localAddress: varchar({ length: 255 }).default("127.0.0.1").notNull(),
	localSubnetMask: varchar({ length: 255 }).default("255.255.255.0").notNull(),
	port: smallint({ unsigned: true }).default(8085).notNull(),
	icon: tinyint({ unsigned: true }).default(0).notNull(),
	flag: tinyint({ unsigned: true }).default(2).notNull(),
	timezone: tinyint({ unsigned: true }).default(0).notNull(),
	allowedSecurityLevel: tinyint({ unsigned: true }).default(0).notNull(),
	population: float().default(0).notNull(),
	gamebuild: int({ unsigned: true }).default(12340).notNull(),
},
(table) => [
	uniqueIndex("idx_name").on(table.name),
	check("realmlist_chk_1", sql`(\`population\` >= 0)`),
]);

export const secret_digest = mysqlTable("secret_digest", {
	id: int({ unsigned: true }).primaryKey(),
	digest: varchar({ length: 100 }).notNull(),
});

export const updates = mysqlTable("updates", {
	name: varchar({ length: 200 }).primaryKey(),
	hash: char({ length: 40 }).default(""),
	state: mysqlEnum(["RELEASED","CUSTOM","MODULE","ARCHIVED","PENDING"]).default("RELEASED").notNull(),
	timestamp: timestamp().defaultNow().notNull(),
	speed: int({ unsigned: true }).default(0).notNull(),
});

export const updates_include = mysqlTable("updates_include", {
	path: varchar({ length: 200 }).primaryKey(),
	state: mysqlEnum(["RELEASED","ARCHIVED","CUSTOM","PENDING"]).default("RELEASED").notNull(),
});

export const uptime = mysqlTable("uptime", {
	realmid: int({ unsigned: true }).notNull(),
	starttime: int({ unsigned: true }).default(0).notNull(),
	uptime: int({ unsigned: true }).default(0).notNull(),
	maxplayers: smallint({ unsigned: true }).default(0).notNull(),
	revision: varchar({ length: 255 }).default("AzerothCore").notNull(),
},
(table) => [
	primaryKey({ columns: [table.realmid, table.starttime] }),]);
