/** Generated by `src/tools/gen-db-schema.ts` from `acore_characters` (`sql/base/db_characters` plus `data/sql/updates/`). Do not edit. */
import { mysqlTable, mysqlSchema, type AnyMySqlColumn, int, tinyint, blob, bigint, varchar, smallint, timestamp, datetime, longtext, text, float, tinytext, char, mysqlEnum, customType, primaryKey, index, uniqueIndex, foreignKey, check } from "drizzle-orm/mysql-core"
import { sql } from "drizzle-orm"

export const account_data = mysqlTable("account_data", {
	accountId: int({ unsigned: true }).default(0).notNull(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
	time: int({ unsigned: true }).default(0).notNull(),
	data: blob({ mode: "buffer" }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.accountId, table.type] }),]);

export const account_instance_times = mysqlTable("account_instance_times", {
	accountId: int({ unsigned: true }).notNull(),
	instanceId: int({ unsigned: true }).default(0).notNull(),
	releaseTime: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
},
(table) => [
	primaryKey({ columns: [table.accountId, table.instanceId] }),]);

export const account_tutorial = mysqlTable("account_tutorial", {
	accountId: int({ unsigned: true }).default(0).primaryKey(),
	tut0: int({ unsigned: true }).default(0).notNull(),
	tut1: int({ unsigned: true }).default(0).notNull(),
	tut2: int({ unsigned: true }).default(0).notNull(),
	tut3: int({ unsigned: true }).default(0).notNull(),
	tut4: int({ unsigned: true }).default(0).notNull(),
	tut5: int({ unsigned: true }).default(0).notNull(),
	tut6: int({ unsigned: true }).default(0).notNull(),
	tut7: int({ unsigned: true }).default(0).notNull(),
});

export const active_arena_season = mysqlTable("active_arena_season", {
	season_id: tinyint({ unsigned: true }).notNull(),
	season_state: tinyint({ unsigned: true }).notNull(),
});

export const addons = mysqlTable("addons", {
	name: varchar({ length: 120 }).default("").primaryKey(),
	crc: int({ unsigned: true }).default(0).notNull(),
});

export const arena_team = mysqlTable("arena_team", {
	arenaTeamId: int({ unsigned: true }).default(0).primaryKey(),
	name: varchar({ length: 24 }).notNull(),
	captainGuid: int({ unsigned: true }).default(0).notNull(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
	rating: smallint({ unsigned: true }).default(0).notNull(),
	seasonGames: smallint({ unsigned: true }).default(0).notNull(),
	seasonWins: smallint({ unsigned: true }).default(0).notNull(),
	weekGames: smallint({ unsigned: true }).default(0).notNull(),
	weekWins: smallint({ unsigned: true }).default(0).notNull(),
	rank: int({ unsigned: true }).default(0).notNull(),
	backgroundColor: int({ unsigned: true }).default(0).notNull(),
	emblemStyle: tinyint({ unsigned: true }).default(0).notNull(),
	emblemColor: int({ unsigned: true }).default(0).notNull(),
	borderStyle: tinyint({ unsigned: true }).default(0).notNull(),
	borderColor: int({ unsigned: true }).default(0).notNull(),
});

export const arena_team_member = mysqlTable("arena_team_member", {
	arenaTeamId: int({ unsigned: true }).default(0).notNull(),
	guid: int({ unsigned: true }).default(0).notNull(),
	weekGames: smallint({ unsigned: true }).default(0).notNull(),
	weekWins: smallint({ unsigned: true }).default(0).notNull(),
	seasonGames: smallint({ unsigned: true }).default(0).notNull(),
	seasonWins: smallint({ unsigned: true }).default(0).notNull(),
	personalRating: smallint().default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.arenaTeamId, table.guid] }),]);

export const auctionhouse = mysqlTable("auctionhouse", {
	id: int({ unsigned: true }).default(0).primaryKey(),
	houseid: tinyint({ unsigned: true }).default(7).notNull(),
	itemguid: int({ unsigned: true }).default(0).notNull(),
	itemowner: int({ unsigned: true }).default(0).notNull(),
	buyoutprice: int({ unsigned: true }).default(0).notNull(),
	time: int({ unsigned: true }).default(0).notNull(),
	buyguid: int({ unsigned: true }).default(0).notNull(),
	lastbid: int({ unsigned: true }).default(0).notNull(),
	startbid: int({ unsigned: true }).default(0).notNull(),
	deposit: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	uniqueIndex("item_guid").on(table.itemguid),
]);

export const banned_addons = mysqlTable("banned_addons", {
	Id: int({ unsigned: true }).autoincrement().primaryKey(),
	Name: varchar({ length: 255 }).notNull(),
	Version: varchar({ length: 255 }).default("").notNull(),
	Timestamp: timestamp().defaultNow().onUpdateNow().notNull(),
},
(table) => [
	uniqueIndex("idx_name_ver").on(table.Name, table.Version),
]);

export const battleground_deserters = mysqlTable("battleground_deserters", {
	guid: int({ unsigned: true }).notNull(),
	type: tinyint({ unsigned: true }).notNull(),
	datetime: datetime().notNull(),
});

export const bugreport = mysqlTable("bugreport", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	type: longtext().notNull(),
	content: longtext().notNull(),
	State: tinyint().default(1).notNull(),
	Assignee: varchar({ length: 255 }),
	Comment: longtext(),
});

export const calendar_events = mysqlTable("calendar_events", {
	id: bigint({ unsigned: true, mode: 'bigint' }).default(0n).primaryKey(),
	creator: int({ unsigned: true }).default(0).notNull(),
	title: varchar({ length: 255 }).default("").notNull(),
	description: varchar({ length: 255 }).default("").notNull(),
	type: tinyint({ unsigned: true }).default(4).notNull(),
	dungeon: int().default(-1).notNull(),
	eventtime: int({ unsigned: true }).default(0).notNull(),
	flags: int({ unsigned: true }).default(0).notNull(),
	time2: int({ unsigned: true }).default(0).notNull(),
});

export const calendar_invites = mysqlTable("calendar_invites", {
	id: bigint({ unsigned: true, mode: 'bigint' }).default(0n).primaryKey(),
	event: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
	invitee: int({ unsigned: true }).default(0).notNull(),
	sender: int({ unsigned: true }).default(0).notNull(),
	status: tinyint({ unsigned: true }).default(0).notNull(),
	statustime: int({ unsigned: true }).default(0).notNull(),
	rank: tinyint({ unsigned: true }).default(0).notNull(),
	text: varchar({ length: 255 }).default("").notNull(),
});

export const channels = mysqlTable("channels", {
	channelId: int({ unsigned: true }).autoincrement().primaryKey(),
	name: varchar({ length: 128 }).notNull(),
	team: int({ unsigned: true }).notNull(),
	announce: tinyint({ unsigned: true }).default(1).notNull(),
	ownership: tinyint({ unsigned: true }).default(1).notNull(),
	password: varchar({ length: 32 }),
	lastUsed: int({ unsigned: true }).notNull(),
});

export const channels_bans = mysqlTable("channels_bans", {
	channelId: int({ unsigned: true }).notNull(),
	playerGUID: int({ unsigned: true }).notNull(),
	banTime: int({ unsigned: true }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.channelId, table.playerGUID] }),]);

export const channels_rights = mysqlTable("channels_rights", {
	name: varchar({ length: 128 }).primaryKey(),
	flags: int({ unsigned: true }).notNull(),
	speakdelay: int({ unsigned: true }).notNull(),
	joinmessage: varchar({ length: 255 }).default("").notNull(),
	delaymessage: varchar({ length: 255 }).default("").notNull(),
	moderators: text(),
});

export const character_account_data = mysqlTable("character_account_data", {
	guid: int({ unsigned: true }).default(0).notNull(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
	time: int({ unsigned: true }).default(0).notNull(),
	data: blob({ mode: "buffer" }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.type] }),]);

export const character_achievement = mysqlTable("character_achievement", {
	guid: int({ unsigned: true }).notNull(),
	achievement: smallint({ unsigned: true }).notNull(),
	date: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.achievement] }),]);

export const character_achievement_offline_updates = mysqlTable("character_achievement_offline_updates", {
	guid: int({ unsigned: true }).notNull(),
	update_type: tinyint({ unsigned: true }).notNull(),
	arg1: int({ unsigned: true }).notNull(),
	arg2: int({ unsigned: true }),
	arg3: int({ unsigned: true }),
},
(table) => [
	index("idx_guid").on(table.guid),
]);

export const character_achievement_progress = mysqlTable("character_achievement_progress", {
	guid: int({ unsigned: true }).notNull(),
	criteria: smallint({ unsigned: true }).notNull(),
	counter: int({ unsigned: true }).notNull(),
	date: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.criteria] }),]);

export const character_action = mysqlTable("character_action", {
	guid: int({ unsigned: true }).default(0).notNull(),
	spec: tinyint({ unsigned: true }).default(0).notNull(),
	button: tinyint({ unsigned: true }).default(0).notNull(),
	action: int({ unsigned: true }).default(0).notNull(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.spec, table.button] }),]);

export const character_arena_stats = mysqlTable("character_arena_stats", {
	guid: int({ unsigned: true }).default(0).notNull(),
	slot: tinyint({ unsigned: true }).default(0).notNull(),
	matchMakerRating: smallint({ unsigned: true }).default(0).notNull(),
	maxMMR: smallint().notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.slot] }),]);

export const character_aura = mysqlTable("character_aura", {
	guid: int({ unsigned: true }).default(0).notNull(),
	casterGuid: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
	itemGuid: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
	spell: int({ unsigned: true }).default(0).notNull(),
	effectMask: tinyint({ unsigned: true }).default(0).notNull(),
	recalculateMask: tinyint({ unsigned: true }).default(0).notNull(),
	stackCount: tinyint({ unsigned: true }).default(1).notNull(),
	amount0: int().default(0).notNull(),
	amount1: int().default(0).notNull(),
	amount2: int().default(0).notNull(),
	base_amount0: int().default(0).notNull(),
	base_amount1: int().default(0).notNull(),
	base_amount2: int().default(0).notNull(),
	maxDuration: int().default(0).notNull(),
	remainTime: int().default(0).notNull(),
	remainCharges: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.casterGuid, table.itemGuid, table.spell, table.effectMask] }),]);

export const character_banned = mysqlTable("character_banned", {
	guid: int({ unsigned: true }).default(0).notNull(),
	bandate: int({ unsigned: true }).default(0).notNull(),
	unbandate: int({ unsigned: true }).default(0).notNull(),
	bannedby: varchar({ length: 50 }).notNull(),
	banreason: varchar({ length: 255 }).notNull(),
	active: tinyint({ unsigned: true }).default(1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.bandate] }),]);

export const character_battleground_random = mysqlTable("character_battleground_random", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
});

export const character_brew_of_the_month = mysqlTable("character_brew_of_the_month", {
	guid: int({ unsigned: true }).primaryKey(),
	lastEventId: int({ unsigned: true }).default(0).notNull(),
});

export const character_declinedname = mysqlTable("character_declinedname", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	genitive: varchar({ length: 15 }).default("").notNull(),
	dative: varchar({ length: 15 }).default("").notNull(),
	accusative: varchar({ length: 15 }).default("").notNull(),
	instrumental: varchar({ length: 15 }).default("").notNull(),
	prepositional: varchar({ length: 15 }).default("").notNull(),
});

export const character_entry_point = mysqlTable("character_entry_point", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	joinX: float().default(0).notNull(),
	joinY: float().default(0).notNull(),
	joinZ: float().default(0).notNull(),
	joinO: float().default(0).notNull(),
	joinMapId: int({ unsigned: true }).default(0).notNull(),
	taxiPath0: int({ unsigned: true }).default(0).notNull(),
	taxiPath1: int({ unsigned: true }).default(0).notNull(),
	mountSpell: int({ unsigned: true }).default(0).notNull(),
});

export const character_equipmentsets = mysqlTable("character_equipmentsets", {
	guid: int().default(0).notNull(),
	setguid: bigint({ mode: 'number' }).autoincrement().primaryKey(),
	setindex: tinyint({ unsigned: true }).default(0).notNull(),
	name: varchar({ length: 31 }).notNull(),
	iconname: varchar({ length: 100 }).notNull(),
	ignore_mask: int({ unsigned: true }).default(0).notNull(),
	item0: int({ unsigned: true }).default(0).notNull(),
	item1: int({ unsigned: true }).default(0).notNull(),
	item2: int({ unsigned: true }).default(0).notNull(),
	item3: int({ unsigned: true }).default(0).notNull(),
	item4: int({ unsigned: true }).default(0).notNull(),
	item5: int({ unsigned: true }).default(0).notNull(),
	item6: int({ unsigned: true }).default(0).notNull(),
	item7: int({ unsigned: true }).default(0).notNull(),
	item8: int({ unsigned: true }).default(0).notNull(),
	item9: int({ unsigned: true }).default(0).notNull(),
	item10: int({ unsigned: true }).default(0).notNull(),
	item11: int({ unsigned: true }).default(0).notNull(),
	item12: int({ unsigned: true }).default(0).notNull(),
	item13: int({ unsigned: true }).default(0).notNull(),
	item14: int({ unsigned: true }).default(0).notNull(),
	item15: int({ unsigned: true }).default(0).notNull(),
	item16: int({ unsigned: true }).default(0).notNull(),
	item17: int({ unsigned: true }).default(0).notNull(),
	item18: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	uniqueIndex("idx_set").on(table.guid, table.setguid, table.setindex),
	index("Idx_setindex").on(table.setindex),
]);

export const character_gifts = mysqlTable("character_gifts", {
	guid: int({ unsigned: true }).default(0).notNull(),
	item_guid: int({ unsigned: true }).default(0).primaryKey(),
	entry: int({ unsigned: true }).default(0).notNull(),
	flags: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	index("idx_guid").on(table.guid),
]);

export const character_glyphs = mysqlTable("character_glyphs", {
	guid: int({ unsigned: true }).notNull(),
	talentGroup: tinyint({ unsigned: true }).default(0).notNull(),
	glyph1: smallint({ unsigned: true }).default(0),
	glyph2: smallint({ unsigned: true }).default(0),
	glyph3: smallint({ unsigned: true }).default(0),
	glyph4: smallint({ unsigned: true }).default(0),
	glyph5: smallint({ unsigned: true }).default(0),
	glyph6: smallint({ unsigned: true }).default(0),
},
(table) => [
	primaryKey({ columns: [table.guid, table.talentGroup] }),]);

export const character_homebind = mysqlTable("character_homebind", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	mapId: smallint({ unsigned: true }).default(0).notNull(),
	zoneId: smallint({ unsigned: true }).default(0).notNull(),
	posX: float().default(0).notNull(),
	posY: float().default(0).notNull(),
	posZ: float().default(0).notNull(),
});

export const character_instance = mysqlTable("character_instance", {
	guid: int({ unsigned: true }).default(0).notNull(),
	instance: int({ unsigned: true }).default(0).notNull(),
	permanent: tinyint({ unsigned: true }).default(0).notNull(),
	extended: tinyint({ unsigned: true }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.instance] }),	index("instance").on(table.instance),
]);

export const character_inventory = mysqlTable("character_inventory", {
	guid: int({ unsigned: true }).default(0).notNull(),
	bag: int({ unsigned: true }).default(0).notNull(),
	slot: tinyint({ unsigned: true }).default(0).notNull(),
	item: int({ unsigned: true }).default(0).primaryKey(),
},
(table) => [
	uniqueIndex("guid").on(table.guid, table.bag, table.slot),
	index("idx_guid").on(table.guid),
]);

export const character_pet = mysqlTable("character_pet", {
	id: int({ unsigned: true }).default(0).primaryKey(),
	entry: int({ unsigned: true }).default(0).notNull(),
	owner: int({ unsigned: true }).default(0).notNull(),
	modelid: int({ unsigned: true }).default(0),
	CreatedBySpell: int({ unsigned: true }).default(0),
	PetType: tinyint({ unsigned: true }).default(0).notNull(),
	level: smallint({ unsigned: true }).default(1).notNull(),
	exp: int({ unsigned: true }).default(0).notNull(),
	Reactstate: tinyint({ unsigned: true }).default(0).notNull(),
	name: varchar({ length: 21 }).default("Pet").notNull(),
	renamed: tinyint({ unsigned: true }).default(0).notNull(),
	slot: tinyint({ unsigned: true }).default(0).notNull(),
	curhealth: int({ unsigned: true }).default(1).notNull(),
	curmana: int({ unsigned: true }).default(0).notNull(),
	curhappiness: int({ unsigned: true }).default(0).notNull(),
	savetime: int({ unsigned: true }).default(0).notNull(),
	abdata: text(),
},
(table) => [
	index("owner").on(table.owner),
	index("idx_slot").on(table.slot),
]);

export const character_pet_declinedname = mysqlTable("character_pet_declinedname", {
	id: int({ unsigned: true }).default(0).primaryKey(),
	owner: int({ unsigned: true }).default(0).notNull(),
	genitive: varchar({ length: 12 }).default("").notNull(),
	dative: varchar({ length: 12 }).default("").notNull(),
	accusative: varchar({ length: 12 }).default("").notNull(),
	instrumental: varchar({ length: 12 }).default("").notNull(),
	prepositional: varchar({ length: 12 }).default("").notNull(),
},
(table) => [
	index("owner_key").on(table.owner),
]);

export const character_queststatus = mysqlTable("character_queststatus", {
	guid: int({ unsigned: true }).default(0).notNull(),
	quest: int({ unsigned: true }).default(0).notNull(),
	status: tinyint({ unsigned: true }).default(0).notNull(),
	explored: tinyint({ unsigned: true }).default(0).notNull(),
	timer: int({ unsigned: true }).default(0).notNull(),
	mobcount1: smallint({ unsigned: true }).default(0).notNull(),
	mobcount2: smallint({ unsigned: true }).default(0).notNull(),
	mobcount3: smallint({ unsigned: true }).default(0).notNull(),
	mobcount4: smallint({ unsigned: true }).default(0).notNull(),
	itemcount1: smallint({ unsigned: true }).default(0).notNull(),
	itemcount2: smallint({ unsigned: true }).default(0).notNull(),
	itemcount3: smallint({ unsigned: true }).default(0).notNull(),
	itemcount4: smallint({ unsigned: true }).default(0).notNull(),
	itemcount5: smallint({ unsigned: true }).default(0).notNull(),
	itemcount6: smallint({ unsigned: true }).default(0).notNull(),
	playercount: smallint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.quest] }),]);

export const character_queststatus_daily = mysqlTable("character_queststatus_daily", {
	guid: int({ unsigned: true }).default(0).notNull(),
	quest: int({ unsigned: true }).default(0).notNull(),
	time: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.quest] }),	index("idx_guid").on(table.guid),
]);

export const character_queststatus_monthly = mysqlTable("character_queststatus_monthly", {
	guid: int({ unsigned: true }).default(0).notNull(),
	quest: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.quest] }),	index("idx_guid").on(table.guid),
]);

export const character_queststatus_rewarded = mysqlTable("character_queststatus_rewarded", {
	guid: int({ unsigned: true }).default(0).notNull(),
	quest: int({ unsigned: true }).default(0).notNull(),
	active: tinyint({ unsigned: true }).default(1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.quest] }),]);

export const character_queststatus_seasonal = mysqlTable("character_queststatus_seasonal", {
	guid: int({ unsigned: true }).default(0).notNull(),
	quest: int({ unsigned: true }).default(0).notNull(),
	event: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.quest] }),	index("idx_guid").on(table.guid),
]);

export const character_queststatus_weekly = mysqlTable("character_queststatus_weekly", {
	guid: int({ unsigned: true }).default(0).notNull(),
	quest: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.quest] }),	index("idx_guid").on(table.guid),
]);

export const character_reputation = mysqlTable("character_reputation", {
	guid: int({ unsigned: true }).default(0).notNull(),
	faction: smallint({ unsigned: true }).default(0).notNull(),
	standing: int().default(0).notNull(),
	flags: smallint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.faction] }),]);

export const character_settings = mysqlTable("character_settings", {
	guid: int({ unsigned: true }).notNull(),
	source: varchar({ length: 40 }).notNull(),
	data: text(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.source] }),]);

export const character_skills = mysqlTable("character_skills", {
	guid: int({ unsigned: true }).notNull(),
	skill: smallint({ unsigned: true }).notNull(),
	value: smallint({ unsigned: true }).notNull(),
	max: smallint({ unsigned: true }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.skill] }),]);

export const character_social = mysqlTable("character_social", {
	guid: int({ unsigned: true }).default(0).notNull(),
	friend: int({ unsigned: true }).default(0).notNull(),
	flags: tinyint({ unsigned: true }).default(0).notNull(),
	note: varchar({ length: 48 }).default("").notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.friend, table.flags] }),	index("friend").on(table.friend),
]);

export const character_spell = mysqlTable("character_spell", {
	guid: int({ unsigned: true }).default(0).notNull(),
	spell: int({ unsigned: true }).default(0).notNull(),
	specMask: tinyint({ unsigned: true }).default(1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.spell] }),]);

export const character_spell_cooldown = mysqlTable("character_spell_cooldown", {
	guid: int({ unsigned: true }).default(0).notNull(),
	spell: int({ unsigned: true }).default(0).notNull(),
	category: int({ unsigned: true }).default(0),
	item: int({ unsigned: true }).default(0).notNull(),
	time: int({ unsigned: true }).default(0).notNull(),
	needSend: tinyint({ unsigned: true }).default(1).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.spell] }),]);

export const character_stats = mysqlTable("character_stats", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	maxhealth: int({ unsigned: true }).default(0).notNull(),
	maxpower1: int({ unsigned: true }).default(0).notNull(),
	maxpower2: int({ unsigned: true }).default(0).notNull(),
	maxpower3: int({ unsigned: true }).default(0).notNull(),
	maxpower4: int({ unsigned: true }).default(0).notNull(),
	maxpower5: int({ unsigned: true }).default(0).notNull(),
	maxpower6: int({ unsigned: true }).default(0).notNull(),
	maxpower7: int({ unsigned: true }).default(0).notNull(),
	strength: int({ unsigned: true }).default(0).notNull(),
	agility: int({ unsigned: true }).default(0).notNull(),
	stamina: int({ unsigned: true }).default(0).notNull(),
	intellect: int({ unsigned: true }).default(0).notNull(),
	spirit: int({ unsigned: true }).default(0).notNull(),
	armor: int({ unsigned: true }).default(0).notNull(),
	resHoly: int({ unsigned: true }).default(0).notNull(),
	resFire: int({ unsigned: true }).default(0).notNull(),
	resNature: int({ unsigned: true }).default(0).notNull(),
	resFrost: int({ unsigned: true }).default(0).notNull(),
	resShadow: int({ unsigned: true }).default(0).notNull(),
	resArcane: int({ unsigned: true }).default(0).notNull(),
	blockPct: float().default(0).notNull(),
	dodgePct: float().default(0).notNull(),
	parryPct: float().default(0).notNull(),
	critPct: float().default(0).notNull(),
	rangedCritPct: float().default(0).notNull(),
	spellCritPct: float().default(0).notNull(),
	attackPower: int({ unsigned: true }).default(0).notNull(),
	rangedAttackPower: int({ unsigned: true }).default(0).notNull(),
	spellPower: int({ unsigned: true }).default(0).notNull(),
	resilience: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	check("character_stats_chk_1", sql`((\`blockPct\` >= 0) and (\`dodgePct\` >= 0) and (\`parryPct\` >= 0) and (\`critPct\` >= 0) and (\`rangedCritPct\` >= 0) and (\`spellCritPct\` >= 0))`),
]);

export const character_talent = mysqlTable("character_talent", {
	guid: int({ unsigned: true }).notNull(),
	spell: int({ unsigned: true }).notNull(),
	specMask: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.spell] }),]);

export const characters = mysqlTable("characters", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	account: int({ unsigned: true }).default(0).notNull(),
	name: varchar({ length: 12 }).charSet("utf8mb4").collate("utf8mb4_bin").notNull(),
	race: tinyint({ unsigned: true }).default(0).notNull(),
	class: tinyint({ unsigned: true }).default(0).notNull(),
	gender: tinyint({ unsigned: true }).default(0).notNull(),
	level: tinyint({ unsigned: true }).default(0).notNull(),
	xp: int({ unsigned: true }).default(0).notNull(),
	money: int({ unsigned: true }).default(0).notNull(),
	skin: tinyint({ unsigned: true }).default(0).notNull(),
	face: tinyint({ unsigned: true }).default(0).notNull(),
	hairStyle: tinyint({ unsigned: true }).default(0).notNull(),
	hairColor: tinyint({ unsigned: true }).default(0).notNull(),
	facialStyle: tinyint({ unsigned: true }).default(0).notNull(),
	bankSlots: tinyint({ unsigned: true }).default(0).notNull(),
	restState: tinyint({ unsigned: true }).default(0).notNull(),
	playerFlags: int({ unsigned: true }).default(0).notNull(),
	position_x: float().default(0).notNull(),
	position_y: float().default(0).notNull(),
	position_z: float().default(0).notNull(),
	map: smallint({ unsigned: true }).default(0).notNull(),
	instance_id: int({ unsigned: true }).default(0).notNull(),
	instance_mode_mask: tinyint({ unsigned: true }).default(0).notNull(),
	orientation: float().default(0).notNull(),
	taximask: text().notNull(),
	online: tinyint({ unsigned: true }).default(0).notNull(),
	cinematic: tinyint({ unsigned: true }).default(0).notNull(),
	totaltime: int({ unsigned: true }).default(0).notNull(),
	leveltime: int({ unsigned: true }).default(0).notNull(),
	logout_time: int({ unsigned: true }).default(0).notNull(),
	is_logout_resting: tinyint({ unsigned: true }).default(0).notNull(),
	rest_bonus: float().default(0).notNull(),
	resettalents_cost: int({ unsigned: true }).default(0).notNull(),
	resettalents_time: int({ unsigned: true }).default(0).notNull(),
	trans_x: float().default(0).notNull(),
	trans_y: float().default(0).notNull(),
	trans_z: float().default(0).notNull(),
	trans_o: float().default(0).notNull(),
	transguid: int().default(0),
	extra_flags: smallint({ unsigned: true }).default(0).notNull(),
	stable_slots: tinyint({ unsigned: true }).default(0).notNull(),
	at_login: smallint({ unsigned: true }).default(0).notNull(),
	zone: smallint({ unsigned: true }).default(0).notNull(),
	death_expire_time: int({ unsigned: true }).default(0).notNull(),
	taxi_path: text(),
	arenaPoints: int({ unsigned: true }).default(0).notNull(),
	totalHonorPoints: int({ unsigned: true }).default(0).notNull(),
	todayHonorPoints: int({ unsigned: true }).default(0).notNull(),
	yesterdayHonorPoints: int({ unsigned: true }).default(0).notNull(),
	totalKills: int({ unsigned: true }).default(0).notNull(),
	todayKills: smallint({ unsigned: true }).default(0).notNull(),
	yesterdayKills: smallint({ unsigned: true }).default(0).notNull(),
	chosenTitle: int({ unsigned: true }).default(0).notNull(),
	knownCurrencies: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
	watchedFaction: int({ unsigned: true }).default(0).notNull(),
	drunk: tinyint({ unsigned: true }).default(0).notNull(),
	health: int({ unsigned: true }).default(0).notNull(),
	power1: int({ unsigned: true }).default(0).notNull(),
	power2: int({ unsigned: true }).default(0).notNull(),
	power3: int({ unsigned: true }).default(0).notNull(),
	power4: int({ unsigned: true }).default(0).notNull(),
	power5: int({ unsigned: true }).default(0).notNull(),
	power6: int({ unsigned: true }).default(0).notNull(),
	power7: int({ unsigned: true }).default(0).notNull(),
	latency: int({ unsigned: true }).default(0),
	talentGroupsCount: tinyint({ unsigned: true }).default(1).notNull(),
	activeTalentGroup: tinyint({ unsigned: true }).default(0).notNull(),
	exploredZones: longtext(),
	equipmentCache: longtext(),
	ammoId: int({ unsigned: true }).default(0).notNull(),
	knownTitles: longtext(),
	actionBars: tinyint({ unsigned: true }).default(0).notNull(),
	grantableLevels: tinyint({ unsigned: true }).default(0).notNull(),
	order: tinyint(),
	creation_date: timestamp().defaultNow().notNull(),
	deleteInfos_Account: int({ unsigned: true }),
	deleteInfos_Name: varchar({ length: 12 }),
	deleteDate: int({ unsigned: true }),
	innTriggerId: int({ unsigned: true }).notNull(),
	extraBonusTalentCount: int().default(0).notNull(),
},
(table) => [
	index("idx_online").on(table.online),
	index("idx_name").on(table.name),
	index("idx_account").on(table.account),
]);

export const chat_filter = mysqlTable("chat_filter", {
	ID: int({ unsigned: true }).autoincrement().primaryKey(),
	Word: varchar({ length: 255 }).notNull(),
});

export const corpse = mysqlTable("corpse", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	posX: float().default(0).notNull(),
	posY: float().default(0).notNull(),
	posZ: float().default(0).notNull(),
	orientation: float().default(0).notNull(),
	mapId: smallint({ unsigned: true }).default(0).notNull(),
	phaseMask: int({ unsigned: true }).default(1).notNull(),
	displayId: int({ unsigned: true }).default(0).notNull(),
	itemCache: text().notNull(),
	bytes1: int({ unsigned: true }).default(0).notNull(),
	bytes2: int({ unsigned: true }).default(0).notNull(),
	guildId: int({ unsigned: true }).default(0).notNull(),
	flags: tinyint({ unsigned: true }).default(0).notNull(),
	dynFlags: tinyint({ unsigned: true }).default(0).notNull(),
	time: int({ unsigned: true }).default(0).notNull(),
	corpseType: tinyint({ unsigned: true }).default(0).notNull(),
	instanceId: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	index("idx_time").on(table.time),
	index("idx_type").on(table.corpseType),
	index("idx_instance").on(table.instanceId),
]);

export const creature_respawn = mysqlTable("creature_respawn", {
	guid: int({ unsigned: true }).default(0).notNull(),
	respawnTime: int({ unsigned: true }).default(0).notNull(),
	mapId: smallint({ unsigned: true }).default(0).notNull(),
	instanceId: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.instanceId] }),	index("idx_instance").on(table.instanceId),
]);

export const game_event_condition_save = mysqlTable("game_event_condition_save", {
	eventEntry: tinyint({ unsigned: true }).notNull(),
	condition_id: int({ unsigned: true }).default(0).notNull(),
	done: float().default(0),
},
(table) => [
	primaryKey({ columns: [table.eventEntry, table.condition_id] }),]);

export const game_event_save = mysqlTable("game_event_save", {
	eventEntry: tinyint({ unsigned: true }).primaryKey(),
	state: tinyint({ unsigned: true }).default(1).notNull(),
	next_start: int({ unsigned: true }).default(0).notNull(),
});

export const gameobject_respawn = mysqlTable("gameobject_respawn", {
	guid: int({ unsigned: true }).default(0).notNull(),
	respawnTime: int({ unsigned: true }).default(0).notNull(),
	mapId: smallint({ unsigned: true }).default(0).notNull(),
	instanceId: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.instanceId] }),	index("idx_instance").on(table.instanceId),
]);

export const gm_subsurvey = mysqlTable("gm_subsurvey", {
	surveyId: int({ unsigned: true }).autoincrement().notNull(),
	questionId: int({ unsigned: true }).default(0).notNull(),
	answer: int({ unsigned: true }).default(0).notNull(),
	answerComment: text().notNull(),
},
(table) => [
	primaryKey({ columns: [table.surveyId, table.questionId] }),]);

export const gm_survey = mysqlTable("gm_survey", {
	surveyId: int({ unsigned: true }).autoincrement().primaryKey(),
	guid: int({ unsigned: true }).default(0).notNull(),
	mainSurvey: int({ unsigned: true }).default(0).notNull(),
	comment: longtext().notNull(),
	createTime: int({ unsigned: true }).default(0).notNull(),
	maxMMR: smallint().notNull(),
});

export const gm_ticket = mysqlTable("gm_ticket", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
	playerGuid: int({ unsigned: true }).default(0).notNull(),
	name: varchar({ length: 12 }).notNull(),
	description: text().notNull(),
	createTime: int({ unsigned: true }).default(0).notNull(),
	mapId: smallint({ unsigned: true }).default(0).notNull(),
	posX: float().default(0).notNull(),
	posY: float().default(0).notNull(),
	posZ: float().default(0).notNull(),
	lastModifiedTime: int({ unsigned: true }).default(0).notNull(),
	closedBy: int().default(0).notNull(),
	assignedTo: int({ unsigned: true }).default(0).notNull(),
	comment: text().notNull(),
	response: text().notNull(),
	completed: tinyint({ unsigned: true }).default(0).notNull(),
	escalated: tinyint({ unsigned: true }).default(0).notNull(),
	viewed: tinyint({ unsigned: true }).default(0).notNull(),
	needMoreHelp: tinyint({ unsigned: true }).default(0).notNull(),
	resolvedBy: int().default(0).notNull(),
});

export const group_member = mysqlTable("group_member", {
	guid: int({ unsigned: true }).notNull(),
	memberGuid: int({ unsigned: true }).primaryKey(),
	memberFlags: tinyint({ unsigned: true }).default(0).notNull(),
	subgroup: tinyint({ unsigned: true }).default(0).notNull(),
	roles: tinyint({ unsigned: true }).default(0).notNull(),
});

export const groups = mysqlTable("groups", {
	guid: int({ unsigned: true }).primaryKey(),
	leaderGuid: int({ unsigned: true }).notNull(),
	lootMethod: tinyint({ unsigned: true }).notNull(),
	looterGuid: int({ unsigned: true }).notNull(),
	lootThreshold: tinyint({ unsigned: true }).notNull(),
	icon1: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon2: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon3: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon4: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon5: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon6: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon7: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	icon8: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	groupType: tinyint({ unsigned: true }).notNull(),
	difficulty: tinyint({ unsigned: true }).default(0).notNull(),
	raidDifficulty: tinyint({ unsigned: true }).default(0).notNull(),
	masterLooterGuid: int({ unsigned: true }).notNull(),
},
(table) => [
	index("leaderGuid").on(table.leaderGuid),
]);

export const guild = mysqlTable("guild", {
	guildid: int({ unsigned: true }).default(0).primaryKey(),
	name: varchar({ length: 24 }).default("").notNull(),
	leaderguid: int({ unsigned: true }).default(0).notNull(),
	EmblemStyle: tinyint({ unsigned: true }).default(0).notNull(),
	EmblemColor: tinyint({ unsigned: true }).default(0).notNull(),
	BorderStyle: tinyint({ unsigned: true }).default(0).notNull(),
	BorderColor: tinyint({ unsigned: true }).default(0).notNull(),
	BackgroundColor: tinyint({ unsigned: true }).default(0).notNull(),
	info: varchar({ length: 500 }).default("").notNull(),
	motd: varchar({ length: 128 }).default("").notNull(),
	createdate: int({ unsigned: true }).default(0).notNull(),
	BankMoney: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
});

export const guild_bank_eventlog = mysqlTable("guild_bank_eventlog", {
	guildid: int({ unsigned: true }).default(0).notNull(),
	LogGuid: int({ unsigned: true }).default(0).notNull(),
	TabId: tinyint({ unsigned: true }).default(0).notNull(),
	EventType: tinyint({ unsigned: true }).default(0).notNull(),
	PlayerGuid: int({ unsigned: true }).default(0).notNull(),
	ItemOrMoney: int({ unsigned: true }).default(0).notNull(),
	ItemStackCount: smallint({ unsigned: true }).default(0).notNull(),
	DestTabId: tinyint({ unsigned: true }).default(0).notNull(),
	TimeStamp: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guildid, table.LogGuid, table.TabId] }),	index("Idx_LogGuid").on(table.LogGuid),
	index("Idx_PlayerGuid").on(table.PlayerGuid),
	index("guildid_key").on(table.guildid),
]);

export const guild_bank_item = mysqlTable("guild_bank_item", {
	guildid: int({ unsigned: true }).default(0).notNull(),
	TabId: tinyint({ unsigned: true }).default(0).notNull(),
	SlotId: tinyint({ unsigned: true }).default(0).notNull(),
	item_guid: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guildid, table.TabId, table.SlotId] }),	index("guildid_key").on(table.guildid),
	index("Idx_item_guid").on(table.item_guid),
]);

export const guild_bank_right = mysqlTable("guild_bank_right", {
	guildid: int({ unsigned: true }).default(0).notNull(),
	TabId: tinyint({ unsigned: true }).default(0).notNull(),
	rid: tinyint({ unsigned: true }).default(0).notNull(),
	gbright: tinyint({ unsigned: true }).default(0).notNull(),
	SlotPerDay: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guildid, table.TabId, table.rid] }),	index("guildid_key").on(table.guildid),
]);

export const guild_bank_tab = mysqlTable("guild_bank_tab", {
	guildid: int({ unsigned: true }).default(0).notNull(),
	TabId: tinyint({ unsigned: true }).default(0).notNull(),
	TabName: varchar({ length: 16 }).default("").notNull(),
	TabIcon: varchar({ length: 100 }).default("").notNull(),
	TabText: varchar({ length: 500 }),
},
(table) => [
	primaryKey({ columns: [table.guildid, table.TabId] }),	index("guildid_key").on(table.guildid),
]);

export const guild_eventlog = mysqlTable("guild_eventlog", {
	guildid: int({ unsigned: true }).notNull(),
	LogGuid: int({ unsigned: true }).notNull(),
	EventType: tinyint({ unsigned: true }).notNull(),
	PlayerGuid1: int({ unsigned: true }).notNull(),
	PlayerGuid2: int({ unsigned: true }).notNull(),
	NewRank: tinyint({ unsigned: true }).notNull(),
	TimeStamp: int({ unsigned: true }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guildid, table.LogGuid] }),	index("Idx_LogGuid").on(table.LogGuid),
	index("Idx_PlayerGuid1").on(table.PlayerGuid1),
	index("Idx_PlayerGuid2").on(table.PlayerGuid2),
]);

export const guild_member = mysqlTable("guild_member", {
	guildid: int({ unsigned: true }).notNull(),
	guid: int({ unsigned: true }).notNull(),
	rank: tinyint({ unsigned: true }).notNull(),
	pnote: varchar({ length: 31 }).default("").notNull(),
	offnote: varchar({ length: 31 }).default("").notNull(),
},
(table) => [
	uniqueIndex("guid_key").on(table.guid),
	index("guildid_key").on(table.guildid),
	index("guildid_rank_key").on(table.guildid, table.rank),
]);

export const guild_member_withdraw = mysqlTable("guild_member_withdraw", {
	guid: int({ unsigned: true }).primaryKey(),
	tab0: int({ unsigned: true }).default(0).notNull(),
	tab1: int({ unsigned: true }).default(0).notNull(),
	tab2: int({ unsigned: true }).default(0).notNull(),
	tab3: int({ unsigned: true }).default(0).notNull(),
	tab4: int({ unsigned: true }).default(0).notNull(),
	tab5: int({ unsigned: true }).default(0).notNull(),
	money: int({ unsigned: true }).default(0).notNull(),
});

export const guild_rank = mysqlTable("guild_rank", {
	guildid: int({ unsigned: true }).default(0).notNull(),
	rid: tinyint({ unsigned: true }).notNull(),
	rname: varchar({ length: 20 }).default("").notNull(),
	rights: int({ unsigned: true }).default(0),
	BankMoneyPerDay: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guildid, table.rid] }),	index("Idx_rid").on(table.rid),
]);

export const instance = mysqlTable("instance", {
	id: int({ unsigned: true }).default(0).primaryKey(),
	map: smallint({ unsigned: true }).default(0).notNull(),
	resettime: int({ unsigned: true }).default(0).notNull(),
	difficulty: tinyint({ unsigned: true }).default(0).notNull(),
	completedEncounters: int({ unsigned: true }).default(0).notNull(),
	data: tinytext().notNull(),
},
(table) => [
	index("resettime").on(table.resettime),
	index("difficulty").on(table.difficulty),
	index("map").on(table.map),
]);

export const instance_reset = mysqlTable("instance_reset", {
	mapid: smallint({ unsigned: true }).default(0).notNull(),
	difficulty: tinyint({ unsigned: true }).default(0).notNull(),
	resettime: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.mapid, table.difficulty] }),	index("difficulty").on(table.difficulty),
]);

export const instance_saved_go_state_data = mysqlTable("instance_saved_go_state_data", {
	id: int({ unsigned: true }).notNull(),
	guid: int({ unsigned: true }).notNull(),
	state: tinyint({ unsigned: true }).default(0),
},
(table) => [
	primaryKey({ columns: [table.id, table.guid] }),]);

export const item_instance = mysqlTable("item_instance", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	itemEntry: int({ unsigned: true }).default(0),
	owner_guid: int({ unsigned: true }).default(0).notNull(),
	creatorGuid: int({ unsigned: true }).default(0).notNull(),
	giftCreatorGuid: int({ unsigned: true }).default(0).notNull(),
	count: int({ unsigned: true }).default(1).notNull(),
	duration: int().default(0).notNull(),
	charges: tinytext(),
	flags: int({ unsigned: true }).default(0),
	enchantments: text().notNull(),
	randomPropertyId: smallint().default(0).notNull(),
	durability: smallint({ unsigned: true }).default(0).notNull(),
	playedTime: int({ unsigned: true }).default(0).notNull(),
	text: text(),
},
(table) => [
	index("idx_owner_guid").on(table.owner_guid),
]);

export const item_loot_storage = mysqlTable("item_loot_storage", {
	containerGUID: int({ unsigned: true }).notNull(),
	itemid: int({ unsigned: true }).notNull(),
	count: int({ unsigned: true }).notNull(),
	item_index: int({ unsigned: true }).default(0).notNull(),
	randomPropertyId: int().notNull(),
	randomSuffix: int({ unsigned: true }).notNull(),
	follow_loot_rules: tinyint({ unsigned: true }).notNull(),
	freeforall: tinyint({ unsigned: true }).notNull(),
	is_blocked: tinyint({ unsigned: true }).notNull(),
	is_counted: tinyint({ unsigned: true }).notNull(),
	is_underthreshold: tinyint({ unsigned: true }).notNull(),
	needs_quest: tinyint({ unsigned: true }).notNull(),
	conditionLootId: int().default(0).notNull(),
});

export const item_refund_instance = mysqlTable("item_refund_instance", {
	item_guid: int({ unsigned: true }).notNull(),
	player_guid: int({ unsigned: true }).notNull(),
	paidMoney: int({ unsigned: true }).default(0).notNull(),
	paidExtendedCost: smallint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.item_guid, table.player_guid] }),]);

export const item_soulbound_trade_data = mysqlTable("item_soulbound_trade_data", {
	itemGuid: int({ unsigned: true }).primaryKey(),
	allowedPlayers: text().notNull(),
});

export const lag_reports = mysqlTable("lag_reports", {
	reportId: int({ unsigned: true }).autoincrement().primaryKey(),
	guid: int({ unsigned: true }).default(0).notNull(),
	lagType: tinyint({ unsigned: true }).default(0).notNull(),
	mapId: smallint({ unsigned: true }).default(0).notNull(),
	posX: float().default(0).notNull(),
	posY: float().default(0).notNull(),
	posZ: float().default(0).notNull(),
	latency: int({ unsigned: true }).default(0).notNull(),
	createTime: int({ unsigned: true }).default(0).notNull(),
});

export const lfg_data = mysqlTable("lfg_data", {
	guid: int({ unsigned: true }).default(0).primaryKey(),
	dungeon: int({ unsigned: true }).default(0).notNull(),
	state: tinyint({ unsigned: true }).default(0).notNull(),
});

export const log_arena_fights = mysqlTable("log_arena_fights", {
	fight_id: int({ unsigned: true }).primaryKey(),
	time: datetime().notNull(),
	type: tinyint({ unsigned: true }).notNull(),
	duration: int({ unsigned: true }).notNull(),
	winner: int({ unsigned: true }).notNull(),
	loser: int({ unsigned: true }).notNull(),
	winner_tr: smallint({ unsigned: true }).notNull(),
	winner_mmr: smallint({ unsigned: true }).notNull(),
	winner_tr_change: smallint().notNull(),
	loser_tr: smallint({ unsigned: true }).notNull(),
	loser_mmr: smallint({ unsigned: true }).notNull(),
	loser_tr_change: smallint().notNull(),
	currOnline: int({ unsigned: true }).notNull(),
});

export const log_arena_memberstats = mysqlTable("log_arena_memberstats", {
	fight_id: int({ unsigned: true }).notNull(),
	member_id: tinyint({ unsigned: true }).notNull(),
	name: char({ length: 20 }).notNull(),
	guid: int({ unsigned: true }).notNull(),
	team: int({ unsigned: true }).notNull(),
	account: int({ unsigned: true }).notNull(),
	ip: char({ length: 15 }).notNull(),
	damage: int({ unsigned: true }).notNull(),
	heal: int({ unsigned: true }).notNull(),
	kblows: int({ unsigned: true }).notNull(),
},
(table) => [
	primaryKey({ columns: [table.fight_id, table.member_id] }),]);

export const log_encounter = mysqlTable("log_encounter", {
	time: datetime().notNull(),
	map: smallint({ unsigned: true }).notNull(),
	difficulty: tinyint({ unsigned: true }).notNull(),
	creditType: tinyint({ unsigned: true }).notNull(),
	creditEntry: int({ unsigned: true }).notNull(),
	playersInfo: text().notNull(),
});

export const log_money = mysqlTable("log_money", {
	sender_acc: int({ unsigned: true }).notNull(),
	sender_guid: int({ unsigned: true }).notNull(),
	sender_name: text().notNull(),
	sender_ip: text().notNull(),
	receiver_acc: int({ unsigned: true }).notNull(),
	receiver_name: text().notNull(),
	money: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	topic: text().notNull(),
	date: datetime().notNull(),
	type: tinyint().notNull(),
});

export const mail = mysqlTable("mail", {
	id: int({ unsigned: true }).default(0).primaryKey(),
	messageType: tinyint({ unsigned: true }).default(0).notNull(),
	stationery: tinyint().default(41).notNull(),
	mailTemplateId: smallint({ unsigned: true }).default(0).notNull(),
	sender: int({ unsigned: true }).default(0).notNull(),
	receiver: int({ unsigned: true }).default(0).notNull(),
	subject: longtext(),
	body: longtext(),
	has_items: tinyint({ unsigned: true }).default(0).notNull(),
	expire_time: int({ unsigned: true }).default(0).notNull(),
	deliver_time: int({ unsigned: true }).default(0).notNull(),
	money: int({ unsigned: true }).default(0).notNull(),
	cod: int({ unsigned: true }).default(0).notNull(),
	checked: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	index("idx_receiver").on(table.receiver),
]);

export const mail_items = mysqlTable("mail_items", {
	mail_id: int({ unsigned: true }).default(0).notNull(),
	item_guid: int({ unsigned: true }).default(0).primaryKey(),
	receiver: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	index("idx_mail_id").on(table.mail_id),
	index("idx_receiver").on(table.receiver),
]);

export const mail_server_character = mysqlTable("mail_server_character", {
	guid: int({ unsigned: true }).notNull(),
	mailId: int({ unsigned: true }).notNull().references(() => mail_server_template.id, { onDelete: "cascade" } ),
},
(table) => [
	primaryKey({ columns: [table.guid, table.mailId] }),]);

export const mail_server_template_conditions = mysqlTable("mail_server_template_conditions", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	templateID: int({ unsigned: true }).notNull().references(() => mail_server_template.id, { onDelete: "cascade" } ),
	conditionType: mysqlEnum(["Level","PlayTime","Quest","Achievement","Reputation","Faction","Race","Class","AccountFlags"]).notNull(),
	conditionValue: int({ unsigned: true }).notNull(),
	conditionState: int({ unsigned: true }).default(0).notNull(),
});

export const mail_server_template_items = mysqlTable("mail_server_template_items", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	templateID: int({ unsigned: true }).notNull().references(() => mail_server_template.id, { onDelete: "cascade" } ),
	faction: mysqlEnum(["Alliance","Horde"]).notNull(),
	item: int({ unsigned: true }).notNull(),
	itemCount: int({ unsigned: true }).notNull(),
});

export const pet_aura = mysqlTable("pet_aura", {
	guid: int({ unsigned: true }).default(0).notNull(),
	casterGuid: bigint({ unsigned: true, mode: 'bigint' }).default(0n).notNull(),
	spell: int({ unsigned: true }).default(0).notNull(),
	effectMask: tinyint({ unsigned: true }).default(0).notNull(),
	recalculateMask: tinyint({ unsigned: true }).default(0).notNull(),
	stackCount: tinyint({ unsigned: true }).default(1).notNull(),
	amount0: int(),
	amount1: int(),
	amount2: int(),
	base_amount0: int(),
	base_amount1: int(),
	base_amount2: int(),
	maxDuration: int().default(0).notNull(),
	remainTime: int().default(0).notNull(),
	remainCharges: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.casterGuid, table.spell, table.effectMask] }),]);

export const pet_spell = mysqlTable("pet_spell", {
	guid: int({ unsigned: true }).default(0).notNull(),
	spell: int({ unsigned: true }).default(0).notNull(),
	active: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.spell] }),]);

export const pet_spell_cooldown = mysqlTable("pet_spell_cooldown", {
	guid: int({ unsigned: true }).default(0).notNull(),
	spell: int({ unsigned: true }).default(0).notNull(),
	category: int({ unsigned: true }).default(0),
	time: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.guid, table.spell] }),]);

export const petition = mysqlTable("petition", {
	ownerguid: int({ unsigned: true }).notNull(),
	petitionguid: int({ unsigned: true }).default(0),
	petition_id: int({ unsigned: true }).default(0).notNull(),
	name: varchar({ length: 24 }).notNull(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.ownerguid, table.type] }),	index("idx_petition_id").on(table.petition_id),
	uniqueIndex("index_ownerguid_petitionguid").on(table.ownerguid, table.petitionguid),
]);

export const pool_quest_save = mysqlTable("pool_quest_save", {
	pool_id: int({ unsigned: true }).default(0).notNull(),
	quest_id: int({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.pool_id, table.quest_id] }),]);

export const profanity_name = mysqlTable("profanity_name", {
	name: varchar({ length: 12 }).charSet("utf8mb4").collate("utf8mb4_bin").primaryKey(),
});

export const pvpstats_battlegrounds = mysqlTable("pvpstats_battlegrounds", {
	id: bigint({ unsigned: true, mode: 'bigint' }).autoincrement().primaryKey(),
	winner_faction: tinyint().notNull(),
	bracket_id: tinyint({ unsigned: true }).notNull(),
	type: tinyint({ unsigned: true }).notNull(),
	date: datetime().notNull(),
});

export const pvpstats_players = mysqlTable("pvpstats_players", {
	battleground_id: bigint({ unsigned: true, mode: 'bigint' }).notNull(),
	character_guid: int({ unsigned: true }).notNull(),
	winner: customType({ dataType: () => 'bit(1)' })().notNull(),
	score_killing_blows: int({ unsigned: true }),
	score_deaths: int({ unsigned: true }),
	score_honorable_kills: int({ unsigned: true }),
	score_bonus_honor: int({ unsigned: true }),
	score_damage_done: int({ unsigned: true }),
	score_healing_done: int({ unsigned: true }),
	attr_1: int({ unsigned: true }).default(0),
	attr_2: int({ unsigned: true }).default(0),
	attr_3: int({ unsigned: true }).default(0),
	attr_4: int({ unsigned: true }).default(0),
	attr_5: int({ unsigned: true }).default(0),
},
(table) => [
	primaryKey({ columns: [table.battleground_id, table.character_guid] }),]);

export const quest_tracker = mysqlTable("quest_tracker", {
	id: int({ unsigned: true }).default(0).notNull(),
	character_guid: int({ unsigned: true }).default(0).notNull(),
	quest_accept_time: datetime().notNull(),
	quest_complete_time: datetime(),
	quest_abandon_time: datetime(),
	completed_by_gm: tinyint().default(0).notNull(),
	core_hash: varchar({ length: 120 }).default("0").notNull(),
	core_revision: varchar({ length: 120 }).default("0").notNull(),
},
(table) => [
	uniqueIndex("idx_latest_quest_for_character").on(table.id, table.character_guid, table.quest_accept_time),
]);

export const recovery_item = mysqlTable("recovery_item", {
	Id: int({ unsigned: true }).autoincrement().primaryKey(),
	Guid: int({ unsigned: true }).default(0).notNull(),
	ItemEntry: int({ unsigned: true }).default(0),
	Count: int({ unsigned: true }).default(0).notNull(),
	DeleteDate: int({ unsigned: true }),
},
(table) => [
	index("idx_guid").on(table.Guid),
]);

export const reserved_name = mysqlTable("reserved_name", {
	name: varchar({ length: 12 }).charSet("utf8mb4").collate("utf8mb4_bin").primaryKey(),
});

export const spam_reports = mysqlTable("spam_reports", {
	ID: int({ unsigned: true }).autoincrement().primaryKey(),
	SpamType: tinyint({ unsigned: true }).notNull(),
	SpammerGuid: int({ unsigned: true }).default(0).notNull(),
	Unk1: int({ unsigned: true }).default(0),
	MailIdOrMessageType: int({ unsigned: true }).default(0),
	ChannelId: int({ unsigned: true }),
	SecondsSinceMessage: int({ unsigned: true }),
	Description: longtext(),
	Time: int(),
});

export const updates = mysqlTable("updates", {
	name: varchar({ length: 200 }).primaryKey(),
	hash: char({ length: 40 }).default(""),
	state: mysqlEnum(["RELEASED","CUSTOM","MODULE","ARCHIVED","PENDING"]).default("RELEASED").notNull(),
	timestamp: timestamp().defaultNow().notNull(),
	speed: int({ unsigned: true }).default(0).notNull(),
});

export const mail_server_template = mysqlTable("mail_server_template", {
	id: int({ unsigned: true }).autoincrement().primaryKey(),
	senderEntry: int({ unsigned: true }).default(0).notNull(),
	moneyA: int({ unsigned: true }).default(0).notNull(),
	moneyH: int({ unsigned: true }).default(0).notNull(),
	subject: text().notNull(),
	body: text().notNull(),
	active: tinyint({ unsigned: true }).default(1).notNull(),
});

export const petition_sign = mysqlTable("petition_sign", {
	ownerguid: int({ unsigned: true }).notNull(),
	petitionguid: int({ unsigned: true }).default(0).notNull(),
	petition_id: int({ unsigned: true }).default(0).notNull(),
	playerguid: int({ unsigned: true }).default(0).notNull(),
	player_account: int({ unsigned: true }).default(0).notNull(),
	type: tinyint({ unsigned: true }).default(0).notNull(),
},
(table) => [
	primaryKey({ columns: [table.petition_id, table.playerguid] }),	index("Idx_ownerguid").on(table.ownerguid),
	index("Idx_playerguid").on(table.playerguid),
]);

export const updates_include = mysqlTable("updates_include", {
	path: varchar({ length: 200 }).primaryKey(),
	state: mysqlEnum(["RELEASED","ARCHIVED","CUSTOM","PENDING"]).default("RELEASED").notNull(),
});

export const warden_action = mysqlTable("warden_action", {
	wardenId: smallint({ unsigned: true }).primaryKey(),
	action: tinyint({ unsigned: true }),
});

export const world_state = mysqlTable("world_state", {
	Id: int({ unsigned: true }).primaryKey(),
	Data: longtext().charSet("utf8mb4").collate("utf8mb4_0900_ai_ci"),
});

export const worldstates = mysqlTable("worldstates", {
	entry: int({ unsigned: true }).default(0).primaryKey(),
	value: int({ unsigned: true }).default(0).notNull(),
	comment: tinytext(),
});
