/** Generated from AzerothCore `SharedDefines.h` and `SpellAuraDefines.h` (3.3.5a). */

// SpellEffects
export const SPELL_EFFECT_INSTAKILL = 1;
export const SPELL_EFFECT_SCHOOL_DAMAGE = 2;
export const SPELL_EFFECT_DUMMY = 3;
export const SPELL_EFFECT_PORTAL_TELEPORT = 4;
export const SPELL_EFFECT_TELEPORT_UNITS = 5;
export const SPELL_EFFECT_APPLY_AURA = 6;
export const SPELL_EFFECT_ENVIRONMENTAL_DAMAGE = 7;
export const SPELL_EFFECT_POWER_DRAIN = 8;
export const SPELL_EFFECT_HEALTH_LEECH = 9;
export const SPELL_EFFECT_HEAL = 10;
export const SPELL_EFFECT_BIND = 11;
export const SPELL_EFFECT_PORTAL = 12;
export const SPELL_EFFECT_RITUAL_BASE = 13;
export const SPELL_EFFECT_RITUAL_SPECIALIZE = 14;
export const SPELL_EFFECT_RITUAL_ACTIVATE_PORTAL = 15;
export const SPELL_EFFECT_QUEST_COMPLETE = 16;
export const SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL = 17;
export const SPELL_EFFECT_RESURRECT = 18;
export const SPELL_EFFECT_ADD_EXTRA_ATTACKS = 19;
export const SPELL_EFFECT_DODGE = 20;
export const SPELL_EFFECT_EVADE = 21;
export const SPELL_EFFECT_PARRY = 22;
export const SPELL_EFFECT_BLOCK = 23;
export const SPELL_EFFECT_CREATE_ITEM = 24;
export const SPELL_EFFECT_WEAPON = 25;
export const SPELL_EFFECT_DEFENSE = 26;
export const SPELL_EFFECT_PERSISTENT_AREA_AURA = 27;
export const SPELL_EFFECT_SUMMON = 28;
export const SPELL_EFFECT_LEAP = 29;
export const SPELL_EFFECT_ENERGIZE = 30;
export const SPELL_EFFECT_WEAPON_PERCENT_DAMAGE = 31;
export const SPELL_EFFECT_TRIGGER_MISSILE = 32;
export const SPELL_EFFECT_OPEN_LOCK = 33;
export const SPELL_EFFECT_SUMMON_CHANGE_ITEM = 34;
export const SPELL_EFFECT_APPLY_AREA_AURA_PARTY = 35;
export const SPELL_EFFECT_LEARN_SPELL = 36;
export const SPELL_EFFECT_SPELL_DEFENSE = 37;
export const SPELL_EFFECT_DISPEL = 38;
export const SPELL_EFFECT_LANGUAGE = 39;
export const SPELL_EFFECT_DUAL_WIELD = 40;
export const SPELL_EFFECT_JUMP = 41;
export const SPELL_EFFECT_JUMP_DEST = 42;
export const SPELL_EFFECT_TELEPORT_UNITS_FACE_CASTER = 43;
export const SPELL_EFFECT_SKILL_STEP = 44;
export const SPELL_EFFECT_ADD_HONOR = 45;
export const SPELL_EFFECT_SPAWN = 46;
export const SPELL_EFFECT_TRADE_SKILL = 47;
export const SPELL_EFFECT_STEALTH = 48;
export const SPELL_EFFECT_DETECT = 49;
export const SPELL_EFFECT_TRANS_DOOR = 50;
export const SPELL_EFFECT_FORCE_CRITICAL_HIT = 51;
export const SPELL_EFFECT_GUARANTEE_HIT = 52;
export const SPELL_EFFECT_ENCHANT_ITEM = 53;
export const SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY = 54;
export const SPELL_EFFECT_TAMECREATURE = 55;
export const SPELL_EFFECT_SUMMON_PET = 56;
export const SPELL_EFFECT_LEARN_PET_SPELL = 57;
export const SPELL_EFFECT_WEAPON_DAMAGE = 58;
export const SPELL_EFFECT_CREATE_RANDOM_ITEM = 59;
export const SPELL_EFFECT_PROFICIENCY = 60;
export const SPELL_EFFECT_SEND_EVENT = 61;
export const SPELL_EFFECT_POWER_BURN = 62;
export const SPELL_EFFECT_THREAT = 63;
export const SPELL_EFFECT_TRIGGER_SPELL = 64;
export const SPELL_EFFECT_APPLY_AREA_AURA_RAID = 65;
export const SPELL_EFFECT_CREATE_MANA_GEM = 66;
export const SPELL_EFFECT_HEAL_MAX_HEALTH = 67;
export const SPELL_EFFECT_INTERRUPT_CAST = 68;
export const SPELL_EFFECT_DISTRACT = 69;
export const SPELL_EFFECT_PULL = 70;
export const SPELL_EFFECT_PICKPOCKET = 71;
export const SPELL_EFFECT_ADD_FARSIGHT = 72;
export const SPELL_EFFECT_UNTRAIN_TALENTS = 73;
export const SPELL_EFFECT_APPLY_GLYPH = 74;
export const SPELL_EFFECT_HEAL_MECHANICAL = 75;
export const SPELL_EFFECT_SUMMON_OBJECT_WILD = 76;
export const SPELL_EFFECT_SCRIPT_EFFECT = 77;
export const SPELL_EFFECT_ATTACK = 78;
export const SPELL_EFFECT_SANCTUARY = 79;
export const SPELL_EFFECT_ADD_COMBO_POINTS = 80;
export const SPELL_EFFECT_CREATE_HOUSE = 81;
export const SPELL_EFFECT_BIND_SIGHT = 82;
export const SPELL_EFFECT_DUEL = 83;
export const SPELL_EFFECT_STUCK = 84;
export const SPELL_EFFECT_SUMMON_PLAYER = 85;
export const SPELL_EFFECT_ACTIVATE_OBJECT = 86;
export const SPELL_EFFECT_GAMEOBJECT_DAMAGE = 87;
export const SPELL_EFFECT_GAMEOBJECT_REPAIR = 88;
export const SPELL_EFFECT_GAMEOBJECT_SET_DESTRUCTION_STATE = 89;
export const SPELL_EFFECT_KILL_CREDIT = 90;
export const SPELL_EFFECT_THREAT_ALL = 91;
export const SPELL_EFFECT_ENCHANT_HELD_ITEM = 92;
export const SPELL_EFFECT_FORCE_DESELECT = 93;
export const SPELL_EFFECT_SELF_RESURRECT = 94;
export const SPELL_EFFECT_SKINNING = 95;
export const SPELL_EFFECT_CHARGE = 96;
export const SPELL_EFFECT_CAST_BUTTON = 97;
export const SPELL_EFFECT_KNOCK_BACK = 98;
export const SPELL_EFFECT_DISENCHANT = 99;
export const SPELL_EFFECT_INEBRIATE = 100;
export const SPELL_EFFECT_FEED_PET = 101;
export const SPELL_EFFECT_DISMISS_PET = 102;
export const SPELL_EFFECT_REPUTATION = 103;
export const SPELL_EFFECT_SUMMON_OBJECT_SLOT1 = 104;
export const SPELL_EFFECT_SUMMON_OBJECT_SLOT2 = 105;
export const SPELL_EFFECT_SUMMON_OBJECT_SLOT3 = 106;
export const SPELL_EFFECT_SUMMON_OBJECT_SLOT4 = 107;
export const SPELL_EFFECT_DISPEL_MECHANIC = 108;
export const SPELL_EFFECT_RESURRECT_PET = 109;
export const SPELL_EFFECT_DESTROY_ALL_TOTEMS = 110;
export const SPELL_EFFECT_DURABILITY_DAMAGE = 111;
export const SPELL_EFFECT_112 = 112;
export const SPELL_EFFECT_RESURRECT_NEW = 113;
export const SPELL_EFFECT_ATTACK_ME = 114;
export const SPELL_EFFECT_DURABILITY_DAMAGE_PCT = 115;
export const SPELL_EFFECT_SKIN_PLAYER_CORPSE = 116;
export const SPELL_EFFECT_SPIRIT_HEAL = 117;
export const SPELL_EFFECT_SKILL = 118;
export const SPELL_EFFECT_APPLY_AREA_AURA_PET = 119;
export const SPELL_EFFECT_TELEPORT_GRAVEYARD = 120;
export const SPELL_EFFECT_NORMALIZED_WEAPON_DMG = 121;
export const SPELL_EFFECT_122 = 122;
export const SPELL_EFFECT_SEND_TAXI = 123;
export const SPELL_EFFECT_PULL_TOWARDS = 124;
export const SPELL_EFFECT_MODIFY_THREAT_PERCENT = 125;
export const SPELL_EFFECT_STEAL_BENEFICIAL_BUFF = 126;
export const SPELL_EFFECT_PROSPECTING = 127;
export const SPELL_EFFECT_APPLY_AREA_AURA_FRIEND = 128;
export const SPELL_EFFECT_APPLY_AREA_AURA_ENEMY = 129;
export const SPELL_EFFECT_REDIRECT_THREAT = 130;
export const SPELL_EFFECT_PLAY_SOUND = 131;
export const SPELL_EFFECT_PLAY_MUSIC = 132;
export const SPELL_EFFECT_UNLEARN_SPECIALIZATION = 133;
export const SPELL_EFFECT_KILL_CREDIT2 = 134;
export const SPELL_EFFECT_CALL_PET = 135;
export const SPELL_EFFECT_HEAL_PCT = 136;
export const SPELL_EFFECT_ENERGIZE_PCT = 137;
export const SPELL_EFFECT_LEAP_BACK = 138;
export const SPELL_EFFECT_CLEAR_QUEST = 139;
export const SPELL_EFFECT_FORCE_CAST = 140;
export const SPELL_EFFECT_FORCE_CAST_WITH_VALUE = 141;
export const SPELL_EFFECT_TRIGGER_SPELL_WITH_VALUE = 142;
export const SPELL_EFFECT_APPLY_AREA_AURA_OWNER = 143;
export const SPELL_EFFECT_KNOCK_BACK_DEST = 144;
export const SPELL_EFFECT_PULL_TOWARDS_DEST = 145;
export const SPELL_EFFECT_ACTIVATE_RUNE = 146;
export const SPELL_EFFECT_QUEST_FAIL = 147;
export const SPELL_EFFECT_TRIGGER_MISSILE_SPELL_WITH_VALUE = 148;
export const SPELL_EFFECT_CHARGE_DEST = 149;
export const SPELL_EFFECT_QUEST_START = 150;
export const SPELL_EFFECT_TRIGGER_SPELL_2 = 151;
export const SPELL_EFFECT_SUMMON_RAF_FRIEND = 152;
export const SPELL_EFFECT_CREATE_TAMED_PET = 153;
export const SPELL_EFFECT_DISCOVER_TAXI = 154;
export const SPELL_EFFECT_TITAN_GRIP = 155;
export const SPELL_EFFECT_ENCHANT_ITEM_PRISMATIC = 156;
export const SPELL_EFFECT_CREATE_ITEM_2 = 157;
export const SPELL_EFFECT_MILLING = 158;
export const SPELL_EFFECT_ALLOW_RENAME_PET = 159;
export const SPELL_EFFECT_FORCE_CAST_2 = 160;
export const SPELL_EFFECT_TALENT_SPEC_COUNT = 161;
export const SPELL_EFFECT_TALENT_SPEC_SELECT = 162;
export const SPELL_EFFECT_163 = 163;
export const SPELL_EFFECT_REMOVE_AURA = 164;
export const TOTAL_SPELL_EFFECTS = 165;
export const SPELL_EFFECT_NAMES: ReadonlyMap<number, string> = new Map([
  [1, "SPELL_EFFECT_INSTAKILL"],
  [2, "SPELL_EFFECT_SCHOOL_DAMAGE"],
  [3, "SPELL_EFFECT_DUMMY"],
  [4, "SPELL_EFFECT_PORTAL_TELEPORT"],
  [5, "SPELL_EFFECT_TELEPORT_UNITS"],
  [6, "SPELL_EFFECT_APPLY_AURA"],
  [7, "SPELL_EFFECT_ENVIRONMENTAL_DAMAGE"],
  [8, "SPELL_EFFECT_POWER_DRAIN"],
  [9, "SPELL_EFFECT_HEALTH_LEECH"],
  [10, "SPELL_EFFECT_HEAL"],
  [11, "SPELL_EFFECT_BIND"],
  [12, "SPELL_EFFECT_PORTAL"],
  [13, "SPELL_EFFECT_RITUAL_BASE"],
  [14, "SPELL_EFFECT_RITUAL_SPECIALIZE"],
  [15, "SPELL_EFFECT_RITUAL_ACTIVATE_PORTAL"],
  [16, "SPELL_EFFECT_QUEST_COMPLETE"],
  [17, "SPELL_EFFECT_WEAPON_DAMAGE_NOSCHOOL"],
  [18, "SPELL_EFFECT_RESURRECT"],
  [19, "SPELL_EFFECT_ADD_EXTRA_ATTACKS"],
  [20, "SPELL_EFFECT_DODGE"],
  [21, "SPELL_EFFECT_EVADE"],
  [22, "SPELL_EFFECT_PARRY"],
  [23, "SPELL_EFFECT_BLOCK"],
  [24, "SPELL_EFFECT_CREATE_ITEM"],
  [25, "SPELL_EFFECT_WEAPON"],
  [26, "SPELL_EFFECT_DEFENSE"],
  [27, "SPELL_EFFECT_PERSISTENT_AREA_AURA"],
  [28, "SPELL_EFFECT_SUMMON"],
  [29, "SPELL_EFFECT_LEAP"],
  [30, "SPELL_EFFECT_ENERGIZE"],
  [31, "SPELL_EFFECT_WEAPON_PERCENT_DAMAGE"],
  [32, "SPELL_EFFECT_TRIGGER_MISSILE"],
  [33, "SPELL_EFFECT_OPEN_LOCK"],
  [34, "SPELL_EFFECT_SUMMON_CHANGE_ITEM"],
  [35, "SPELL_EFFECT_APPLY_AREA_AURA_PARTY"],
  [36, "SPELL_EFFECT_LEARN_SPELL"],
  [37, "SPELL_EFFECT_SPELL_DEFENSE"],
  [38, "SPELL_EFFECT_DISPEL"],
  [39, "SPELL_EFFECT_LANGUAGE"],
  [40, "SPELL_EFFECT_DUAL_WIELD"],
  [41, "SPELL_EFFECT_JUMP"],
  [42, "SPELL_EFFECT_JUMP_DEST"],
  [43, "SPELL_EFFECT_TELEPORT_UNITS_FACE_CASTER"],
  [44, "SPELL_EFFECT_SKILL_STEP"],
  [45, "SPELL_EFFECT_ADD_HONOR"],
  [46, "SPELL_EFFECT_SPAWN"],
  [47, "SPELL_EFFECT_TRADE_SKILL"],
  [48, "SPELL_EFFECT_STEALTH"],
  [49, "SPELL_EFFECT_DETECT"],
  [50, "SPELL_EFFECT_TRANS_DOOR"],
  [51, "SPELL_EFFECT_FORCE_CRITICAL_HIT"],
  [52, "SPELL_EFFECT_GUARANTEE_HIT"],
  [53, "SPELL_EFFECT_ENCHANT_ITEM"],
  [54, "SPELL_EFFECT_ENCHANT_ITEM_TEMPORARY"],
  [55, "SPELL_EFFECT_TAMECREATURE"],
  [56, "SPELL_EFFECT_SUMMON_PET"],
  [57, "SPELL_EFFECT_LEARN_PET_SPELL"],
  [58, "SPELL_EFFECT_WEAPON_DAMAGE"],
  [59, "SPELL_EFFECT_CREATE_RANDOM_ITEM"],
  [60, "SPELL_EFFECT_PROFICIENCY"],
  [61, "SPELL_EFFECT_SEND_EVENT"],
  [62, "SPELL_EFFECT_POWER_BURN"],
  [63, "SPELL_EFFECT_THREAT"],
  [64, "SPELL_EFFECT_TRIGGER_SPELL"],
  [65, "SPELL_EFFECT_APPLY_AREA_AURA_RAID"],
  [66, "SPELL_EFFECT_CREATE_MANA_GEM"],
  [67, "SPELL_EFFECT_HEAL_MAX_HEALTH"],
  [68, "SPELL_EFFECT_INTERRUPT_CAST"],
  [69, "SPELL_EFFECT_DISTRACT"],
  [70, "SPELL_EFFECT_PULL"],
  [71, "SPELL_EFFECT_PICKPOCKET"],
  [72, "SPELL_EFFECT_ADD_FARSIGHT"],
  [73, "SPELL_EFFECT_UNTRAIN_TALENTS"],
  [74, "SPELL_EFFECT_APPLY_GLYPH"],
  [75, "SPELL_EFFECT_HEAL_MECHANICAL"],
  [76, "SPELL_EFFECT_SUMMON_OBJECT_WILD"],
  [77, "SPELL_EFFECT_SCRIPT_EFFECT"],
  [78, "SPELL_EFFECT_ATTACK"],
  [79, "SPELL_EFFECT_SANCTUARY"],
  [80, "SPELL_EFFECT_ADD_COMBO_POINTS"],
  [81, "SPELL_EFFECT_CREATE_HOUSE"],
  [82, "SPELL_EFFECT_BIND_SIGHT"],
  [83, "SPELL_EFFECT_DUEL"],
  [84, "SPELL_EFFECT_STUCK"],
  [85, "SPELL_EFFECT_SUMMON_PLAYER"],
  [86, "SPELL_EFFECT_ACTIVATE_OBJECT"],
  [87, "SPELL_EFFECT_GAMEOBJECT_DAMAGE"],
  [88, "SPELL_EFFECT_GAMEOBJECT_REPAIR"],
  [89, "SPELL_EFFECT_GAMEOBJECT_SET_DESTRUCTION_STATE"],
  [90, "SPELL_EFFECT_KILL_CREDIT"],
  [91, "SPELL_EFFECT_THREAT_ALL"],
  [92, "SPELL_EFFECT_ENCHANT_HELD_ITEM"],
  [93, "SPELL_EFFECT_FORCE_DESELECT"],
  [94, "SPELL_EFFECT_SELF_RESURRECT"],
  [95, "SPELL_EFFECT_SKINNING"],
  [96, "SPELL_EFFECT_CHARGE"],
  [97, "SPELL_EFFECT_CAST_BUTTON"],
  [98, "SPELL_EFFECT_KNOCK_BACK"],
  [99, "SPELL_EFFECT_DISENCHANT"],
  [100, "SPELL_EFFECT_INEBRIATE"],
  [101, "SPELL_EFFECT_FEED_PET"],
  [102, "SPELL_EFFECT_DISMISS_PET"],
  [103, "SPELL_EFFECT_REPUTATION"],
  [104, "SPELL_EFFECT_SUMMON_OBJECT_SLOT1"],
  [105, "SPELL_EFFECT_SUMMON_OBJECT_SLOT2"],
  [106, "SPELL_EFFECT_SUMMON_OBJECT_SLOT3"],
  [107, "SPELL_EFFECT_SUMMON_OBJECT_SLOT4"],
  [108, "SPELL_EFFECT_DISPEL_MECHANIC"],
  [109, "SPELL_EFFECT_RESURRECT_PET"],
  [110, "SPELL_EFFECT_DESTROY_ALL_TOTEMS"],
  [111, "SPELL_EFFECT_DURABILITY_DAMAGE"],
  [112, "SPELL_EFFECT_112"],
  [113, "SPELL_EFFECT_RESURRECT_NEW"],
  [114, "SPELL_EFFECT_ATTACK_ME"],
  [115, "SPELL_EFFECT_DURABILITY_DAMAGE_PCT"],
  [116, "SPELL_EFFECT_SKIN_PLAYER_CORPSE"],
  [117, "SPELL_EFFECT_SPIRIT_HEAL"],
  [118, "SPELL_EFFECT_SKILL"],
  [119, "SPELL_EFFECT_APPLY_AREA_AURA_PET"],
  [120, "SPELL_EFFECT_TELEPORT_GRAVEYARD"],
  [121, "SPELL_EFFECT_NORMALIZED_WEAPON_DMG"],
  [122, "SPELL_EFFECT_122"],
  [123, "SPELL_EFFECT_SEND_TAXI"],
  [124, "SPELL_EFFECT_PULL_TOWARDS"],
  [125, "SPELL_EFFECT_MODIFY_THREAT_PERCENT"],
  [126, "SPELL_EFFECT_STEAL_BENEFICIAL_BUFF"],
  [127, "SPELL_EFFECT_PROSPECTING"],
  [128, "SPELL_EFFECT_APPLY_AREA_AURA_FRIEND"],
  [129, "SPELL_EFFECT_APPLY_AREA_AURA_ENEMY"],
  [130, "SPELL_EFFECT_REDIRECT_THREAT"],
  [131, "SPELL_EFFECT_PLAY_SOUND"],
  [132, "SPELL_EFFECT_PLAY_MUSIC"],
  [133, "SPELL_EFFECT_UNLEARN_SPECIALIZATION"],
  [134, "SPELL_EFFECT_KILL_CREDIT2"],
  [135, "SPELL_EFFECT_CALL_PET"],
  [136, "SPELL_EFFECT_HEAL_PCT"],
  [137, "SPELL_EFFECT_ENERGIZE_PCT"],
  [138, "SPELL_EFFECT_LEAP_BACK"],
  [139, "SPELL_EFFECT_CLEAR_QUEST"],
  [140, "SPELL_EFFECT_FORCE_CAST"],
  [141, "SPELL_EFFECT_FORCE_CAST_WITH_VALUE"],
  [142, "SPELL_EFFECT_TRIGGER_SPELL_WITH_VALUE"],
  [143, "SPELL_EFFECT_APPLY_AREA_AURA_OWNER"],
  [144, "SPELL_EFFECT_KNOCK_BACK_DEST"],
  [145, "SPELL_EFFECT_PULL_TOWARDS_DEST"],
  [146, "SPELL_EFFECT_ACTIVATE_RUNE"],
  [147, "SPELL_EFFECT_QUEST_FAIL"],
  [148, "SPELL_EFFECT_TRIGGER_MISSILE_SPELL_WITH_VALUE"],
  [149, "SPELL_EFFECT_CHARGE_DEST"],
  [150, "SPELL_EFFECT_QUEST_START"],
  [151, "SPELL_EFFECT_TRIGGER_SPELL_2"],
  [152, "SPELL_EFFECT_SUMMON_RAF_FRIEND"],
  [153, "SPELL_EFFECT_CREATE_TAMED_PET"],
  [154, "SPELL_EFFECT_DISCOVER_TAXI"],
  [155, "SPELL_EFFECT_TITAN_GRIP"],
  [156, "SPELL_EFFECT_ENCHANT_ITEM_PRISMATIC"],
  [157, "SPELL_EFFECT_CREATE_ITEM_2"],
  [158, "SPELL_EFFECT_MILLING"],
  [159, "SPELL_EFFECT_ALLOW_RENAME_PET"],
  [160, "SPELL_EFFECT_FORCE_CAST_2"],
  [161, "SPELL_EFFECT_TALENT_SPEC_COUNT"],
  [162, "SPELL_EFFECT_TALENT_SPEC_SELECT"],
  [163, "SPELL_EFFECT_163"],
  [164, "SPELL_EFFECT_REMOVE_AURA"],
  [165, "TOTAL_SPELL_EFFECTS"],
]);

// AuraType
export const SPELL_AURA_NONE = 0;
export const SPELL_AURA_BIND_SIGHT = 1;
export const SPELL_AURA_MOD_POSSESS = 2;
export const SPELL_AURA_PERIODIC_DAMAGE = 3;
export const SPELL_AURA_DUMMY = 4;
export const SPELL_AURA_MOD_CONFUSE = 5;
export const SPELL_AURA_MOD_CHARM = 6;
export const SPELL_AURA_MOD_FEAR = 7;
export const SPELL_AURA_PERIODIC_HEAL = 8;
export const SPELL_AURA_MOD_ATTACKSPEED = 9;
export const SPELL_AURA_MOD_THREAT = 10;
export const SPELL_AURA_MOD_TAUNT = 11;
export const SPELL_AURA_MOD_STUN = 12;
export const SPELL_AURA_MOD_DAMAGE_DONE = 13;
export const SPELL_AURA_MOD_DAMAGE_TAKEN = 14;
export const SPELL_AURA_DAMAGE_SHIELD = 15;
export const SPELL_AURA_MOD_STEALTH = 16;
export const SPELL_AURA_MOD_STEALTH_DETECT = 17;
export const SPELL_AURA_MOD_INVISIBILITY = 18;
export const SPELL_AURA_MOD_INVISIBILITY_DETECT = 19;
export const SPELL_AURA_OBS_MOD_HEALTH = 20;
export const SPELL_AURA_OBS_MOD_POWER = 21;
export const SPELL_AURA_MOD_RESISTANCE = 22;
export const SPELL_AURA_PERIODIC_TRIGGER_SPELL = 23;
export const SPELL_AURA_PERIODIC_ENERGIZE = 24;
export const SPELL_AURA_MOD_PACIFY = 25;
export const SPELL_AURA_MOD_ROOT = 26;
export const SPELL_AURA_MOD_SILENCE = 27;
export const SPELL_AURA_REFLECT_SPELLS = 28;
export const SPELL_AURA_MOD_STAT = 29;
export const SPELL_AURA_MOD_SKILL = 30;
export const SPELL_AURA_MOD_INCREASE_SPEED = 31;
export const SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED = 32;
export const SPELL_AURA_MOD_DECREASE_SPEED = 33;
export const SPELL_AURA_MOD_INCREASE_HEALTH = 34;
export const SPELL_AURA_MOD_INCREASE_ENERGY = 35;
export const SPELL_AURA_MOD_SHAPESHIFT = 36;
export const SPELL_AURA_EFFECT_IMMUNITY = 37;
export const SPELL_AURA_STATE_IMMUNITY = 38;
export const SPELL_AURA_SCHOOL_IMMUNITY = 39;
export const SPELL_AURA_DAMAGE_IMMUNITY = 40;
export const SPELL_AURA_DISPEL_IMMUNITY = 41;
export const SPELL_AURA_PROC_TRIGGER_SPELL = 42;
export const SPELL_AURA_PROC_TRIGGER_DAMAGE = 43;
export const SPELL_AURA_TRACK_CREATURES = 44;
export const SPELL_AURA_TRACK_RESOURCES = 45;
export const SPELL_AURA_46 = 46;
export const SPELL_AURA_MOD_PARRY_PERCENT = 47;
export const SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT = 48;
export const SPELL_AURA_MOD_DODGE_PERCENT = 49;
export const SPELL_AURA_MOD_CRITICAL_HEALING_AMOUNT = 50;
export const SPELL_AURA_MOD_BLOCK_PERCENT = 51;
export const SPELL_AURA_MOD_WEAPON_CRIT_PERCENT = 52;
export const SPELL_AURA_PERIODIC_LEECH = 53;
export const SPELL_AURA_MOD_HIT_CHANCE = 54;
export const SPELL_AURA_MOD_SPELL_HIT_CHANCE = 55;
export const SPELL_AURA_TRANSFORM = 56;
export const SPELL_AURA_MOD_SPELL_CRIT_CHANCE = 57;
export const SPELL_AURA_MOD_INCREASE_SWIM_SPEED = 58;
export const SPELL_AURA_MOD_DAMAGE_DONE_CREATURE = 59;
export const SPELL_AURA_MOD_PACIFY_SILENCE = 60;
export const SPELL_AURA_MOD_SCALE = 61;
export const SPELL_AURA_PERIODIC_HEALTH_FUNNEL = 62;
export const SPELL_AURA_63 = 63;
export const SPELL_AURA_PERIODIC_MANA_LEECH = 64;
export const SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK = 65;
export const SPELL_AURA_FEIGN_DEATH = 66;
export const SPELL_AURA_MOD_DISARM = 67;
export const SPELL_AURA_MOD_STALKED = 68;
export const SPELL_AURA_SCHOOL_ABSORB = 69;
export const SPELL_AURA_EXTRA_ATTACKS = 70;
export const SPELL_AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL = 71;
export const SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT = 72;
export const SPELL_AURA_MOD_POWER_COST_SCHOOL = 73;
export const SPELL_AURA_REFLECT_SPELLS_SCHOOL = 74;
export const SPELL_AURA_MOD_LANGUAGE = 75;
export const SPELL_AURA_FAR_SIGHT = 76;
export const SPELL_AURA_MECHANIC_IMMUNITY = 77;
export const SPELL_AURA_MOUNTED = 78;
export const SPELL_AURA_MOD_DAMAGE_PERCENT_DONE = 79;
export const SPELL_AURA_MOD_PERCENT_STAT = 80;
export const SPELL_AURA_SPLIT_DAMAGE_PCT = 81;
export const SPELL_AURA_WATER_BREATHING = 82;
export const SPELL_AURA_MOD_BASE_RESISTANCE = 83;
export const SPELL_AURA_MOD_REGEN = 84;
export const SPELL_AURA_MOD_POWER_REGEN = 85;
export const SPELL_AURA_CHANNEL_DEATH_ITEM = 86;
export const SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN = 87;
export const SPELL_AURA_MOD_HEALTH_REGEN_PERCENT = 88;
export const SPELL_AURA_PERIODIC_DAMAGE_PERCENT = 89;
export const SPELL_AURA_90 = 90;
export const SPELL_AURA_MOD_DETECT_RANGE = 91;
export const SPELL_AURA_PREVENTS_FLEEING = 92;
export const SPELL_AURA_MOD_UNATTACKABLE = 93;
export const SPELL_AURA_INTERRUPT_REGEN = 94;
export const SPELL_AURA_GHOST = 95;
export const SPELL_AURA_SPELL_MAGNET = 96;
export const SPELL_AURA_MANA_SHIELD = 97;
export const SPELL_AURA_MOD_SKILL_TALENT = 98;
export const SPELL_AURA_MOD_ATTACK_POWER = 99;
export const SPELL_AURA_AURAS_VISIBLE = 100;
export const SPELL_AURA_MOD_RESISTANCE_PCT = 101;
export const SPELL_AURA_MOD_MELEE_ATTACK_POWER_VERSUS = 102;
export const SPELL_AURA_MOD_TOTAL_THREAT = 103;
export const SPELL_AURA_WATER_WALK = 104;
export const SPELL_AURA_FEATHER_FALL = 105;
export const SPELL_AURA_HOVER = 106;
export const SPELL_AURA_ADD_FLAT_MODIFIER = 107;
export const SPELL_AURA_ADD_PCT_MODIFIER = 108;
export const SPELL_AURA_ADD_TARGET_TRIGGER = 109;
export const SPELL_AURA_MOD_POWER_REGEN_PERCENT = 110;
export const SPELL_AURA_ADD_CASTER_HIT_TRIGGER = 111;
export const SPELL_AURA_OVERRIDE_CLASS_SCRIPTS = 112;
export const SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN = 113;
export const SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN_PCT = 114;
export const SPELL_AURA_MOD_HEALING = 115;
export const SPELL_AURA_MOD_REGEN_DURING_COMBAT = 116;
export const SPELL_AURA_MOD_MECHANIC_RESISTANCE = 117;
export const SPELL_AURA_MOD_HEALING_PCT = 118;
export const SPELL_AURA_119 = 119;
export const SPELL_AURA_UNTRACKABLE = 120;
export const SPELL_AURA_EMPATHY = 121;
export const SPELL_AURA_MOD_OFFHAND_DAMAGE_PCT = 122;
export const SPELL_AURA_MOD_TARGET_RESISTANCE = 123;
export const SPELL_AURA_MOD_RANGED_ATTACK_POWER = 124;
export const SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN = 125;
export const SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN_PCT = 126;
export const SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS = 127;
export const SPELL_AURA_MOD_POSSESS_PET = 128;
export const SPELL_AURA_MOD_SPEED_ALWAYS = 129;
export const SPELL_AURA_MOD_MOUNTED_SPEED_ALWAYS = 130;
export const SPELL_AURA_MOD_RANGED_ATTACK_POWER_VERSUS = 131;
export const SPELL_AURA_MOD_INCREASE_ENERGY_PERCENT = 132;
export const SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT = 133;
export const SPELL_AURA_MOD_MANA_REGEN_INTERRUPT = 134;
export const SPELL_AURA_MOD_HEALING_DONE = 135;
export const SPELL_AURA_MOD_HEALING_DONE_PERCENT = 136;
export const SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE = 137;
export const SPELL_AURA_MOD_MELEE_HASTE = 138;
export const SPELL_AURA_FORCE_REACTION = 139;
export const SPELL_AURA_MOD_RANGED_HASTE = 140;
export const SPELL_AURA_MOD_RANGED_AMMO_HASTE = 141;
export const SPELL_AURA_MOD_BASE_RESISTANCE_PCT = 142;
export const SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE = 143;
export const SPELL_AURA_SAFE_FALL = 144;
export const SPELL_AURA_MOD_PET_TALENT_POINTS = 145;
export const SPELL_AURA_ALLOW_TAME_PET_TYPE = 146;
export const SPELL_AURA_MECHANIC_IMMUNITY_MASK = 147;
export const SPELL_AURA_RETAIN_COMBO_POINTS = 148;
export const SPELL_AURA_REDUCE_PUSHBACK = 149;
export const SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT = 150;
export const SPELL_AURA_TRACK_STEALTHED = 151;
export const SPELL_AURA_MOD_DETECTED_RANGE = 152;
export const SPELL_AURA_SPLIT_DAMAGE_FLAT = 153;
export const SPELL_AURA_MOD_STEALTH_LEVEL = 154;
export const SPELL_AURA_MOD_WATER_BREATHING = 155;
export const SPELL_AURA_MOD_REPUTATION_GAIN = 156;
export const SPELL_AURA_PET_DAMAGE_MULTI = 157;
export const SPELL_AURA_MOD_SHIELD_BLOCKVALUE = 158;
export const SPELL_AURA_NO_PVP_CREDIT = 159;
export const SPELL_AURA_MOD_AOE_AVOIDANCE = 160;
export const SPELL_AURA_MOD_HEALTH_REGEN_IN_COMBAT = 161;
export const SPELL_AURA_POWER_BURN = 162;
export const SPELL_AURA_MOD_CRIT_DAMAGE_BONUS = 163;
export const SPELL_AURA_164 = 164;
export const SPELL_AURA_MELEE_ATTACK_POWER_ATTACKER_BONUS = 165;
export const SPELL_AURA_MOD_ATTACK_POWER_PCT = 166;
export const SPELL_AURA_MOD_RANGED_ATTACK_POWER_PCT = 167;
export const SPELL_AURA_MOD_DAMAGE_DONE_VERSUS = 168;
export const SPELL_AURA_MOD_CRIT_PERCENT_VERSUS = 169;
export const SPELL_AURA_DETECT_AMORE = 170;
export const SPELL_AURA_MOD_SPEED_NOT_STACK = 171;
export const SPELL_AURA_MOD_MOUNTED_SPEED_NOT_STACK = 172;
export const SPELL_AURA_173 = 173;
export const SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT = 174;
export const SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT = 175;
export const SPELL_AURA_SPIRIT_OF_REDEMPTION = 176;
export const SPELL_AURA_AOE_CHARM = 177;
export const SPELL_AURA_MOD_DEBUFF_RESISTANCE = 178;
export const SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE = 179;
export const SPELL_AURA_MOD_FLAT_SPELL_DAMAGE_VERSUS = 180;
export const SPELL_AURA_181 = 181;
export const SPELL_AURA_MOD_RESISTANCE_OF_STAT_PERCENT = 182;
export const SPELL_AURA_MOD_CRITICAL_THREAT = 183;
export const SPELL_AURA_MOD_ATTACKER_MELEE_HIT_CHANCE = 184;
export const SPELL_AURA_MOD_ATTACKER_RANGED_HIT_CHANCE = 185;
export const SPELL_AURA_MOD_ATTACKER_SPELL_HIT_CHANCE = 186;
export const SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_CHANCE = 187;
export const SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_CHANCE = 188;
export const SPELL_AURA_MOD_RATING = 189;
export const SPELL_AURA_MOD_FACTION_REPUTATION_GAIN = 190;
export const SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED = 191;
export const SPELL_AURA_MOD_MELEE_RANGED_HASTE = 192;
export const SPELL_AURA_MELEE_SLOW = 193;
export const SPELL_AURA_MOD_TARGET_ABSORB_SCHOOL = 194;
export const SPELL_AURA_MOD_TARGET_ABILITY_ABSORB_SCHOOL = 195;
export const SPELL_AURA_MOD_COOLDOWN = 196;
export const SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE = 197;
export const SPELL_AURA_198 = 198;
export const SPELL_AURA_MOD_INCREASES_SPELL_PCT_TO_HIT = 199;
export const SPELL_AURA_MOD_XP_PCT = 200;
export const SPELL_AURA_FLY = 201;
export const SPELL_AURA_IGNORE_COMBAT_RESULT = 202;
export const SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_DAMAGE = 203;
export const SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_DAMAGE = 204;
export const SPELL_AURA_MOD_SCHOOL_CRIT_DMG_TAKEN = 205;
export const SPELL_AURA_MOD_INCREASE_FLIGHT_SPEED = 206;
export const SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED = 207;
export const SPELL_AURA_MOD_FLIGHT_SPEED_ALWAYS = 208;
export const SPELL_AURA_MOD_MOUNTED_FLIGHT_SPEED_ALWAYS = 209;
export const SPELL_AURA_MOD_FLIGHT_SPEED_NOT_STACKING = 210;
export const SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED_NOT_STACKING = 211;
export const SPELL_AURA_MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT = 212;
export const SPELL_AURA_MOD_RAGE_FROM_DAMAGE_DEALT = 213;
export const SPELL_AURA_214 = 214;
export const SPELL_AURA_ARENA_PREPARATION = 215;
export const SPELL_AURA_HASTE_SPELLS = 216;
export const SPELL_AURA_MOD_MELEE_HASTE_2 = 217;
export const SPELL_AURA_HASTE_RANGED = 218;
export const SPELL_AURA_MOD_MANA_REGEN_FROM_STAT = 219;
export const SPELL_AURA_MOD_RATING_FROM_STAT = 220;
export const SPELL_AURA_MOD_DETAUNT = 221;
export const SPELL_AURA_222 = 222;
export const SPELL_AURA_RAID_PROC_FROM_CHARGE = 223;
export const SPELL_AURA_224 = 224;
export const SPELL_AURA_RAID_PROC_FROM_CHARGE_WITH_VALUE = 225;
export const SPELL_AURA_PERIODIC_DUMMY = 226;
export const SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE = 227;
export const SPELL_AURA_DETECT_STEALTH = 228;
export const SPELL_AURA_MOD_AOE_DAMAGE_AVOIDANCE = 229;
export const SPELL_AURA_230 = 230;
export const SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE = 231;
export const SPELL_AURA_MECHANIC_DURATION_MOD = 232;
export const SPELL_AURA_CHANGE_MODEL_FOR_ALL_HUMANOIDS = 233;
export const SPELL_AURA_MECHANIC_DURATION_MOD_NOT_STACK = 234;
export const SPELL_AURA_MOD_DISPEL_RESIST = 235;
export const SPELL_AURA_CONTROL_VEHICLE = 236;
export const SPELL_AURA_MOD_SPELL_DAMAGE_OF_ATTACK_POWER = 237;
export const SPELL_AURA_MOD_SPELL_HEALING_OF_ATTACK_POWER = 238;
export const SPELL_AURA_MOD_SCALE_2 = 239;
export const SPELL_AURA_MOD_EXPERTISE = 240;
export const SPELL_AURA_FORCE_MOVE_FORWARD = 241;
export const SPELL_AURA_MOD_SPELL_DAMAGE_FROM_HEALING = 242;
export const SPELL_AURA_MOD_FACTION = 243;
export const SPELL_AURA_COMPREHEND_LANGUAGE = 244;
export const SPELL_AURA_MOD_AURA_DURATION_BY_DISPEL = 245;
export const SPELL_AURA_MOD_AURA_DURATION_BY_DISPEL_NOT_STACK = 246;
export const SPELL_AURA_CLONE_CASTER = 247;
export const SPELL_AURA_MOD_COMBAT_RESULT_CHANCE = 248;
export const SPELL_AURA_CONVERT_RUNE = 249;
export const SPELL_AURA_MOD_INCREASE_HEALTH_2 = 250;
export const SPELL_AURA_MOD_ENEMY_DODGE = 251;
export const SPELL_AURA_MOD_SPEED_SLOW_ALL = 252;
export const SPELL_AURA_MOD_BLOCK_CRIT_CHANCE = 253;
export const SPELL_AURA_MOD_DISARM_OFFHAND = 254;
export const SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT = 255;
export const SPELL_AURA_NO_REAGENT_USE = 0x100;
export const SPELL_AURA_MOD_TARGET_RESIST_BY_SPELL_CLASS = 0x101;
export const SPELL_AURA_258 = 0x102;
export const SPELL_AURA_MOD_HOT_PCT = 0x103;
export const SPELL_AURA_SCREEN_EFFECT = 0x104;
export const SPELL_AURA_PHASE = 0x105;
export const SPELL_AURA_ABILITY_IGNORE_AURASTATE = 0x106;
export const SPELL_AURA_ALLOW_ONLY_ABILITY = 0x107;
export const SPELL_AURA_264 = 0x108;
export const SPELL_AURA_265 = 0x109;
export const SPELL_AURA_266 = 0x10a;
export const SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL = 0x10b;
export const SPELL_AURA_MOD_ATTACK_POWER_OF_STAT_PERCENT = 0x10c;
export const SPELL_AURA_MOD_IGNORE_TARGET_RESIST_MODIFIERS = 0x10d;
export const SPELL_AURA_MOD_ABILITY_IGNORE_TARGET_RESIST = 0x10e;
export const SPELL_AURA_MOD_DAMAGE_FROM_CASTER = 0x10f;
export const SPELL_AURA_IGNORE_MELEE_RESET = 0x110;
export const SPELL_AURA_X_RAY = 0x111;
export const SPELL_AURA_ABILITY_CONSUME_NO_AMMO = 0x112;
export const SPELL_AURA_MOD_IGNORE_SHAPESHIFT = 0x113;
export const SPELL_AURA_MOD_DAMAGE_DONE_FOR_MECHANIC = 0x114;
export const SPELL_AURA_MOD_MAX_AFFECTED_TARGETS = 0x115;
export const SPELL_AURA_MOD_DISARM_RANGED = 0x116;
export const SPELL_AURA_INITIALIZE_IMAGES = 0x117;
export const SPELL_AURA_MOD_ARMOR_PENETRATION_PCT = 0x118;
export const SPELL_AURA_MOD_HONOR_GAIN_PCT = 0x119;
export const SPELL_AURA_MOD_BASE_HEALTH_PCT = 0x11a;
export const SPELL_AURA_MOD_HEALING_RECEIVED = 0x11b;
export const SPELL_AURA_LINKED = 0x11c;
export const SPELL_AURA_MOD_ATTACK_POWER_OF_ARMOR = 0x11d;
export const SPELL_AURA_ABILITY_PERIODIC_CRIT = 0x11e;
export const SPELL_AURA_DEFLECT_SPELLS = 0x11f;
export const SPELL_AURA_IGNORE_HIT_DIRECTION = 0x120;
export const SPELL_AURA_PREVENT_DURABILITY_LOSS = 0x121;
export const SPELL_AURA_MOD_CRIT_PCT = 0x122;
export const SPELL_AURA_MOD_XP_QUEST_PCT = 0x123;
export const SPELL_AURA_OPEN_STABLE = 0x124;
export const SPELL_AURA_OVERRIDE_SPELLS = 0x125;
export const SPELL_AURA_PREVENT_REGENERATE_POWER = 0x126;
export const SPELL_AURA_295 = 0x127;
export const SPELL_AURA_SET_VEHICLE_ID = 0x128;
export const SPELL_AURA_BLOCK_SPELL_FAMILY = 0x129;
export const SPELL_AURA_STRANGULATE = 0x12a;
export const SPELL_AURA_299 = 0x12b;
export const SPELL_AURA_SHARE_DAMAGE_PCT = 0x12c;
export const SPELL_AURA_SCHOOL_HEAL_ABSORB = 0x12d;
export const SPELL_AURA_302 = 0x12e;
export const SPELL_AURA_MOD_DAMAGE_DONE_VERSUS_AURASTATE = 0x12f;
export const SPELL_AURA_MOD_FAKE_INEBRIATE = 0x130;
export const SPELL_AURA_MOD_MINIMUM_SPEED = 0x131;
export const SPELL_AURA_306 = 0x132;
export const SPELL_AURA_HEAL_ABSORB_TEST = 0x133;
export const SPELL_AURA_MOD_CRIT_CHANCE_FOR_CASTER = 0x134;
export const SPELL_AURA_309 = 0x135;
export const SPELL_AURA_MOD_CREATURE_AOE_DAMAGE_AVOIDANCE = 0x136;
export const SPELL_AURA_311 = 0x137;
export const SPELL_AURA_312 = 0x138;
export const SPELL_AURA_313 = 0x139;
export const SPELL_AURA_PREVENT_RESURRECTION = 0x13a;
export const SPELL_AURA_UNDERWATER_WALKING = 0x13b;
export const SPELL_AURA_PERIODIC_HASTE = 0x13c;
export const TOTAL_AURAS = 0x13d;
export const AURA_NAMES: ReadonlyMap<number, string> = new Map([
  [0, "SPELL_AURA_NONE"],
  [1, "SPELL_AURA_BIND_SIGHT"],
  [2, "SPELL_AURA_MOD_POSSESS"],
  [3, "SPELL_AURA_PERIODIC_DAMAGE"],
  [4, "SPELL_AURA_DUMMY"],
  [5, "SPELL_AURA_MOD_CONFUSE"],
  [6, "SPELL_AURA_MOD_CHARM"],
  [7, "SPELL_AURA_MOD_FEAR"],
  [8, "SPELL_AURA_PERIODIC_HEAL"],
  [9, "SPELL_AURA_MOD_ATTACKSPEED"],
  [10, "SPELL_AURA_MOD_THREAT"],
  [11, "SPELL_AURA_MOD_TAUNT"],
  [12, "SPELL_AURA_MOD_STUN"],
  [13, "SPELL_AURA_MOD_DAMAGE_DONE"],
  [14, "SPELL_AURA_MOD_DAMAGE_TAKEN"],
  [15, "SPELL_AURA_DAMAGE_SHIELD"],
  [16, "SPELL_AURA_MOD_STEALTH"],
  [17, "SPELL_AURA_MOD_STEALTH_DETECT"],
  [18, "SPELL_AURA_MOD_INVISIBILITY"],
  [19, "SPELL_AURA_MOD_INVISIBILITY_DETECT"],
  [20, "SPELL_AURA_OBS_MOD_HEALTH"],
  [21, "SPELL_AURA_OBS_MOD_POWER"],
  [22, "SPELL_AURA_MOD_RESISTANCE"],
  [23, "SPELL_AURA_PERIODIC_TRIGGER_SPELL"],
  [24, "SPELL_AURA_PERIODIC_ENERGIZE"],
  [25, "SPELL_AURA_MOD_PACIFY"],
  [26, "SPELL_AURA_MOD_ROOT"],
  [27, "SPELL_AURA_MOD_SILENCE"],
  [28, "SPELL_AURA_REFLECT_SPELLS"],
  [29, "SPELL_AURA_MOD_STAT"],
  [30, "SPELL_AURA_MOD_SKILL"],
  [31, "SPELL_AURA_MOD_INCREASE_SPEED"],
  [32, "SPELL_AURA_MOD_INCREASE_MOUNTED_SPEED"],
  [33, "SPELL_AURA_MOD_DECREASE_SPEED"],
  [34, "SPELL_AURA_MOD_INCREASE_HEALTH"],
  [35, "SPELL_AURA_MOD_INCREASE_ENERGY"],
  [36, "SPELL_AURA_MOD_SHAPESHIFT"],
  [37, "SPELL_AURA_EFFECT_IMMUNITY"],
  [38, "SPELL_AURA_STATE_IMMUNITY"],
  [39, "SPELL_AURA_SCHOOL_IMMUNITY"],
  [40, "SPELL_AURA_DAMAGE_IMMUNITY"],
  [41, "SPELL_AURA_DISPEL_IMMUNITY"],
  [42, "SPELL_AURA_PROC_TRIGGER_SPELL"],
  [43, "SPELL_AURA_PROC_TRIGGER_DAMAGE"],
  [44, "SPELL_AURA_TRACK_CREATURES"],
  [45, "SPELL_AURA_TRACK_RESOURCES"],
  [46, "SPELL_AURA_46"],
  [47, "SPELL_AURA_MOD_PARRY_PERCENT"],
  [48, "SPELL_AURA_PERIODIC_TRIGGER_SPELL_FROM_CLIENT"],
  [49, "SPELL_AURA_MOD_DODGE_PERCENT"],
  [50, "SPELL_AURA_MOD_CRITICAL_HEALING_AMOUNT"],
  [51, "SPELL_AURA_MOD_BLOCK_PERCENT"],
  [52, "SPELL_AURA_MOD_WEAPON_CRIT_PERCENT"],
  [53, "SPELL_AURA_PERIODIC_LEECH"],
  [54, "SPELL_AURA_MOD_HIT_CHANCE"],
  [55, "SPELL_AURA_MOD_SPELL_HIT_CHANCE"],
  [56, "SPELL_AURA_TRANSFORM"],
  [57, "SPELL_AURA_MOD_SPELL_CRIT_CHANCE"],
  [58, "SPELL_AURA_MOD_INCREASE_SWIM_SPEED"],
  [59, "SPELL_AURA_MOD_DAMAGE_DONE_CREATURE"],
  [60, "SPELL_AURA_MOD_PACIFY_SILENCE"],
  [61, "SPELL_AURA_MOD_SCALE"],
  [62, "SPELL_AURA_PERIODIC_HEALTH_FUNNEL"],
  [63, "SPELL_AURA_63"],
  [64, "SPELL_AURA_PERIODIC_MANA_LEECH"],
  [65, "SPELL_AURA_MOD_CASTING_SPEED_NOT_STACK"],
  [66, "SPELL_AURA_FEIGN_DEATH"],
  [67, "SPELL_AURA_MOD_DISARM"],
  [68, "SPELL_AURA_MOD_STALKED"],
  [69, "SPELL_AURA_SCHOOL_ABSORB"],
  [70, "SPELL_AURA_EXTRA_ATTACKS"],
  [71, "SPELL_AURA_MOD_SPELL_CRIT_CHANCE_SCHOOL"],
  [72, "SPELL_AURA_MOD_POWER_COST_SCHOOL_PCT"],
  [73, "SPELL_AURA_MOD_POWER_COST_SCHOOL"],
  [74, "SPELL_AURA_REFLECT_SPELLS_SCHOOL"],
  [75, "SPELL_AURA_MOD_LANGUAGE"],
  [76, "SPELL_AURA_FAR_SIGHT"],
  [77, "SPELL_AURA_MECHANIC_IMMUNITY"],
  [78, "SPELL_AURA_MOUNTED"],
  [79, "SPELL_AURA_MOD_DAMAGE_PERCENT_DONE"],
  [80, "SPELL_AURA_MOD_PERCENT_STAT"],
  [81, "SPELL_AURA_SPLIT_DAMAGE_PCT"],
  [82, "SPELL_AURA_WATER_BREATHING"],
  [83, "SPELL_AURA_MOD_BASE_RESISTANCE"],
  [84, "SPELL_AURA_MOD_REGEN"],
  [85, "SPELL_AURA_MOD_POWER_REGEN"],
  [86, "SPELL_AURA_CHANNEL_DEATH_ITEM"],
  [87, "SPELL_AURA_MOD_DAMAGE_PERCENT_TAKEN"],
  [88, "SPELL_AURA_MOD_HEALTH_REGEN_PERCENT"],
  [89, "SPELL_AURA_PERIODIC_DAMAGE_PERCENT"],
  [90, "SPELL_AURA_90"],
  [91, "SPELL_AURA_MOD_DETECT_RANGE"],
  [92, "SPELL_AURA_PREVENTS_FLEEING"],
  [93, "SPELL_AURA_MOD_UNATTACKABLE"],
  [94, "SPELL_AURA_INTERRUPT_REGEN"],
  [95, "SPELL_AURA_GHOST"],
  [96, "SPELL_AURA_SPELL_MAGNET"],
  [97, "SPELL_AURA_MANA_SHIELD"],
  [98, "SPELL_AURA_MOD_SKILL_TALENT"],
  [99, "SPELL_AURA_MOD_ATTACK_POWER"],
  [100, "SPELL_AURA_AURAS_VISIBLE"],
  [101, "SPELL_AURA_MOD_RESISTANCE_PCT"],
  [102, "SPELL_AURA_MOD_MELEE_ATTACK_POWER_VERSUS"],
  [103, "SPELL_AURA_MOD_TOTAL_THREAT"],
  [104, "SPELL_AURA_WATER_WALK"],
  [105, "SPELL_AURA_FEATHER_FALL"],
  [106, "SPELL_AURA_HOVER"],
  [107, "SPELL_AURA_ADD_FLAT_MODIFIER"],
  [108, "SPELL_AURA_ADD_PCT_MODIFIER"],
  [109, "SPELL_AURA_ADD_TARGET_TRIGGER"],
  [110, "SPELL_AURA_MOD_POWER_REGEN_PERCENT"],
  [111, "SPELL_AURA_ADD_CASTER_HIT_TRIGGER"],
  [112, "SPELL_AURA_OVERRIDE_CLASS_SCRIPTS"],
  [113, "SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN"],
  [114, "SPELL_AURA_MOD_RANGED_DAMAGE_TAKEN_PCT"],
  [115, "SPELL_AURA_MOD_HEALING"],
  [116, "SPELL_AURA_MOD_REGEN_DURING_COMBAT"],
  [117, "SPELL_AURA_MOD_MECHANIC_RESISTANCE"],
  [118, "SPELL_AURA_MOD_HEALING_PCT"],
  [119, "SPELL_AURA_119"],
  [120, "SPELL_AURA_UNTRACKABLE"],
  [121, "SPELL_AURA_EMPATHY"],
  [122, "SPELL_AURA_MOD_OFFHAND_DAMAGE_PCT"],
  [123, "SPELL_AURA_MOD_TARGET_RESISTANCE"],
  [124, "SPELL_AURA_MOD_RANGED_ATTACK_POWER"],
  [125, "SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN"],
  [126, "SPELL_AURA_MOD_MELEE_DAMAGE_TAKEN_PCT"],
  [127, "SPELL_AURA_RANGED_ATTACK_POWER_ATTACKER_BONUS"],
  [128, "SPELL_AURA_MOD_POSSESS_PET"],
  [129, "SPELL_AURA_MOD_SPEED_ALWAYS"],
  [130, "SPELL_AURA_MOD_MOUNTED_SPEED_ALWAYS"],
  [131, "SPELL_AURA_MOD_RANGED_ATTACK_POWER_VERSUS"],
  [132, "SPELL_AURA_MOD_INCREASE_ENERGY_PERCENT"],
  [133, "SPELL_AURA_MOD_INCREASE_HEALTH_PERCENT"],
  [134, "SPELL_AURA_MOD_MANA_REGEN_INTERRUPT"],
  [135, "SPELL_AURA_MOD_HEALING_DONE"],
  [136, "SPELL_AURA_MOD_HEALING_DONE_PERCENT"],
  [137, "SPELL_AURA_MOD_TOTAL_STAT_PERCENTAGE"],
  [138, "SPELL_AURA_MOD_MELEE_HASTE"],
  [139, "SPELL_AURA_FORCE_REACTION"],
  [140, "SPELL_AURA_MOD_RANGED_HASTE"],
  [141, "SPELL_AURA_MOD_RANGED_AMMO_HASTE"],
  [142, "SPELL_AURA_MOD_BASE_RESISTANCE_PCT"],
  [143, "SPELL_AURA_MOD_RESISTANCE_EXCLUSIVE"],
  [144, "SPELL_AURA_SAFE_FALL"],
  [145, "SPELL_AURA_MOD_PET_TALENT_POINTS"],
  [146, "SPELL_AURA_ALLOW_TAME_PET_TYPE"],
  [147, "SPELL_AURA_MECHANIC_IMMUNITY_MASK"],
  [148, "SPELL_AURA_RETAIN_COMBO_POINTS"],
  [149, "SPELL_AURA_REDUCE_PUSHBACK"],
  [150, "SPELL_AURA_MOD_SHIELD_BLOCKVALUE_PCT"],
  [151, "SPELL_AURA_TRACK_STEALTHED"],
  [152, "SPELL_AURA_MOD_DETECTED_RANGE"],
  [153, "SPELL_AURA_SPLIT_DAMAGE_FLAT"],
  [154, "SPELL_AURA_MOD_STEALTH_LEVEL"],
  [155, "SPELL_AURA_MOD_WATER_BREATHING"],
  [156, "SPELL_AURA_MOD_REPUTATION_GAIN"],
  [157, "SPELL_AURA_PET_DAMAGE_MULTI"],
  [158, "SPELL_AURA_MOD_SHIELD_BLOCKVALUE"],
  [159, "SPELL_AURA_NO_PVP_CREDIT"],
  [160, "SPELL_AURA_MOD_AOE_AVOIDANCE"],
  [161, "SPELL_AURA_MOD_HEALTH_REGEN_IN_COMBAT"],
  [162, "SPELL_AURA_POWER_BURN"],
  [163, "SPELL_AURA_MOD_CRIT_DAMAGE_BONUS"],
  [164, "SPELL_AURA_164"],
  [165, "SPELL_AURA_MELEE_ATTACK_POWER_ATTACKER_BONUS"],
  [166, "SPELL_AURA_MOD_ATTACK_POWER_PCT"],
  [167, "SPELL_AURA_MOD_RANGED_ATTACK_POWER_PCT"],
  [168, "SPELL_AURA_MOD_DAMAGE_DONE_VERSUS"],
  [169, "SPELL_AURA_MOD_CRIT_PERCENT_VERSUS"],
  [170, "SPELL_AURA_DETECT_AMORE"],
  [171, "SPELL_AURA_MOD_SPEED_NOT_STACK"],
  [172, "SPELL_AURA_MOD_MOUNTED_SPEED_NOT_STACK"],
  [173, "SPELL_AURA_173"],
  [174, "SPELL_AURA_MOD_SPELL_DAMAGE_OF_STAT_PERCENT"],
  [175, "SPELL_AURA_MOD_SPELL_HEALING_OF_STAT_PERCENT"],
  [176, "SPELL_AURA_SPIRIT_OF_REDEMPTION"],
  [177, "SPELL_AURA_AOE_CHARM"],
  [178, "SPELL_AURA_MOD_DEBUFF_RESISTANCE"],
  [179, "SPELL_AURA_MOD_ATTACKER_SPELL_CRIT_CHANCE"],
  [180, "SPELL_AURA_MOD_FLAT_SPELL_DAMAGE_VERSUS"],
  [181, "SPELL_AURA_181"],
  [182, "SPELL_AURA_MOD_RESISTANCE_OF_STAT_PERCENT"],
  [183, "SPELL_AURA_MOD_CRITICAL_THREAT"],
  [184, "SPELL_AURA_MOD_ATTACKER_MELEE_HIT_CHANCE"],
  [185, "SPELL_AURA_MOD_ATTACKER_RANGED_HIT_CHANCE"],
  [186, "SPELL_AURA_MOD_ATTACKER_SPELL_HIT_CHANCE"],
  [187, "SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_CHANCE"],
  [188, "SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_CHANCE"],
  [189, "SPELL_AURA_MOD_RATING"],
  [190, "SPELL_AURA_MOD_FACTION_REPUTATION_GAIN"],
  [191, "SPELL_AURA_USE_NORMAL_MOVEMENT_SPEED"],
  [192, "SPELL_AURA_MOD_MELEE_RANGED_HASTE"],
  [193, "SPELL_AURA_MELEE_SLOW"],
  [194, "SPELL_AURA_MOD_TARGET_ABSORB_SCHOOL"],
  [195, "SPELL_AURA_MOD_TARGET_ABILITY_ABSORB_SCHOOL"],
  [196, "SPELL_AURA_MOD_COOLDOWN"],
  [197, "SPELL_AURA_MOD_ATTACKER_SPELL_AND_WEAPON_CRIT_CHANCE"],
  [198, "SPELL_AURA_198"],
  [199, "SPELL_AURA_MOD_INCREASES_SPELL_PCT_TO_HIT"],
  [200, "SPELL_AURA_MOD_XP_PCT"],
  [201, "SPELL_AURA_FLY"],
  [202, "SPELL_AURA_IGNORE_COMBAT_RESULT"],
  [203, "SPELL_AURA_MOD_ATTACKER_MELEE_CRIT_DAMAGE"],
  [204, "SPELL_AURA_MOD_ATTACKER_RANGED_CRIT_DAMAGE"],
  [205, "SPELL_AURA_MOD_SCHOOL_CRIT_DMG_TAKEN"],
  [206, "SPELL_AURA_MOD_INCREASE_FLIGHT_SPEED"],
  [207, "SPELL_AURA_MOD_INCREASE_MOUNTED_FLIGHT_SPEED"],
  [208, "SPELL_AURA_MOD_FLIGHT_SPEED_ALWAYS"],
  [209, "SPELL_AURA_MOD_MOUNTED_FLIGHT_SPEED_ALWAYS"],
  [210, "SPELL_AURA_MOD_FLIGHT_SPEED_NOT_STACKING"],
  [211, "SPELL_AURA_MOD_FLIGHT_SPEED_MOUNTED_NOT_STACKING"],
  [212, "SPELL_AURA_MOD_RANGED_ATTACK_POWER_OF_STAT_PERCENT"],
  [213, "SPELL_AURA_MOD_RAGE_FROM_DAMAGE_DEALT"],
  [214, "SPELL_AURA_214"],
  [215, "SPELL_AURA_ARENA_PREPARATION"],
  [216, "SPELL_AURA_HASTE_SPELLS"],
  [217, "SPELL_AURA_MOD_MELEE_HASTE_2"],
  [218, "SPELL_AURA_HASTE_RANGED"],
  [219, "SPELL_AURA_MOD_MANA_REGEN_FROM_STAT"],
  [220, "SPELL_AURA_MOD_RATING_FROM_STAT"],
  [221, "SPELL_AURA_MOD_DETAUNT"],
  [222, "SPELL_AURA_222"],
  [223, "SPELL_AURA_RAID_PROC_FROM_CHARGE"],
  [224, "SPELL_AURA_224"],
  [225, "SPELL_AURA_RAID_PROC_FROM_CHARGE_WITH_VALUE"],
  [226, "SPELL_AURA_PERIODIC_DUMMY"],
  [227, "SPELL_AURA_PERIODIC_TRIGGER_SPELL_WITH_VALUE"],
  [228, "SPELL_AURA_DETECT_STEALTH"],
  [229, "SPELL_AURA_MOD_AOE_DAMAGE_AVOIDANCE"],
  [230, "SPELL_AURA_230"],
  [231, "SPELL_AURA_PROC_TRIGGER_SPELL_WITH_VALUE"],
  [232, "SPELL_AURA_MECHANIC_DURATION_MOD"],
  [233, "SPELL_AURA_CHANGE_MODEL_FOR_ALL_HUMANOIDS"],
  [234, "SPELL_AURA_MECHANIC_DURATION_MOD_NOT_STACK"],
  [235, "SPELL_AURA_MOD_DISPEL_RESIST"],
  [236, "SPELL_AURA_CONTROL_VEHICLE"],
  [237, "SPELL_AURA_MOD_SPELL_DAMAGE_OF_ATTACK_POWER"],
  [238, "SPELL_AURA_MOD_SPELL_HEALING_OF_ATTACK_POWER"],
  [239, "SPELL_AURA_MOD_SCALE_2"],
  [240, "SPELL_AURA_MOD_EXPERTISE"],
  [241, "SPELL_AURA_FORCE_MOVE_FORWARD"],
  [242, "SPELL_AURA_MOD_SPELL_DAMAGE_FROM_HEALING"],
  [243, "SPELL_AURA_MOD_FACTION"],
  [244, "SPELL_AURA_COMPREHEND_LANGUAGE"],
  [245, "SPELL_AURA_MOD_AURA_DURATION_BY_DISPEL"],
  [246, "SPELL_AURA_MOD_AURA_DURATION_BY_DISPEL_NOT_STACK"],
  [247, "SPELL_AURA_CLONE_CASTER"],
  [248, "SPELL_AURA_MOD_COMBAT_RESULT_CHANCE"],
  [249, "SPELL_AURA_CONVERT_RUNE"],
  [250, "SPELL_AURA_MOD_INCREASE_HEALTH_2"],
  [251, "SPELL_AURA_MOD_ENEMY_DODGE"],
  [252, "SPELL_AURA_MOD_SPEED_SLOW_ALL"],
  [253, "SPELL_AURA_MOD_BLOCK_CRIT_CHANCE"],
  [254, "SPELL_AURA_MOD_DISARM_OFFHAND"],
  [255, "SPELL_AURA_MOD_MECHANIC_DAMAGE_TAKEN_PERCENT"],
  [256, "SPELL_AURA_NO_REAGENT_USE"],
  [257, "SPELL_AURA_MOD_TARGET_RESIST_BY_SPELL_CLASS"],
  [258, "SPELL_AURA_258"],
  [259, "SPELL_AURA_MOD_HOT_PCT"],
  [260, "SPELL_AURA_SCREEN_EFFECT"],
  [261, "SPELL_AURA_PHASE"],
  [262, "SPELL_AURA_ABILITY_IGNORE_AURASTATE"],
  [263, "SPELL_AURA_ALLOW_ONLY_ABILITY"],
  [264, "SPELL_AURA_264"],
  [265, "SPELL_AURA_265"],
  [266, "SPELL_AURA_266"],
  [267, "SPELL_AURA_MOD_IMMUNE_AURA_APPLY_SCHOOL"],
  [268, "SPELL_AURA_MOD_ATTACK_POWER_OF_STAT_PERCENT"],
  [269, "SPELL_AURA_MOD_IGNORE_TARGET_RESIST_MODIFIERS"],
  [270, "SPELL_AURA_MOD_ABILITY_IGNORE_TARGET_RESIST"],
  [271, "SPELL_AURA_MOD_DAMAGE_FROM_CASTER"],
  [272, "SPELL_AURA_IGNORE_MELEE_RESET"],
  [273, "SPELL_AURA_X_RAY"],
  [274, "SPELL_AURA_ABILITY_CONSUME_NO_AMMO"],
  [275, "SPELL_AURA_MOD_IGNORE_SHAPESHIFT"],
  [276, "SPELL_AURA_MOD_DAMAGE_DONE_FOR_MECHANIC"],
  [277, "SPELL_AURA_MOD_MAX_AFFECTED_TARGETS"],
  [278, "SPELL_AURA_MOD_DISARM_RANGED"],
  [279, "SPELL_AURA_INITIALIZE_IMAGES"],
  [280, "SPELL_AURA_MOD_ARMOR_PENETRATION_PCT"],
  [281, "SPELL_AURA_MOD_HONOR_GAIN_PCT"],
  [282, "SPELL_AURA_MOD_BASE_HEALTH_PCT"],
  [283, "SPELL_AURA_MOD_HEALING_RECEIVED"],
  [284, "SPELL_AURA_LINKED"],
  [285, "SPELL_AURA_MOD_ATTACK_POWER_OF_ARMOR"],
  [286, "SPELL_AURA_ABILITY_PERIODIC_CRIT"],
  [287, "SPELL_AURA_DEFLECT_SPELLS"],
  [288, "SPELL_AURA_IGNORE_HIT_DIRECTION"],
  [289, "SPELL_AURA_PREVENT_DURABILITY_LOSS"],
  [290, "SPELL_AURA_MOD_CRIT_PCT"],
  [291, "SPELL_AURA_MOD_XP_QUEST_PCT"],
  [292, "SPELL_AURA_OPEN_STABLE"],
  [293, "SPELL_AURA_OVERRIDE_SPELLS"],
  [294, "SPELL_AURA_PREVENT_REGENERATE_POWER"],
  [295, "SPELL_AURA_295"],
  [296, "SPELL_AURA_SET_VEHICLE_ID"],
  [297, "SPELL_AURA_BLOCK_SPELL_FAMILY"],
  [298, "SPELL_AURA_STRANGULATE"],
  [299, "SPELL_AURA_299"],
  [300, "SPELL_AURA_SHARE_DAMAGE_PCT"],
  [301, "SPELL_AURA_SCHOOL_HEAL_ABSORB"],
  [302, "SPELL_AURA_302"],
  [303, "SPELL_AURA_MOD_DAMAGE_DONE_VERSUS_AURASTATE"],
  [304, "SPELL_AURA_MOD_FAKE_INEBRIATE"],
  [305, "SPELL_AURA_MOD_MINIMUM_SPEED"],
  [306, "SPELL_AURA_306"],
  [307, "SPELL_AURA_HEAL_ABSORB_TEST"],
  [308, "SPELL_AURA_MOD_CRIT_CHANCE_FOR_CASTER"],
  [309, "SPELL_AURA_309"],
  [310, "SPELL_AURA_MOD_CREATURE_AOE_DAMAGE_AVOIDANCE"],
  [311, "SPELL_AURA_311"],
  [312, "SPELL_AURA_312"],
  [313, "SPELL_AURA_313"],
  [314, "SPELL_AURA_PREVENT_RESURRECTION"],
  [315, "SPELL_AURA_UNDERWATER_WALKING"],
  [316, "SPELL_AURA_PERIODIC_HASTE"],
  [317, "TOTAL_AURAS"],
]);

// Targets
export const TARGET_UNIT_CASTER = 1;
export const TARGET_UNIT_NEARBY_ENEMY = 2;
export const TARGET_UNIT_NEARBY_ALLY = 3;
export const TARGET_UNIT_NEARBY_PARTY = 4;
export const TARGET_UNIT_PET = 5;
export const TARGET_UNIT_TARGET_ENEMY = 6;
export const TARGET_UNIT_SRC_AREA_ENTRY = 7;
export const TARGET_UNIT_DEST_AREA_ENTRY = 8;
export const TARGET_DEST_HOME = 9;
export const TARGET_UNIT_SRC_AREA_UNK_11 = 11;
export const TARGET_UNIT_SRC_AREA_ENEMY = 15;
export const TARGET_UNIT_DEST_AREA_ENEMY = 16;
export const TARGET_DEST_DB = 17;
export const TARGET_DEST_CASTER = 18;
export const TARGET_UNIT_CASTER_AREA_PARTY = 20;
export const TARGET_UNIT_TARGET_ALLY = 21;
export const TARGET_SRC_CASTER = 22;
export const TARGET_GAMEOBJECT_TARGET = 23;
export const TARGET_UNIT_CONE_ENEMY_24 = 24;
export const TARGET_UNIT_TARGET_ANY = 25;
export const TARGET_GAMEOBJECT_ITEM_TARGET = 26;
export const TARGET_UNIT_MASTER = 27;
export const TARGET_DEST_DYNOBJ_ENEMY = 28;
export const TARGET_DEST_DYNOBJ_ALLY = 29;
export const TARGET_UNIT_SRC_AREA_ALLY = 30;
export const TARGET_UNIT_DEST_AREA_ALLY = 31;
export const TARGET_DEST_CASTER_SUMMON = 32;
export const TARGET_UNIT_SRC_AREA_PARTY = 33;
export const TARGET_UNIT_DEST_AREA_PARTY = 34;
export const TARGET_UNIT_TARGET_PARTY = 35;
export const TARGET_DEST_CASTER_36 = 36;
export const TARGET_UNIT_LASTTARGET_AREA_PARTY = 37;
export const TARGET_UNIT_NEARBY_ENTRY = 38;
export const TARGET_DEST_CASTER_FISHING = 39;
export const TARGET_GAMEOBJECT_NEARBY_ENTRY = 40;
export const TARGET_DEST_CASTER_FRONT_RIGHT = 41;
export const TARGET_DEST_CASTER_BACK_RIGHT = 42;
export const TARGET_DEST_CASTER_BACK_LEFT = 43;
export const TARGET_DEST_CASTER_FRONT_LEFT = 44;
export const TARGET_UNIT_TARGET_CHAINHEAL_ALLY = 45;
export const TARGET_DEST_NEARBY_ENTRY = 46;
export const TARGET_DEST_CASTER_FRONT = 47;
export const TARGET_DEST_CASTER_BACK = 48;
export const TARGET_DEST_CASTER_RIGHT = 49;
export const TARGET_DEST_CASTER_LEFT = 50;
export const TARGET_GAMEOBJECT_SRC_AREA = 51;
export const TARGET_GAMEOBJECT_DEST_AREA = 52;
export const TARGET_DEST_TARGET_ENEMY = 53;
export const TARGET_UNIT_CONE_ENEMY_54 = 54;
export const TARGET_DEST_CASTER_FRONT_LEAP = 55;
export const TARGET_UNIT_CASTER_AREA_RAID = 56;
export const TARGET_UNIT_TARGET_RAID = 57;
export const TARGET_UNIT_NEARBY_RAID = 58;
export const TARGET_UNIT_CONE_ALLY = 59;
export const TARGET_UNIT_CONE_ENTRY = 60;
export const TARGET_UNIT_TARGET_AREA_RAID_CLASS = 61;
export const TARGET_UNK_62 = 62;
export const TARGET_DEST_TARGET_ANY = 63;
export const TARGET_DEST_TARGET_FRONT = 64;
export const TARGET_DEST_TARGET_BACK = 65;
export const TARGET_DEST_TARGET_RIGHT = 66;
export const TARGET_DEST_TARGET_LEFT = 67;
export const TARGET_DEST_TARGET_FRONT_RIGHT = 68;
export const TARGET_DEST_TARGET_BACK_RIGHT = 69;
export const TARGET_DEST_TARGET_BACK_LEFT = 70;
export const TARGET_DEST_TARGET_FRONT_LEFT = 71;
export const TARGET_DEST_CASTER_RANDOM = 72;
export const TARGET_DEST_CASTER_RADIUS = 73;
export const TARGET_DEST_TARGET_RANDOM = 74;
export const TARGET_DEST_TARGET_RADIUS = 75;
export const TARGET_DEST_CHANNEL_TARGET = 76;
export const TARGET_UNIT_CHANNEL_TARGET = 77;
export const TARGET_DEST_DEST_FRONT = 78;
export const TARGET_DEST_DEST_BACK = 79;
export const TARGET_DEST_DEST_RIGHT = 80;
export const TARGET_DEST_DEST_LEFT = 81;
export const TARGET_DEST_DEST_FRONT_RIGHT = 82;
export const TARGET_DEST_DEST_BACK_RIGHT = 83;
export const TARGET_DEST_DEST_BACK_LEFT = 84;
export const TARGET_DEST_DEST_FRONT_LEFT = 85;
export const TARGET_DEST_DEST_RANDOM = 86;
export const TARGET_DEST_DEST = 87;
export const TARGET_DEST_DYNOBJ_NONE = 88;
export const TARGET_DEST_TRAJ = 89;
export const TARGET_UNIT_TARGET_MINIPET = 90;
export const TARGET_DEST_DEST_RADIUS = 91;
export const TARGET_UNIT_SUMMONER = 92;
export const TARGET_CORPSE_SRC_AREA_ENEMY = 93;
export const TARGET_UNIT_VEHICLE = 94;
export const TARGET_UNIT_TARGET_PASSENGER = 95;
export const TARGET_UNIT_PASSENGER_0 = 96;
export const TARGET_UNIT_PASSENGER_1 = 97;
export const TARGET_UNIT_PASSENGER_2 = 98;
export const TARGET_UNIT_PASSENGER_3 = 99;
export const TARGET_UNIT_PASSENGER_4 = 100;
export const TARGET_UNIT_PASSENGER_5 = 101;
export const TARGET_UNIT_PASSENGER_6 = 102;
export const TARGET_UNIT_PASSENGER_7 = 103;
export const TARGET_UNIT_CONE_ENEMY_104 = 104;
export const TARGET_UNIT_UNK_105 = 105;
export const TARGET_DEST_CHANNEL_CASTER = 106;
export const TARGET_UNK_DEST_AREA_UNK_107 = 107;
export const TARGET_GAMEOBJECT_CONE = 108;
export const TARGET_DEST_UNK_110 = 110;
export const TARGET_NAMES: ReadonlyMap<number, string> = new Map([
  [1, "TARGET_UNIT_CASTER"],
  [2, "TARGET_UNIT_NEARBY_ENEMY"],
  [3, "TARGET_UNIT_NEARBY_ALLY"],
  [4, "TARGET_UNIT_NEARBY_PARTY"],
  [5, "TARGET_UNIT_PET"],
  [6, "TARGET_UNIT_TARGET_ENEMY"],
  [7, "TARGET_UNIT_SRC_AREA_ENTRY"],
  [8, "TARGET_UNIT_DEST_AREA_ENTRY"],
  [9, "TARGET_DEST_HOME"],
  [11, "TARGET_UNIT_SRC_AREA_UNK_11"],
  [15, "TARGET_UNIT_SRC_AREA_ENEMY"],
  [16, "TARGET_UNIT_DEST_AREA_ENEMY"],
  [17, "TARGET_DEST_DB"],
  [18, "TARGET_DEST_CASTER"],
  [20, "TARGET_UNIT_CASTER_AREA_PARTY"],
  [21, "TARGET_UNIT_TARGET_ALLY"],
  [22, "TARGET_SRC_CASTER"],
  [23, "TARGET_GAMEOBJECT_TARGET"],
  [24, "TARGET_UNIT_CONE_ENEMY_24"],
  [25, "TARGET_UNIT_TARGET_ANY"],
  [26, "TARGET_GAMEOBJECT_ITEM_TARGET"],
  [27, "TARGET_UNIT_MASTER"],
  [28, "TARGET_DEST_DYNOBJ_ENEMY"],
  [29, "TARGET_DEST_DYNOBJ_ALLY"],
  [30, "TARGET_UNIT_SRC_AREA_ALLY"],
  [31, "TARGET_UNIT_DEST_AREA_ALLY"],
  [32, "TARGET_DEST_CASTER_SUMMON"],
  [33, "TARGET_UNIT_SRC_AREA_PARTY"],
  [34, "TARGET_UNIT_DEST_AREA_PARTY"],
  [35, "TARGET_UNIT_TARGET_PARTY"],
  [36, "TARGET_DEST_CASTER_36"],
  [37, "TARGET_UNIT_LASTTARGET_AREA_PARTY"],
  [38, "TARGET_UNIT_NEARBY_ENTRY"],
  [39, "TARGET_DEST_CASTER_FISHING"],
  [40, "TARGET_GAMEOBJECT_NEARBY_ENTRY"],
  [41, "TARGET_DEST_CASTER_FRONT_RIGHT"],
  [42, "TARGET_DEST_CASTER_BACK_RIGHT"],
  [43, "TARGET_DEST_CASTER_BACK_LEFT"],
  [44, "TARGET_DEST_CASTER_FRONT_LEFT"],
  [45, "TARGET_UNIT_TARGET_CHAINHEAL_ALLY"],
  [46, "TARGET_DEST_NEARBY_ENTRY"],
  [47, "TARGET_DEST_CASTER_FRONT"],
  [48, "TARGET_DEST_CASTER_BACK"],
  [49, "TARGET_DEST_CASTER_RIGHT"],
  [50, "TARGET_DEST_CASTER_LEFT"],
  [51, "TARGET_GAMEOBJECT_SRC_AREA"],
  [52, "TARGET_GAMEOBJECT_DEST_AREA"],
  [53, "TARGET_DEST_TARGET_ENEMY"],
  [54, "TARGET_UNIT_CONE_ENEMY_54"],
  [55, "TARGET_DEST_CASTER_FRONT_LEAP"],
  [56, "TARGET_UNIT_CASTER_AREA_RAID"],
  [57, "TARGET_UNIT_TARGET_RAID"],
  [58, "TARGET_UNIT_NEARBY_RAID"],
  [59, "TARGET_UNIT_CONE_ALLY"],
  [60, "TARGET_UNIT_CONE_ENTRY"],
  [61, "TARGET_UNIT_TARGET_AREA_RAID_CLASS"],
  [62, "TARGET_UNK_62"],
  [63, "TARGET_DEST_TARGET_ANY"],
  [64, "TARGET_DEST_TARGET_FRONT"],
  [65, "TARGET_DEST_TARGET_BACK"],
  [66, "TARGET_DEST_TARGET_RIGHT"],
  [67, "TARGET_DEST_TARGET_LEFT"],
  [68, "TARGET_DEST_TARGET_FRONT_RIGHT"],
  [69, "TARGET_DEST_TARGET_BACK_RIGHT"],
  [70, "TARGET_DEST_TARGET_BACK_LEFT"],
  [71, "TARGET_DEST_TARGET_FRONT_LEFT"],
  [72, "TARGET_DEST_CASTER_RANDOM"],
  [73, "TARGET_DEST_CASTER_RADIUS"],
  [74, "TARGET_DEST_TARGET_RANDOM"],
  [75, "TARGET_DEST_TARGET_RADIUS"],
  [76, "TARGET_DEST_CHANNEL_TARGET"],
  [77, "TARGET_UNIT_CHANNEL_TARGET"],
  [78, "TARGET_DEST_DEST_FRONT"],
  [79, "TARGET_DEST_DEST_BACK"],
  [80, "TARGET_DEST_DEST_RIGHT"],
  [81, "TARGET_DEST_DEST_LEFT"],
  [82, "TARGET_DEST_DEST_FRONT_RIGHT"],
  [83, "TARGET_DEST_DEST_BACK_RIGHT"],
  [84, "TARGET_DEST_DEST_BACK_LEFT"],
  [85, "TARGET_DEST_DEST_FRONT_LEFT"],
  [86, "TARGET_DEST_DEST_RANDOM"],
  [87, "TARGET_DEST_DEST"],
  [88, "TARGET_DEST_DYNOBJ_NONE"],
  [89, "TARGET_DEST_TRAJ"],
  [90, "TARGET_UNIT_TARGET_MINIPET"],
  [91, "TARGET_DEST_DEST_RADIUS"],
  [92, "TARGET_UNIT_SUMMONER"],
  [93, "TARGET_CORPSE_SRC_AREA_ENEMY"],
  [94, "TARGET_UNIT_VEHICLE"],
  [95, "TARGET_UNIT_TARGET_PASSENGER"],
  [96, "TARGET_UNIT_PASSENGER_0"],
  [97, "TARGET_UNIT_PASSENGER_1"],
  [98, "TARGET_UNIT_PASSENGER_2"],
  [99, "TARGET_UNIT_PASSENGER_3"],
  [100, "TARGET_UNIT_PASSENGER_4"],
  [101, "TARGET_UNIT_PASSENGER_5"],
  [102, "TARGET_UNIT_PASSENGER_6"],
  [103, "TARGET_UNIT_PASSENGER_7"],
  [104, "TARGET_UNIT_CONE_ENEMY_104"],
  [105, "TARGET_UNIT_UNK_105"],
  [106, "TARGET_DEST_CHANNEL_CASTER"],
  [107, "TARGET_UNK_DEST_AREA_UNK_107"],
  [108, "TARGET_GAMEOBJECT_CONE"],
  [110, "TARGET_DEST_UNK_110"],
]);

// SpellCastResult
export const SPELL_FAILED_SUCCESS = 0;
export const SPELL_FAILED_AFFECTING_COMBAT = 1;
export const SPELL_FAILED_ALREADY_AT_FULL_HEALTH = 2;
export const SPELL_FAILED_ALREADY_AT_FULL_MANA = 3;
export const SPELL_FAILED_ALREADY_AT_FULL_POWER = 4;
export const SPELL_FAILED_ALREADY_BEING_TAMED = 5;
export const SPELL_FAILED_ALREADY_HAVE_CHARM = 6;
export const SPELL_FAILED_ALREADY_HAVE_SUMMON = 7;
export const SPELL_FAILED_ALREADY_OPEN = 8;
export const SPELL_FAILED_AURA_BOUNCED = 9;
export const SPELL_FAILED_AUTOTRACK_INTERRUPTED = 10;
export const SPELL_FAILED_BAD_IMPLICIT_TARGETS = 11;
export const SPELL_FAILED_BAD_TARGETS = 12;
export const SPELL_FAILED_CANT_BE_CHARMED = 13;
export const SPELL_FAILED_CANT_BE_DISENCHANTED = 14;
export const SPELL_FAILED_CANT_BE_DISENCHANTED_SKILL = 15;
export const SPELL_FAILED_CANT_BE_MILLED = 16;
export const SPELL_FAILED_CANT_BE_PROSPECTED = 17;
export const SPELL_FAILED_CANT_CAST_ON_TAPPED = 18;
export const SPELL_FAILED_CANT_DUEL_WHILE_INVISIBLE = 19;
export const SPELL_FAILED_CANT_DUEL_WHILE_STEALTHED = 20;
export const SPELL_FAILED_CANT_STEALTH = 21;
export const SPELL_FAILED_CASTER_AURASTATE = 22;
export const SPELL_FAILED_CASTER_DEAD = 23;
export const SPELL_FAILED_CHARMED = 24;
export const SPELL_FAILED_CHEST_IN_USE = 25;
export const SPELL_FAILED_CONFUSED = 26;
export const SPELL_FAILED_DONT_REPORT = 27;
export const SPELL_FAILED_EQUIPPED_ITEM = 28;
export const SPELL_FAILED_EQUIPPED_ITEM_CLASS = 29;
export const SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND = 30;
export const SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND = 31;
export const SPELL_FAILED_ERROR = 32;
export const SPELL_FAILED_FIZZLE = 33;
export const SPELL_FAILED_FLEEING = 34;
export const SPELL_FAILED_FOOD_LOWLEVEL = 35;
export const SPELL_FAILED_HIGHLEVEL = 36;
export const SPELL_FAILED_HUNGER_SATIATED = 37;
export const SPELL_FAILED_IMMUNE = 38;
export const SPELL_FAILED_INCORRECT_AREA = 39;
export const SPELL_FAILED_INTERRUPTED = 40;
export const SPELL_FAILED_INTERRUPTED_COMBAT = 41;
export const SPELL_FAILED_ITEM_ALREADY_ENCHANTED = 42;
export const SPELL_FAILED_ITEM_GONE = 43;
export const SPELL_FAILED_ITEM_NOT_FOUND = 44;
export const SPELL_FAILED_ITEM_NOT_READY = 45;
export const SPELL_FAILED_LEVEL_REQUIREMENT = 46;
export const SPELL_FAILED_LINE_OF_SIGHT = 47;
export const SPELL_FAILED_LOWLEVEL = 48;
export const SPELL_FAILED_LOW_CASTLEVEL = 49;
export const SPELL_FAILED_MAINHAND_EMPTY = 50;
export const SPELL_FAILED_MOVING = 51;
export const SPELL_FAILED_NEED_AMMO = 52;
export const SPELL_FAILED_NEED_AMMO_POUCH = 53;
export const SPELL_FAILED_NEED_EXOTIC_AMMO = 54;
export const SPELL_FAILED_NEED_MORE_ITEMS = 55;
export const SPELL_FAILED_NOPATH = 56;
export const SPELL_FAILED_NOT_BEHIND = 57;
export const SPELL_FAILED_NOT_FISHABLE = 58;
export const SPELL_FAILED_NOT_FLYING = 59;
export const SPELL_FAILED_NOT_HERE = 60;
export const SPELL_FAILED_NOT_INFRONT = 61;
export const SPELL_FAILED_NOT_IN_CONTROL = 62;
export const SPELL_FAILED_NOT_KNOWN = 63;
export const SPELL_FAILED_NOT_MOUNTED = 64;
export const SPELL_FAILED_NOT_ON_TAXI = 65;
export const SPELL_FAILED_NOT_ON_TRANSPORT = 66;
export const SPELL_FAILED_NOT_READY = 67;
export const SPELL_FAILED_NOT_SHAPESHIFT = 68;
export const SPELL_FAILED_NOT_STANDING = 69;
export const SPELL_FAILED_NOT_TRADEABLE = 70;
export const SPELL_FAILED_NOT_TRADING = 71;
export const SPELL_FAILED_NOT_UNSHEATHED = 72;
export const SPELL_FAILED_NOT_WHILE_GHOST = 73;
export const SPELL_FAILED_NOT_WHILE_LOOTING = 74;
export const SPELL_FAILED_NO_AMMO = 75;
export const SPELL_FAILED_NO_CHARGES_REMAIN = 76;
export const SPELL_FAILED_NO_CHAMPION = 77;
export const SPELL_FAILED_NO_COMBO_POINTS = 78;
export const SPELL_FAILED_NO_DUELING = 79;
export const SPELL_FAILED_NO_ENDURANCE = 80;
export const SPELL_FAILED_NO_FISH = 81;
export const SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED = 82;
export const SPELL_FAILED_NO_MOUNTS_ALLOWED = 83;
export const SPELL_FAILED_NO_PET = 84;
export const SPELL_FAILED_NO_POWER = 85;
export const SPELL_FAILED_NOTHING_TO_DISPEL = 86;
export const SPELL_FAILED_NOTHING_TO_STEAL = 87;
export const SPELL_FAILED_ONLY_ABOVEWATER = 88;
export const SPELL_FAILED_ONLY_DAYTIME = 89;
export const SPELL_FAILED_ONLY_INDOORS = 90;
export const SPELL_FAILED_ONLY_MOUNTED = 91;
export const SPELL_FAILED_ONLY_NIGHTTIME = 92;
export const SPELL_FAILED_ONLY_OUTDOORS = 93;
export const SPELL_FAILED_ONLY_SHAPESHIFT = 94;
export const SPELL_FAILED_ONLY_STEALTHED = 95;
export const SPELL_FAILED_ONLY_UNDERWATER = 96;
export const SPELL_FAILED_OUT_OF_RANGE = 97;
export const SPELL_FAILED_PACIFIED = 98;
export const SPELL_FAILED_POSSESSED = 99;
export const SPELL_FAILED_REAGENTS = 100;
export const SPELL_FAILED_REQUIRES_AREA = 101;
export const SPELL_FAILED_REQUIRES_SPELL_FOCUS = 102;
export const SPELL_FAILED_ROOTED = 103;
export const SPELL_FAILED_SILENCED = 104;
export const SPELL_FAILED_SPELL_IN_PROGRESS = 105;
export const SPELL_FAILED_SPELL_LEARNED = 106;
export const SPELL_FAILED_SPELL_UNAVAILABLE = 107;
export const SPELL_FAILED_STUNNED = 108;
export const SPELL_FAILED_TARGETS_DEAD = 109;
export const SPELL_FAILED_TARGET_AFFECTING_COMBAT = 110;
export const SPELL_FAILED_TARGET_AURASTATE = 111;
export const SPELL_FAILED_TARGET_DUELING = 112;
export const SPELL_FAILED_TARGET_ENEMY = 113;
export const SPELL_FAILED_TARGET_ENRAGED = 114;
export const SPELL_FAILED_TARGET_FRIENDLY = 115;
export const SPELL_FAILED_TARGET_IN_COMBAT = 116;
export const SPELL_FAILED_TARGET_IS_PLAYER = 117;
export const SPELL_FAILED_TARGET_IS_PLAYER_CONTROLLED = 118;
export const SPELL_FAILED_TARGET_NOT_DEAD = 119;
export const SPELL_FAILED_TARGET_NOT_IN_PARTY = 120;
export const SPELL_FAILED_TARGET_NOT_LOOTED = 121;
export const SPELL_FAILED_TARGET_NOT_PLAYER = 122;
export const SPELL_FAILED_TARGET_NO_POCKETS = 123;
export const SPELL_FAILED_TARGET_NO_WEAPONS = 124;
export const SPELL_FAILED_TARGET_NO_RANGED_WEAPONS = 125;
export const SPELL_FAILED_TARGET_UNSKINNABLE = 126;
export const SPELL_FAILED_THIRST_SATIATED = 127;
export const SPELL_FAILED_TOO_CLOSE = 128;
export const SPELL_FAILED_TOO_MANY_OF_ITEM = 129;
export const SPELL_FAILED_TOTEM_CATEGORY = 130;
export const SPELL_FAILED_TOTEMS = 131;
export const SPELL_FAILED_TRY_AGAIN = 132;
export const SPELL_FAILED_UNIT_NOT_BEHIND = 133;
export const SPELL_FAILED_UNIT_NOT_INFRONT = 134;
export const SPELL_FAILED_WRONG_PET_FOOD = 135;
export const SPELL_FAILED_NOT_WHILE_FATIGUED = 136;
export const SPELL_FAILED_TARGET_NOT_IN_INSTANCE = 137;
export const SPELL_FAILED_NOT_WHILE_TRADING = 138;
export const SPELL_FAILED_TARGET_NOT_IN_RAID = 139;
export const SPELL_FAILED_TARGET_FREEFORALL = 140;
export const SPELL_FAILED_NO_EDIBLE_CORPSES = 141;
export const SPELL_FAILED_ONLY_BATTLEGROUNDS = 142;
export const SPELL_FAILED_TARGET_NOT_GHOST = 143;
export const SPELL_FAILED_TRANSFORM_UNUSABLE = 144;
export const SPELL_FAILED_WRONG_WEATHER = 145;
export const SPELL_FAILED_DAMAGE_IMMUNE = 146;
export const SPELL_FAILED_PREVENTED_BY_MECHANIC = 147;
export const SPELL_FAILED_PLAY_TIME = 148;
export const SPELL_FAILED_REPUTATION = 149;
export const SPELL_FAILED_MIN_SKILL = 150;
export const SPELL_FAILED_NOT_IN_ARENA = 151;
export const SPELL_FAILED_NOT_ON_SHAPESHIFT = 152;
export const SPELL_FAILED_NOT_ON_STEALTHED = 153;
export const SPELL_FAILED_NOT_ON_DAMAGE_IMMUNE = 154;
export const SPELL_FAILED_NOT_ON_MOUNTED = 155;
export const SPELL_FAILED_TOO_SHALLOW = 156;
export const SPELL_FAILED_TARGET_NOT_IN_SANCTUARY = 157;
export const SPELL_FAILED_TARGET_IS_TRIVIAL = 158;
export const SPELL_FAILED_BM_OR_INVISGOD = 159;
export const SPELL_FAILED_EXPERT_RIDING_REQUIREMENT = 160;
export const SPELL_FAILED_ARTISAN_RIDING_REQUIREMENT = 161;
export const SPELL_FAILED_NOT_IDLE = 162;
export const SPELL_FAILED_NOT_INACTIVE = 163;
export const SPELL_FAILED_PARTIAL_PLAYTIME = 164;
export const SPELL_FAILED_NO_PLAYTIME = 165;
export const SPELL_FAILED_NOT_IN_BATTLEGROUND = 166;
export const SPELL_FAILED_NOT_IN_RAID_INSTANCE = 167;
export const SPELL_FAILED_ONLY_IN_ARENA = 168;
export const SPELL_FAILED_TARGET_LOCKED_TO_RAID_INSTANCE = 169;
export const SPELL_FAILED_ON_USE_ENCHANT = 170;
export const SPELL_FAILED_NOT_ON_GROUND = 171;
export const SPELL_FAILED_CUSTOM_ERROR = 172;
export const SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW = 173;
export const SPELL_FAILED_TOO_MANY_SOCKETS = 174;
export const SPELL_FAILED_INVALID_GLYPH = 175;
export const SPELL_FAILED_UNIQUE_GLYPH = 176;
export const SPELL_FAILED_GLYPH_SOCKET_LOCKED = 177;
export const SPELL_FAILED_NO_VALID_TARGETS = 178;
export const SPELL_FAILED_ITEM_AT_MAX_CHARGES = 179;
export const SPELL_FAILED_NOT_IN_BARBERSHOP = 180;
export const SPELL_FAILED_FISHING_TOO_LOW = 181;
export const SPELL_FAILED_ITEM_ENCHANT_TRADE_WINDOW = 182;
export const SPELL_FAILED_SUMMON_PENDING = 183;
export const SPELL_FAILED_MAX_SOCKETS = 184;
export const SPELL_FAILED_PET_CAN_RENAME = 185;
export const SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED = 186;
export const SPELL_FAILED_UNKNOWN = 187;
export const SPELL_CAST_OK = 255;
export const CAST_RESULT_NAMES: ReadonlyMap<number, string> = new Map([
  [0, "SPELL_FAILED_SUCCESS"],
  [1, "SPELL_FAILED_AFFECTING_COMBAT"],
  [2, "SPELL_FAILED_ALREADY_AT_FULL_HEALTH"],
  [3, "SPELL_FAILED_ALREADY_AT_FULL_MANA"],
  [4, "SPELL_FAILED_ALREADY_AT_FULL_POWER"],
  [5, "SPELL_FAILED_ALREADY_BEING_TAMED"],
  [6, "SPELL_FAILED_ALREADY_HAVE_CHARM"],
  [7, "SPELL_FAILED_ALREADY_HAVE_SUMMON"],
  [8, "SPELL_FAILED_ALREADY_OPEN"],
  [9, "SPELL_FAILED_AURA_BOUNCED"],
  [10, "SPELL_FAILED_AUTOTRACK_INTERRUPTED"],
  [11, "SPELL_FAILED_BAD_IMPLICIT_TARGETS"],
  [12, "SPELL_FAILED_BAD_TARGETS"],
  [13, "SPELL_FAILED_CANT_BE_CHARMED"],
  [14, "SPELL_FAILED_CANT_BE_DISENCHANTED"],
  [15, "SPELL_FAILED_CANT_BE_DISENCHANTED_SKILL"],
  [16, "SPELL_FAILED_CANT_BE_MILLED"],
  [17, "SPELL_FAILED_CANT_BE_PROSPECTED"],
  [18, "SPELL_FAILED_CANT_CAST_ON_TAPPED"],
  [19, "SPELL_FAILED_CANT_DUEL_WHILE_INVISIBLE"],
  [20, "SPELL_FAILED_CANT_DUEL_WHILE_STEALTHED"],
  [21, "SPELL_FAILED_CANT_STEALTH"],
  [22, "SPELL_FAILED_CASTER_AURASTATE"],
  [23, "SPELL_FAILED_CASTER_DEAD"],
  [24, "SPELL_FAILED_CHARMED"],
  [25, "SPELL_FAILED_CHEST_IN_USE"],
  [26, "SPELL_FAILED_CONFUSED"],
  [27, "SPELL_FAILED_DONT_REPORT"],
  [28, "SPELL_FAILED_EQUIPPED_ITEM"],
  [29, "SPELL_FAILED_EQUIPPED_ITEM_CLASS"],
  [30, "SPELL_FAILED_EQUIPPED_ITEM_CLASS_MAINHAND"],
  [31, "SPELL_FAILED_EQUIPPED_ITEM_CLASS_OFFHAND"],
  [32, "SPELL_FAILED_ERROR"],
  [33, "SPELL_FAILED_FIZZLE"],
  [34, "SPELL_FAILED_FLEEING"],
  [35, "SPELL_FAILED_FOOD_LOWLEVEL"],
  [36, "SPELL_FAILED_HIGHLEVEL"],
  [37, "SPELL_FAILED_HUNGER_SATIATED"],
  [38, "SPELL_FAILED_IMMUNE"],
  [39, "SPELL_FAILED_INCORRECT_AREA"],
  [40, "SPELL_FAILED_INTERRUPTED"],
  [41, "SPELL_FAILED_INTERRUPTED_COMBAT"],
  [42, "SPELL_FAILED_ITEM_ALREADY_ENCHANTED"],
  [43, "SPELL_FAILED_ITEM_GONE"],
  [44, "SPELL_FAILED_ITEM_NOT_FOUND"],
  [45, "SPELL_FAILED_ITEM_NOT_READY"],
  [46, "SPELL_FAILED_LEVEL_REQUIREMENT"],
  [47, "SPELL_FAILED_LINE_OF_SIGHT"],
  [48, "SPELL_FAILED_LOWLEVEL"],
  [49, "SPELL_FAILED_LOW_CASTLEVEL"],
  [50, "SPELL_FAILED_MAINHAND_EMPTY"],
  [51, "SPELL_FAILED_MOVING"],
  [52, "SPELL_FAILED_NEED_AMMO"],
  [53, "SPELL_FAILED_NEED_AMMO_POUCH"],
  [54, "SPELL_FAILED_NEED_EXOTIC_AMMO"],
  [55, "SPELL_FAILED_NEED_MORE_ITEMS"],
  [56, "SPELL_FAILED_NOPATH"],
  [57, "SPELL_FAILED_NOT_BEHIND"],
  [58, "SPELL_FAILED_NOT_FISHABLE"],
  [59, "SPELL_FAILED_NOT_FLYING"],
  [60, "SPELL_FAILED_NOT_HERE"],
  [61, "SPELL_FAILED_NOT_INFRONT"],
  [62, "SPELL_FAILED_NOT_IN_CONTROL"],
  [63, "SPELL_FAILED_NOT_KNOWN"],
  [64, "SPELL_FAILED_NOT_MOUNTED"],
  [65, "SPELL_FAILED_NOT_ON_TAXI"],
  [66, "SPELL_FAILED_NOT_ON_TRANSPORT"],
  [67, "SPELL_FAILED_NOT_READY"],
  [68, "SPELL_FAILED_NOT_SHAPESHIFT"],
  [69, "SPELL_FAILED_NOT_STANDING"],
  [70, "SPELL_FAILED_NOT_TRADEABLE"],
  [71, "SPELL_FAILED_NOT_TRADING"],
  [72, "SPELL_FAILED_NOT_UNSHEATHED"],
  [73, "SPELL_FAILED_NOT_WHILE_GHOST"],
  [74, "SPELL_FAILED_NOT_WHILE_LOOTING"],
  [75, "SPELL_FAILED_NO_AMMO"],
  [76, "SPELL_FAILED_NO_CHARGES_REMAIN"],
  [77, "SPELL_FAILED_NO_CHAMPION"],
  [78, "SPELL_FAILED_NO_COMBO_POINTS"],
  [79, "SPELL_FAILED_NO_DUELING"],
  [80, "SPELL_FAILED_NO_ENDURANCE"],
  [81, "SPELL_FAILED_NO_FISH"],
  [82, "SPELL_FAILED_NO_ITEMS_WHILE_SHAPESHIFTED"],
  [83, "SPELL_FAILED_NO_MOUNTS_ALLOWED"],
  [84, "SPELL_FAILED_NO_PET"],
  [85, "SPELL_FAILED_NO_POWER"],
  [86, "SPELL_FAILED_NOTHING_TO_DISPEL"],
  [87, "SPELL_FAILED_NOTHING_TO_STEAL"],
  [88, "SPELL_FAILED_ONLY_ABOVEWATER"],
  [89, "SPELL_FAILED_ONLY_DAYTIME"],
  [90, "SPELL_FAILED_ONLY_INDOORS"],
  [91, "SPELL_FAILED_ONLY_MOUNTED"],
  [92, "SPELL_FAILED_ONLY_NIGHTTIME"],
  [93, "SPELL_FAILED_ONLY_OUTDOORS"],
  [94, "SPELL_FAILED_ONLY_SHAPESHIFT"],
  [95, "SPELL_FAILED_ONLY_STEALTHED"],
  [96, "SPELL_FAILED_ONLY_UNDERWATER"],
  [97, "SPELL_FAILED_OUT_OF_RANGE"],
  [98, "SPELL_FAILED_PACIFIED"],
  [99, "SPELL_FAILED_POSSESSED"],
  [100, "SPELL_FAILED_REAGENTS"],
  [101, "SPELL_FAILED_REQUIRES_AREA"],
  [102, "SPELL_FAILED_REQUIRES_SPELL_FOCUS"],
  [103, "SPELL_FAILED_ROOTED"],
  [104, "SPELL_FAILED_SILENCED"],
  [105, "SPELL_FAILED_SPELL_IN_PROGRESS"],
  [106, "SPELL_FAILED_SPELL_LEARNED"],
  [107, "SPELL_FAILED_SPELL_UNAVAILABLE"],
  [108, "SPELL_FAILED_STUNNED"],
  [109, "SPELL_FAILED_TARGETS_DEAD"],
  [110, "SPELL_FAILED_TARGET_AFFECTING_COMBAT"],
  [111, "SPELL_FAILED_TARGET_AURASTATE"],
  [112, "SPELL_FAILED_TARGET_DUELING"],
  [113, "SPELL_FAILED_TARGET_ENEMY"],
  [114, "SPELL_FAILED_TARGET_ENRAGED"],
  [115, "SPELL_FAILED_TARGET_FRIENDLY"],
  [116, "SPELL_FAILED_TARGET_IN_COMBAT"],
  [117, "SPELL_FAILED_TARGET_IS_PLAYER"],
  [118, "SPELL_FAILED_TARGET_IS_PLAYER_CONTROLLED"],
  [119, "SPELL_FAILED_TARGET_NOT_DEAD"],
  [120, "SPELL_FAILED_TARGET_NOT_IN_PARTY"],
  [121, "SPELL_FAILED_TARGET_NOT_LOOTED"],
  [122, "SPELL_FAILED_TARGET_NOT_PLAYER"],
  [123, "SPELL_FAILED_TARGET_NO_POCKETS"],
  [124, "SPELL_FAILED_TARGET_NO_WEAPONS"],
  [125, "SPELL_FAILED_TARGET_NO_RANGED_WEAPONS"],
  [126, "SPELL_FAILED_TARGET_UNSKINNABLE"],
  [127, "SPELL_FAILED_THIRST_SATIATED"],
  [128, "SPELL_FAILED_TOO_CLOSE"],
  [129, "SPELL_FAILED_TOO_MANY_OF_ITEM"],
  [130, "SPELL_FAILED_TOTEM_CATEGORY"],
  [131, "SPELL_FAILED_TOTEMS"],
  [132, "SPELL_FAILED_TRY_AGAIN"],
  [133, "SPELL_FAILED_UNIT_NOT_BEHIND"],
  [134, "SPELL_FAILED_UNIT_NOT_INFRONT"],
  [135, "SPELL_FAILED_WRONG_PET_FOOD"],
  [136, "SPELL_FAILED_NOT_WHILE_FATIGUED"],
  [137, "SPELL_FAILED_TARGET_NOT_IN_INSTANCE"],
  [138, "SPELL_FAILED_NOT_WHILE_TRADING"],
  [139, "SPELL_FAILED_TARGET_NOT_IN_RAID"],
  [140, "SPELL_FAILED_TARGET_FREEFORALL"],
  [141, "SPELL_FAILED_NO_EDIBLE_CORPSES"],
  [142, "SPELL_FAILED_ONLY_BATTLEGROUNDS"],
  [143, "SPELL_FAILED_TARGET_NOT_GHOST"],
  [144, "SPELL_FAILED_TRANSFORM_UNUSABLE"],
  [145, "SPELL_FAILED_WRONG_WEATHER"],
  [146, "SPELL_FAILED_DAMAGE_IMMUNE"],
  [147, "SPELL_FAILED_PREVENTED_BY_MECHANIC"],
  [148, "SPELL_FAILED_PLAY_TIME"],
  [149, "SPELL_FAILED_REPUTATION"],
  [150, "SPELL_FAILED_MIN_SKILL"],
  [151, "SPELL_FAILED_NOT_IN_ARENA"],
  [152, "SPELL_FAILED_NOT_ON_SHAPESHIFT"],
  [153, "SPELL_FAILED_NOT_ON_STEALTHED"],
  [154, "SPELL_FAILED_NOT_ON_DAMAGE_IMMUNE"],
  [155, "SPELL_FAILED_NOT_ON_MOUNTED"],
  [156, "SPELL_FAILED_TOO_SHALLOW"],
  [157, "SPELL_FAILED_TARGET_NOT_IN_SANCTUARY"],
  [158, "SPELL_FAILED_TARGET_IS_TRIVIAL"],
  [159, "SPELL_FAILED_BM_OR_INVISGOD"],
  [160, "SPELL_FAILED_EXPERT_RIDING_REQUIREMENT"],
  [161, "SPELL_FAILED_ARTISAN_RIDING_REQUIREMENT"],
  [162, "SPELL_FAILED_NOT_IDLE"],
  [163, "SPELL_FAILED_NOT_INACTIVE"],
  [164, "SPELL_FAILED_PARTIAL_PLAYTIME"],
  [165, "SPELL_FAILED_NO_PLAYTIME"],
  [166, "SPELL_FAILED_NOT_IN_BATTLEGROUND"],
  [167, "SPELL_FAILED_NOT_IN_RAID_INSTANCE"],
  [168, "SPELL_FAILED_ONLY_IN_ARENA"],
  [169, "SPELL_FAILED_TARGET_LOCKED_TO_RAID_INSTANCE"],
  [170, "SPELL_FAILED_ON_USE_ENCHANT"],
  [171, "SPELL_FAILED_NOT_ON_GROUND"],
  [172, "SPELL_FAILED_CUSTOM_ERROR"],
  [173, "SPELL_FAILED_CANT_DO_THAT_RIGHT_NOW"],
  [174, "SPELL_FAILED_TOO_MANY_SOCKETS"],
  [175, "SPELL_FAILED_INVALID_GLYPH"],
  [176, "SPELL_FAILED_UNIQUE_GLYPH"],
  [177, "SPELL_FAILED_GLYPH_SOCKET_LOCKED"],
  [178, "SPELL_FAILED_NO_VALID_TARGETS"],
  [179, "SPELL_FAILED_ITEM_AT_MAX_CHARGES"],
  [180, "SPELL_FAILED_NOT_IN_BARBERSHOP"],
  [181, "SPELL_FAILED_FISHING_TOO_LOW"],
  [182, "SPELL_FAILED_ITEM_ENCHANT_TRADE_WINDOW"],
  [183, "SPELL_FAILED_SUMMON_PENDING"],
  [184, "SPELL_FAILED_MAX_SOCKETS"],
  [185, "SPELL_FAILED_PET_CAN_RENAME"],
  [186, "SPELL_FAILED_TARGET_CANNOT_BE_RESURRECTED"],
  [187, "SPELL_FAILED_UNKNOWN"],
  [255, "SPELL_CAST_OK"],
]);

// SpellMissInfo
export const SPELL_MISS_NONE = 0;
export const SPELL_MISS_MISS = 1;
export const SPELL_MISS_RESIST = 2;
export const SPELL_MISS_DODGE = 3;
export const SPELL_MISS_PARRY = 4;
export const SPELL_MISS_BLOCK = 5;
export const SPELL_MISS_EVADE = 6;
export const SPELL_MISS_IMMUNE = 7;
export const SPELL_MISS_IMMUNE2 = 8;
export const SPELL_MISS_DEFLECT = 9;
export const SPELL_MISS_ABSORB = 10;
export const SPELL_MISS_REFLECT = 11;
export const MISS_NAMES: ReadonlyMap<number, string> = new Map([
  [0, "SPELL_MISS_NONE"],
  [1, "SPELL_MISS_MISS"],
  [2, "SPELL_MISS_RESIST"],
  [3, "SPELL_MISS_DODGE"],
  [4, "SPELL_MISS_PARRY"],
  [5, "SPELL_MISS_BLOCK"],
  [6, "SPELL_MISS_EVADE"],
  [7, "SPELL_MISS_IMMUNE"],
  [8, "SPELL_MISS_IMMUNE2"],
  [9, "SPELL_MISS_DEFLECT"],
  [10, "SPELL_MISS_ABSORB"],
  [11, "SPELL_MISS_REFLECT"],
]);

// SpellAttr0
export const SPELL_ATTR0_PROC_FAILURE_BURNS_CHARGE = 0x1;
export const SPELL_ATTR0_USES_RANGED_SLOT = 0x2;
export const SPELL_ATTR0_ON_NEXT_SWING_NO_DAMAGE = 0x4;
export const SPELL_ATTR0_DO_NOT_LOG_IMMUNE_MISSES = 0x8;
export const SPELL_ATTR0_IS_ABILITY = 0x10;
export const SPELL_ATTR0_IS_TRADESKILL = 0x20;
export const SPELL_ATTR0_PASSIVE = 0x40;
export const SPELL_ATTR0_DO_NOT_DISPLAY = 0x80;
export const SPELL_ATTR0_DO_NOT_LOG = 0x100;
export const SPELL_ATTR0_HELD_ITEM_ONLY = 0x200;
export const SPELL_ATTR0_ON_NEXT_SWING = 0x400;
export const SPELL_ATTR0_WEARER_CASTS_PROC_TRIGGER = 0x800;
export const SPELL_ATTR0_SERVER_ONLY = 0x1000;
export const SPELL_ATTR0_ALLOW_ITEM_SPELL_IN_PVP = 0x2000;
export const SPELL_ATTR0_ONLY_INDOORS = 0x4000;
export const SPELL_ATTR0_ONLY_OUTDOORS = 0x8000;
export const SPELL_ATTR0_NOT_SHAPESHIFTED = 0x10000;
export const SPELL_ATTR0_ONLY_STEALTHED = 0x20000;
export const SPELL_ATTR0_DO_NOT_SHEATH = 0x40000;
export const SPELL_ATTR0_SCALES_WITH_CREATURE_LEVEL = 0x80000;
export const SPELL_ATTR0_CANCELS_AUTO_ATTACK_COMBAT = 0x100000;
export const SPELL_ATTR0_NO_ACTIVE_DEFENSE = 0x200000;
export const SPELL_ATTR0_TRACK_TARGET_IN_CAST_PLAYER_ONLY = 0x400000;
export const SPELL_ATTR0_ALLOW_CAST_WHILE_DEAD = 0x800000;
export const SPELL_ATTR0_ALLOW_WHILE_MOUNTED = 0x1000000;
export const SPELL_ATTR0_COOLDOWN_ON_EVENT = 0x2000000;
export const SPELL_ATTR0_AURA_IS_DEBUFF = 0x4000000;
export const SPELL_ATTR0_ALLOW_WHILE_SITTING = 0x8000000;
export const SPELL_ATTR0_NOT_IN_COMBAT_ONLY_PEACEFUL = 0x10000000;
export const SPELL_ATTR0_NO_IMMUNITIES = 0x20000000;
export const SPELL_ATTR0_HEARTBEAT_RESIST = 0x40000000;
export const SPELL_ATTR0_NO_AURA_CANCEL = 0x80000000;

// SpellAttr1
export const SPELL_ATTR1_DISMISS_PET_FIRST = 0x1;
export const SPELL_ATTR1_USE_ALL_MANA = 0x2;
export const SPELL_ATTR1_IS_CHANNELED = 0x4;
export const SPELL_ATTR1_NO_REDIRECTION = 0x8;
export const SPELL_ATTR1_NO_SKILL_INCREASE = 0x10;
export const SPELL_ATTR1_ALLOW_WHILE_STEALTHED = 0x20;
export const SPELL_ATTR1_IS_SELF_CHANNELED = 0x40;
export const SPELL_ATTR1_NO_REFLECTION = 0x80;
export const SPELL_ATTR1_ONLY_PEACEFUL_TARGETS = 0x100;
export const SPELL_ATTR1_INITIATE_COMBAT = 0x200;
export const SPELL_ATTR1_NO_THREAT = 0x400;
export const SPELL_ATTR1_AURA_UNIQUE = 0x800;
export const SPELL_ATTR1_FAILURE_BREAKS_STEALTH = 0x1000;
export const SPELL_ATTR1_TOGGLE_FAR_SIGHT = 0x2000;
export const SPELL_ATTR1_TRACK_TARGET_IN_CHANNEL = 0x4000;
export const SPELL_ATTR1_IMMUNITY_PURGES_EFFECT = 0x8000;
export const SPELL_ATTR1_IMMUNITY_TO_HOSTILE_AND_FRIENDLY_EFFECTS = 0x10000;
export const SPELL_ATTR1_NO_AUTOCAST_AI = 0x20000;
export const SPELL_ATTR1_PREVENTS_ANIM = 0x40000;
export const SPELL_ATTR1_EXCLUDE_CASTER = 0x80000;
export const SPELL_ATTR1_FINISHING_MOVE_DAMAGE = 0x100000;
export const SPELL_ATTR1_THREAT_ONLY_ON_MISS = 0x200000;
export const SPELL_ATTR1_FINISHING_MOVE_DURATION = 0x400000;
export const SPELL_ATTR1_IGNORE_OWNERS_DEATH = 0x800000;
export const SPELL_ATTR1_SPECIAL_SKILLUP = 0x1000000;
export const SPELL_ATTR1_AURA_STAYS_AFTER_COMBAT = 0x2000000;
export const SPELL_ATTR1_REQUIRE_ALL_TARGETS = 0x4000000;
export const SPELL_ATTR1_DISCOUNT_POWER_ON_MISS = 0x8000000;
export const SPELL_ATTR1_NO_AURA_ICON = 0x10000000;
export const SPELL_ATTR1_NAME_IN_CHANNEL_BAR = 0x20000000;
export const SPELL_ATTR1_COMBO_ON_BLOCK = 0x40000000;
export const SPELL_ATTR1_CAST_WHEN_LEARNED = 0x80000000;

// SpellAttr2
export const SPELL_ATTR2_ALLOW_DEAD_TARGET = 0x1;
export const SPELL_ATTR2_NO_SHAPESHIFT_UI = 0x2;
export const SPELL_ATTR2_IGNORE_LINE_OF_SIGHT = 0x4;
export const SPELL_ATTR2_ALLOW_LOW_LEVEL_BUFF = 0x8;
export const SPELL_ATTR2_USE_SHAPESHIFT_BAR = 0x10;
export const SPELL_ATTR2_AUTO_REPEAT = 0x20;
export const SPELL_ATTR2_CANNOT_CAST_ON_TAPPED = 0x40;
export const SPELL_ATTR2_DO_NOT_REPORT_SPELL_FAILURE = 0x80;
export const SPELL_ATTR2_INCLUDE_IN_ADVANCED_COMBAT_LOG = 0x100;
export const SPELL_ATTR2_ALWAYS_CAST_AS_UNIT = 0x200;
export const SPELL_ATTR2_SPECIAL_TAMING_FLAG = 0x400;
export const SPELL_ATTR2_NO_TARGET_PER_SECOND_COST = 0x800;
export const SPELL_ATTR2_CHAIN_FROM_CASTER = 0x1000;
export const SPELL_ATTR2_ENCHANT_OWN_ITEM_ONLY = 0x2000;
export const SPELL_ATTR2_ALLOW_WHILE_INVISIBLE = 0x4000;
export const SPELL_ATTR2_DO_NOT_CONSUME_IF_GAINED_DURING_CAST = 0x8000;
export const SPELL_ATTR2_NO_ACTIVE_PETS = 0x10000;
export const SPELL_ATTR2_DO_NOT_RESET_COMBAT_TIMERS = 0x20000;
export const SPELL_ATTR2_NO_JUMP_WHILE_CAST_PENDING = 0x40000;
export const SPELL_ATTR2_ALLOW_WHILE_NOT_SHAPESHIFTED = 0x80000;
export const SPELL_ATTR2_INITIATE_COMBAT_POST_CAST = 0x100000;
export const SPELL_ATTR2_FAIL_ON_ALL_TARGETS_IMMUNE = 0x200000;
export const SPELL_ATTR2_NO_INITIAL_THREAD = 0x400000;
export const SPELL_ATTR2_PROC_COOLDOWN_ON_FAILURE = 0x800000;
export const SPELL_ATTR2_ITEM_CAST_WITH_OWNER_SKILL = 0x1000000;
export const SPELL_ATTR2_DONT_BLOCK_MANA_REGEN = 0x2000000;
export const SPELL_ATTR2_NO_SCHOOL_IMMUNITIES = 0x4000000;
export const SPELL_ATTR2_IGNORE_WEAPONSKILL = 0x8000000;
export const SPELL_ATTR2_NOT_AN_ACTION = 0x10000000;
export const SPELL_ATTR2_CANT_CRIT = 0x20000000;
export const SPELL_ATTR2_ACTIVE_THREAT = 0x40000000;
export const SPELL_ATTR2_RETAIN_ITEM_CAST = 0x80000000;

// SpellAttr3
export const SPELL_ATTR3_PVP_ENABLING = 0x1;
export const SPELL_ATTR3_NO_PROC_EQUIP_REQUIREMENT = 0x2;
export const SPELL_ATTR3_NO_CASTING_BAR_TEXT = 0x4;
export const SPELL_ATTR3_COMPLETELY_BLOCKED = 0x8;
export const SPELL_ATTR3_NO_RES_TIMER = 0x10;
export const SPELL_ATTR3_NO_DURABILITY_LOSS = 0x20;
export const SPELL_ATTR3_NO_AVOIDANCE = 0x40;
export const SPELL_ATTR3_DOT_STACKING_RULE = 0x80;
export const SPELL_ATTR3_ONLY_ON_PLAYER = 0x100;
export const SPELL_ATTR3_NOT_A_PROC = 0x200;
export const SPELL_ATTR3_REQUIRES_MAIN_HAND_WEAPON = 0x400;
export const SPELL_ATTR3_ONLY_BATTLEGROUNDS = 0x800;
export const SPELL_ATTR3_ONLY_ON_GHOSTS = 0x1000;
export const SPELL_ATTR3_HIDE_CHANNEL_BAR = 0x2000;
export const SPELL_ATTR3_HIDE_IN_RAID_FILTER = 0x4000;
export const SPELL_ATTR3_NORMAL_RANGED_ATTACK = 0x8000;
export const SPELL_ATTR3_SUPPRESS_CASTER_PROCS = 0x10000;
export const SPELL_ATTR3_SUPPRESS_TARGET_PROCS = 0x20000;
export const SPELL_ATTR3_ALWAYS_HIT = 0x40000;
export const SPELL_ATTR3_INSTANT_TARGET_PROCS = 0x80000;
export const SPELL_ATTR3_ALLOW_AURA_WHILE_DEAD = 0x100000;
export const SPELL_ATTR3_ONLY_PROC_OUTDOORS = 0x200000;
export const SPELL_ATTR3_CASTING_CANCELS_AUTOREPEAT = 0x400000;
export const SPELL_ATTR3_NO_DAMAGE_HISTORY = 0x800000;
export const SPELL_ATTR3_REQUIRES_OFF_HAND_WEAPON = 0x1000000;
export const SPELL_ATTR3_TREAT_AS_PERIODIC = 0x2000000;
export const SPELL_ATTR3_CAN_PROC_FROM_PROCS = 0x4000000;
export const SPELL_ATTR3_ONLY_PROC_ON_CASTER = 0x8000000;
export const SPELL_ATTR3_IGNORE_CASTER_AND_TARGET_RESTRICTIONS = 0x10000000;
export const SPELL_ATTR3_IGNORE_CASTER_MODIFIERS = 0x20000000;
export const SPELL_ATTR3_DO_NOT_DISPLAY_RANGE = 0x40000000;
export const SPELL_ATTR3_NOT_ON_AOE_IMMUNE = 0x80000000;

// SpellAttr4
export const SPELL_ATTR4_NO_CAST_LOG = 0x1;
export const SPELL_ATTR4_CLASS_TRIGGER_ONLY_ON_TARGET = 0x2;
export const SPELL_ATTR4_AURA_EXPIRES_OFFLINE = 0x4;
export const SPELL_ATTR4_NO_HELPFUL_THREAT = 0x8;
export const SPELL_ATTR4_NO_HARMFUL_THREAT = 0x10;
export const SPELL_ATTR4_ALLOW_CLIENT_TARGETING = 0x20;
export const SPELL_ATTR4_CANNOT_BE_STOLEN = 0x40;
export const SPELL_ATTR4_ALLOW_CAST_WHILE_CASTING = 0x80;
export const SPELL_ATTR4_IGNORE_DAMAGE_TAKEN_MODIFIERS = 0x100;
export const SPELL_ATTR4_COMBAT_FEEDBACK_WHEN_USABLE = 0x200;
export const SPELL_ATTR4_WEAPON_SPEED_COST_SCALING = 0x400;
export const SPELL_ATTR4_NO_PARTIAL_IMMUNITY = 0x800;
export const SPELL_ATTR4_AURA_IS_BUFF = 0x1000;
export const SPELL_ATTR4_DO_NOT_LOG_CASTER = 0x2000;
export const SPELL_ATTR4_DAMAGE_DOESNT_BREAK_AURAS = 0x4000;
export const SPELL_ATTR4_NOT_IN_SPELLBOOK = 0x8000;
export const SPELL_ATTR4_NOT_IN_ARENA_OR_RATED_BATTLEGROUND = 0x10000;
export const SPELL_ATTR4_IGNORE_DEFAULT_ARENA_RESTRICTIONS = 0x20000;
export const SPELL_ATTR4_BOUNCY_CHAIN_MISSILES = 0x40000;
export const SPELL_ATTR4_ALLOW_PROC_WHILE_SITTING = 0x80000;
export const SPELL_ATTR4_AURA_NEVER_BOUNCES = 0x100000;
export const SPELL_ATTR4_ALLOW_ENETRING_ARENA = 0x200000;
export const SPELL_ATTR4_PROC_SUPPRESS_SWING_ANIM = 0x400000;
export const SPELL_ATTR4_SUPPRESS_WEAPON_PROCS = 0x800000;
export const SPELL_ATTR4_AUTO_RANGED_COMBAT = 0x1000000;
export const SPELL_ATTR4_OWNER_POWER_SCALING = 0x2000000;
export const SPELL_ATTR4_ONLY_FLYING_AREAS = 0x4000000;
export const SPELL_ATTR4_FORCE_DISPLAY_CASTBAR = 0x8000000;
export const SPELL_ATTR4_IGNORE_COMBAT_TIMERS = 0x10000000;
export const SPELL_ATTR4_AURA_BOUNCE_FAILS_SPELL = 0x20000000;
export const SPELL_ATTR4_OBSOLETE = 0x40000000;
export const SPELL_ATTR4_USE_FACING_FROM_SPELL = 0x80000000;

// SpellAttr5
export const SPELL_ATTR5_ALLOW_ACTION_DURING_CHANNEL = 0x1;
export const SPELL_ATTR5_NO_REAGENT_COST_WITH_AURA = 0x2;
export const SPELL_ATTR5_REMOVE_ENTERING_ARENA = 0x4;
export const SPELL_ATTR5_ALLOW_WHILE_STUNNED = 0x8;
export const SPELL_ATTR5_TRIGGERS_CHANNELING = 0x10;
export const SPELL_ATTR5_LIMIT_N = 0x20;
export const SPELL_ATTR5_IGNORE_AREA_EFFECT_PVP_CHECK = 0x40;
export const SPELL_ATTR5_NOT_ON_PLAYER = 0x80;
export const SPELL_ATTR5_NOT_ON_PLAYER_CONTROLLED_NPC = 0x100;
export const SPELL_ATTR5_EXTRA_INITIAL_PERIOD = 0x200;
export const SPELL_ATTR5_DO_NOT_DISPLAY_DURATION = 0x400;
export const SPELL_ATTR5_IMPLIED_TARGETING = 0x800;
export const SPELL_ATTR5_MELEE_CHAIN_TARGETING = 0x1000;
export const SPELL_ATTR5_SPELL_HASTE_AFFECTS_PERIODIC = 0x2000;
export const SPELL_ATTR5_NOT_AVALIABLE_WHILE_CHARMED = 0x4000;
export const SPELL_ATTR5_TREAT_AS_AREA_EFFECT = 0x8000;
export const SPELL_ATTR5_AURA_AFFECTS_NOT_JUST_REQ_EQUIPPED_ITEM = 0x10000;
export const SPELL_ATTR5_ALLOW_WHILE_FLEEING = 0x20000;
export const SPELL_ATTR5_ALLOW_WHILE_CONFUSED = 0x40000;
export const SPELL_ATTR5_AI_DOESNT_FACE_TARGET = 0x80000;
export const SPELL_ATTR5_DO_NOT_ATTEMPT_A_PET_RESUMMON_WHEN_DISMOUNTING = 0x100000;
export const SPELL_ATTR5_IGNORE_TARGET_REQUIREMENTS = 0x200000;
export const SPELL_ATTR5_NOT_ON_TRIVIAL = 0x400000;
export const SPELL_ATTR5_NO_PARTIAL_RESISTS = 0x800000;
export const SPELL_ATTR5_IGNORE_CASTER_REQUIREMENETS = 0x1000000;
export const SPELL_ATTR5_ALWAYS_LINE_OF_SIGHT = 0x2000000;
export const SPELL_ATTR5_ALWAYS_AOE_LINE_OF_SIGHT = 0x4000000;
export const SPELL_ATTR5_NO_CASTER_AURA_ICON = 0x8000000;
export const SPELL_ATTR5_NO_TARGET_AURA_ICON = 0x10000000;
export const SPELL_ATTR5_AURA_UNIQUE_PER_CASTER = 0x20000000;
export const SPELL_ATTR5_ALWAYS_SHOW_GROUND_TEXTURE = 0x40000000;
export const SPELL_ATTR5_ADD_MELEE_HIT_RATING = 0x80000000;

// SpellAttr6
export const SPELL_ATTR6_NO_COOLDOWN_ON_TOOLTIP = 0x1;
export const SPELL_ATTR6_DO_NOT_RESET_COOLDOWN_IN_ARENA = 0x2;
export const SPELL_ATTR6_NOT_AN_ATTACK = 0x4;
export const SPELL_ATTR6_CAN_ASSIST_IMMUNE_PC = 0x8;
export const SPELL_ATTR6_IGNORE_FOR_MOD_TIME_RATE = 0x10;
export const SPELL_ATTR6_DO_NOT_CONSUME_RESOURCES = 0x20;
export const SPELL_ATTR6_FLOATING_COMBAT_TEXT_ON_CAST = 0x40;
export const SPELL_ATTR6_AURA_IS_WEAPON_PROC = 0x80;
export const SPELL_ATTR6_DO_NOT_CHAIN_TO_CROWD_CONTROLLED_TARGETS = 0x100;
export const SPELL_ATTR6_ALLOW_ON_CHARMED_TARGETS = 0x200;
export const SPELL_ATTR6_NO_AURA_LOG = 0x400;
export const SPELL_ATTR6_NOT_IN_RAID_INSTANCES = 0x800;
export const SPELL_ATTR6_ALLOW_WHILE_RIDING_VEHICLE = 0x1000;
export const SPELL_ATTR6_IGNORE_PHASE_SHIFT = 0x2000;
export const SPELL_ATTR6_AI_PRIMARY_RANGED_ATTACK = 0x4000;
export const SPELL_ATTR6_NO_PUSHBACK = 0x8000;
export const SPELL_ATTR6_NO_JUMP_PATHING = 0x10000;
export const SPELL_ATTR6_ALLOW_EQUIP_WHILE_CASTING = 0x20000;
export const SPELL_ATTR6_ORIGINATE_FROM_CONTROLLER = 0x40000;
export const SPELL_ATTR6_DELAY_COMBAT_TIMER_DURING_CAST = 0x80000;
export const SPELL_ATTR6_AURA_ICON_ONLY_FOR_CASTER = 0x100000;
export const SPELL_ATTR6_SHOW_MECHANIC_AS_COMBAT_TEXT = 0x200000;
export const SPELL_ATTR6_ABSORB_CANNOT_BE_IGNORED = 0x400000;
export const SPELL_ATTR6_TAPS_IMMEDIATELY = 0x800000;
export const SPELL_ATTR6_CAN_TARGET_UNTARGETABLE = 0x1000000;
export const SPELL_ATTR6_DOESNT_RESET_SWING_TIMER_IF_INSTANT = 0x2000000;
export const SPELL_ATTR6_VEHICLE_IMMUNITY_CATEGORY = 0x4000000;
export const SPELL_ATTR6_IGNORE_HEALTH_MODIFIERS = 0x8000000;
export const SPELL_ATTR6_DO_NOT_SELECT_TARGET_WITH_INITIATES_COMBAT = 0x10000000;
export const SPELL_ATTR6_IGNORE_CASTER_DAMAGE_MODIFIERS = 0x20000000;
export const SPELL_ATTR6_DISABLE_TIED_EFFECT_POINTS = 0x40000000;
export const SPELL_ATTR6_NO_CATEGORY_COOLDOWN_MODS = 0x80000000;

// SpellAttr7
export const SPELL_ATTR7_ALLOW_SPELL_REFLECTION = 0x1;
export const SPELL_ATTR7_NO_TARGET_DURATION_MOD = 0x2;
export const SPELL_ATTR7_DISABLE_AURA_WHILE_DEAD = 0x4;
export const SPELL_ATTR7_DEBUG_SPELL = 0x8;
export const SPELL_ATTR7_TREAT_AS_RAID_BUFF = 0x10;
export const SPELL_ATTR7_CAN_BE_MULTI_CAST = 0x20;
export const SPELL_ATTR7_DONT_CAUSE_SPELL_PUSHBACK = 0x40;
export const SPELL_ATTR7_PREPARE_FOR_VEHICLE_CONTROL_END = 0x80;
export const SPELL_ATTR7_HORDE_SPECIFIC_SPELL = 0x100;
export const SPELL_ATTR7_ALLIANCE_SPECIFIC_SPELL = 0x200;
export const SPELL_ATTR7_DISPEL_REMOVES_CHARGES = 0x400;
export const SPELL_ATTR7_CAN_CAUSE_INTERRUPT = 0x800;
export const SPELL_ATTR7_CAN_CAUSE_SILENCE = 0x1000;
export const SPELL_ATTR7_NO_UI_NOT_INTERRUPTIBLE = 0x2000;
export const SPELL_ATTR7_RECAST_ON_RESUMMON = 0x4000;
export const SPELL_ATTR7_RESET_SWING_TIMER_AT_SPELL_START = 0x8000;
export const SPELL_ATTR7_ONLY_IN_SPELLBOOK_UNTIL_LEARNED = 0x10000;
export const SPELL_ATTR7_DO_NOT_LOG_PVP_KILL = 0x20000;
export const SPELL_ATTR7_ATTACK_ON_CHARGE_TO_UNIT = 0x40000;
export const SPELL_ATTR7_REPORT_SPELL_FAILURE_TO_UNIT_TARGET = 0x80000;
export const SPELL_ATTR7_NO_CLIENT_FAIL_WHILE_STUNNED_FLEEING_CONFUSED = 0x100000;
export const SPELL_ATTR7_RETAIN_COOLDOWN_THROUGH_LOAD = 0x200000;
export const SPELL_ATTR7_IGNORES_COLD_WEATHER_FLYING_REQUIREMENT = 0x400000;
export const SPELL_ATTR7_NO_ATTACK_DODGE = 0x800000;
export const SPELL_ATTR7_NO_ATTACK_PARRY = 0x1000000;
export const SPELL_ATTR7_NO_ATTACK_MISS = 0x2000000;
export const SPELL_ATTR7_TREAT_AS_NPC_AOE = 0x4000000;
export const SPELL_ATTR7_BYPASS_NO_RESURRECTION_AURA = 0x8000000;
export const SPELL_ATTR7_DO_NOT_COUNT_FOR_PVP_SCOREBOARD = 0x10000000;
export const SPELL_ATTR7_REFLECTION_ONLY_DEFENDS = 0x20000000;
export const SPELL_ATTR7_CAN_PROC_FROM_SUPPRESSED_TARGET_PROCS = 0x40000000;
export const SPELL_ATTR7_ALWAYS_CAST_LOG = 0x80000000;

