import type { MySqlTable } from "drizzle-orm/mysql-core";
import * as world from "./schema/world.ts";
import { SPELL_WORLD_TABLES, spellWorldTable } from "../spells/world-data.ts";
import { LOOT_TABLE_NAMES, lootTable } from "../loot/templates.ts";

/** The `acore_world` tables the server keeps in memory (`WorldTables`). A table read at runtime must be listed here. */
export const WORLD_TABLES: readonly MySqlTable[] = [...new Set<MySqlTable>([
  world.acore_string,
  world.areatrigger,
  world.broadcast_text,
  world.command,
  world.trainer,
  world.trainer_spell,
  world.gameobject_template_locale,
  world.item_template_locale,
  world.quest_template_locale,
  world.conditions,
  world.creature,
  world.creature_classlevelstats,
  world.creature_equip_template,
  world.creature_immunities,
  world.creature_model_info,
  world.creature_multispawn,
  world.creature_questender,
  world.creature_questitem,
  world.creature_queststarter,
  world.creature_template,
  world.creature_template_locale,
  world.creature_template_model,
  world.creature_template_resistance,
  world.disables,
  world.durabilitycosts_dbc,
  world.durabilityquality_dbc,
  world.exploration_basexp,
  world.factiontemplate_dbc,
  world.game_event,
  world.game_event_creature,
  world.game_event_gameobject,
  world.game_event_npc_vendor,
  world.game_event_pool,
  world.game_graveyard,
  world.game_tele,
  world.gameobject,
  world.gameobject_questender,
  world.gameobject_questitem,
  world.gameobject_queststarter,
  world.gameobject_template,
  world.gossip_menu,
  world.gossip_menu_option,
  world.graveyard_zone,
  world.instance_template,
  world.item_enchantment_template,
  world.item_template,
  world.itemextendedcost_dbc,
  world.itemlimitcategory_dbc,
  world.itemrandomproperties_dbc,
  world.itemrandomsuffix_dbc,
  world.npc_text,
  world.npc_vendor,
  world.player_class_stats,
  world.player_race_stats,
  world.player_xp_for_level,
  world.playercreateinfo,
  world.playercreateinfo_action,
  world.playercreateinfo_skills,
  world.playercreateinfo_spell_custom,
  world.points_of_interest,
  world.pool_creature,
  world.pool_gameobject,
  world.pool_template,
  world.quest_details,
  world.quest_money_reward,
  world.quest_offer_reward,
  world.quest_poi,
  world.quest_poi_points,
  world.quest_request_items,
  world.quest_template,
  world.quest_template_addon,
  world.questfactionreward_dbc,
  world.questxp_dbc,
  world.randproppoints_dbc,
  world.reference_loot_template,
  world.spell_bonus_data,
  world.spell_cooldown_overrides,
  world.spell_dbc,
  world.spell_target_position,
  world.spellcasttimes_dbc,
  world.spellcategory_dbc,
  world.spellduration_dbc,
  world.spellitemenchantment_dbc,
  world.spellradius_dbc,
  world.spellrange_dbc,
  world.spellshapeshiftform_dbc,
  world.spellvisual_dbc,
  world.taxinodes_dbc,
  world.taxipath_dbc,
  world.taxipathnode_dbc,
  // WaypointMgr::Load, LoadWaypointAddons, ReloadPath
  world.waypoint_data,
  world.waypoint_data_addon,
  // spawn stores (ObjectMgr::LoadCreatureAddons, LoadGameObjectAddons, LoadSpawnGroups, LoadLinkedRespawn)
  world.creature_addon,
  world.creature_template_addon,
  // ObjectMgr::LoadCreatureTemplate (the `ctm` join), LoadCreatureMovementOverrides
  world.creature_template_movement,
  world.creature_movement_override,
  world.gameobject_addon,
  world.gameobject_template_addon,
  world.spawn_group_template,
  world.spawn_group,
  world.linked_respawn,
  // FormationMgr::LoadCreatureFormations
  world.creature_formations,
  ...SPELL_WORLD_TABLES.map(spellWorldTable),
  ...LOOT_TABLE_NAMES.map(lootTable),
])];
