/** Generated by `src/tools/gen-command-enums.ts` from AzerothCore `Player.h` (3.3.5a). */

// PlayerFlags
export const PLAYER_FLAGS_GROUP_LEADER = 1;
export const PLAYER_FLAGS_AFK = 2;
export const PLAYER_FLAGS_DND = 4;
export const PLAYER_FLAGS_GM = 8;
export const PLAYER_FLAGS_GHOST = 16;
export const PLAYER_FLAGS_RESTING = 32;
export const PLAYER_FLAGS_UNK6 = 64;
export const PLAYER_FLAGS_UNK7 = 128;
export const PLAYER_FLAGS_CONTESTED_PVP = 0x00000100;
export const PLAYER_FLAGS_IN_PVP = 0x00000200;
export const PLAYER_FLAGS_HIDE_HELM = 0x00000400;
export const PLAYER_FLAGS_HIDE_CLOAK = 0x00000800;
export const PLAYER_FLAGS_PARTIAL_PLAY_TIME = 0x00001000;
export const PLAYER_FLAGS_NO_PLAY_TIME = 0x00002000;
export const PLAYER_FLAGS_IS_OUT_OF_BOUNDS = 0x00004000;
export const PLAYER_FLAGS_DEVELOPER = 0x00008000;
export const PLAYER_FLAGS_UNK16 = 0x00010000;
export const PLAYER_FLAGS_TAXI_BENCHMARK = 0x00020000;
export const PLAYER_FLAGS_PVP_TIMER = 0x00040000;
export const PLAYER_FLAGS_UBER = 0x00080000;
export const PLAYER_FLAGS_UNK20 = 0x00100000;
export const PLAYER_FLAGS_UNK21 = 0x00200000;
export const PLAYER_FLAGS_COMMENTATOR2 = 0x00400000;
export const PLAYER_ALLOW_ONLY_ABILITY = 0x00800000;
export const PLAYER_FLAGS_UNK24 = 0x01000000;
export const PLAYER_FLAGS_NO_XP_GAIN = 0x02000000;
export const PLAYER_FLAGS_UNK26 = 0x04000000;
export const PLAYER_FLAGS_UNK27 = 0x08000000;
export const PLAYER_FLAGS_UNK28 = 0x10000000;
export const PLAYER_FLAGS_UNK29 = 0x20000000;
export const PLAYER_FLAGS_UNK30 = 0x40000000;
export const PLAYER_FLAGS_UNK31 = 0x80000000;

// PlayerExtraFlags
export const PLAYER_EXTRA_GM_ON = 1;
export const PLAYER_EXTRA_ACCEPT_WHISPERS = 4;
export const PLAYER_EXTRA_TAXICHEAT = 8;
export const PLAYER_EXTRA_GM_INVISIBLE = 16;
export const PLAYER_EXTRA_GM_CHAT = 32;
export const PLAYER_EXTRA_HAS_310_FLYER = 64;
export const PLAYER_EXTRA_SPECTATOR_ON = 128;
export const PLAYER_EXTRA_PVP_DEATH = 0x00000100;
export const PLAYER_EXTRA_SHOW_DK_PET = 0x00000400;
export const PLAYER_EXTRA_GM_SPECTATOR = 0x00000800;
export const PLAYER_EXTRA_DECLINE_GROUP_INVITES = 0x00001000;

// AtLoginFlags
export const AT_LOGIN_NONE = 0;
export const AT_LOGIN_RENAME = 1;
export const AT_LOGIN_RESET_SPELLS = 2;
export const AT_LOGIN_RESET_TALENTS = 4;
export const AT_LOGIN_CUSTOMIZE = 8;
export const AT_LOGIN_RESET_PET_TALENTS = 16;
export const AT_LOGIN_FIRST = 32;
export const AT_LOGIN_CHANGE_FACTION = 64;
export const AT_LOGIN_CHANGE_RACE = 128;
export const AT_LOGIN_RESET_AP = 0x00000100;
export const AT_LOGIN_RESET_ARENA = 0x00000200;
export const AT_LOGIN_CHECK_ACHIEVS = 0x00000400;
export const AT_LOGIN_RESURRECT = 0x00000800;

// TeleportToOptions
export const TELE_TO_GM_MODE = 1;
export const TELE_TO_NOT_LEAVE_TRANSPORT = 2;
export const TELE_TO_NOT_LEAVE_COMBAT = 4;
export const TELE_TO_NOT_UNSUMMON_PET = 8;
export const TELE_TO_SPELL = 16;
export const TELE_TO_NOT_LEAVE_VEHICLE = 32;
export const TELE_TO_WITH_PET = 64;
export const TELE_TO_NOT_LEAVE_TAXI = 128;

// PlayerChatTag
export const CHAT_TAG_NONE = 0;
export const CHAT_TAG_AFK = 1;
export const CHAT_TAG_DND = 2;
export const CHAT_TAG_GM = 4;
export const CHAT_TAG_COM = 8;
export const CHAT_TAG_DEV = 16;

// CharDeleteMethod
export const CHAR_DELETE_REMOVE = 0;
export const CHAR_DELETE_UNLINK = 1;

// PlayerCommandStates
export const CHEAT_NONE = 0;
export const CHEAT_GOD = 1;
export const CHEAT_CASTTIME = 2;
export const CHEAT_COOLDOWN = 4;
export const CHEAT_POWER = 8;
export const CHEAT_WATERWALK = 16;
