/**
 * Writes `src/database/schema/{auth,characters,world}.ts` from the live databases: `bun run gen:db-schema`.
 * Run `bun run db:update` first so the databases hold `sql/base/` plus every update. Never edit the output by hand.
 */
import { $ } from "bun";

const DATABASES = [
  { file: "auth", database: "acore_auth" },
  { file: "characters", database: "acore_characters" },
  { file: "world", database: "acore_world" },
];
const host = process.env.MYSQL_HOST ?? "127.0.0.1";
const port = process.env.MYSQL_PORT ?? "3306";

for (const { file, database } of DATABASES) {
  const out = `/tmp/wow-ts-pull-${file}`;
  await $`rm -rf ${out}`;
  await $`bun --bun x drizzle-kit pull --dialect mysql --url ${`mysql://acore:acore@${host}:${port}/${database}`} --out ${out} --introspect-casing preserve`.quiet();
  let text = await Bun.file(`${out}/schema.ts`).text();
  const bytes = /\b(binary|varbinary)\(/.test(text);
  text = text
    .replace(/\bbinary\(\{/g, "binaryBytes({")
    .replace(/\bvarbinary\(\{/g, "varbinaryBytes({")
    .replace(/\bblob\(\)/g, "blob({ mode: \"buffer\" })")
    .replace(/, binary\b|, varbinary\b/g, "")
    .replace(/\bAnyMySqlColumn, /, "type AnyMySqlColumn, ")
    // Unsigned 64-bit columns hold full guids and masks, which do not fit a double.
    .replace(/bigint\(\{ unsigned: true, mode: 'number' \}\)/g, "bigint({ unsigned: true, mode: 'bigint' })")
    .replace(/(mode: 'bigint' \}\)[^\n]*?)\.default\((\d+)\)/g, "$1.default($2n)")
    .replace(/^import \{ sql \} from "drizzle-orm"\n/m, text.includes("sql`") ? 'import { sql } from "drizzle-orm"\n' : "");
  const header = [
    `/** Generated by \`src/tools/gen-db-schema.ts\` from \`${database}\` (\`sql/base/db_${file === "auth" ? "auth" : file}\` plus \`data/sql/updates/\`). Do not edit. */`,
    ...(bytes ? ['import { binaryBytes, varbinaryBytes } from "./columns.ts";'] : []),
  ].join("\n");
  await Bun.write(`src/database/schema/${file}.ts`, `${header}\n${text}`);
  console.log(`src/database/schema/${file}.ts`);
}
await $`bunx tsc --noEmit -p . 2>&1 | grep src/database/schema || true`;
