/** Writes `src/spells/enums.ts` from the AzerothCore headers: `bun src/tools/gen-spell-enums.ts`. */
const root = new URL("../../azerothcore/src/server", import.meta.url).pathname;
const wanted: [string, string[]][] = [
  ["shared/SharedDefines.h", ["SpellSchools", "SpellSchoolMask", "AuraStateType", "Mechanics", "DispelType", "SpellImmunity", "SpellHitType", "SpellDmgClass", "SpellPreventionType", "CreatureType", "CreatureTypeFlags", "SpellFamilyNames", "DiminishingGroup", "DiminishingReturnsType", "Powers", "SpellCategory", "Stats"]],
  ["shared/DataStores/DBCEnums.h", ["SpellCategoryFlags"]],
  ["game/Spells/SpellDefines.h", ["SpellModOp", "SpellInterruptFlags", "SpellChannelInterruptFlags", "SpellAuraInterruptFlags", "SpellValueMod", "SpellFacingFlags", "TriggerCastFlags"]],
  ["game/Spells/Auras/SpellAuraDefines.h", ["AURA_FLAGS", "AuraEffectHandleModes", "AuraObjectType", "AuraRemoveMode"]],
  ["game/Spells/SpellMgr.h", ["SpellLinkedType", "SpellGroupStackRule", "SpellFamilyFlag"]],
  ["game/Spells/SpellInfo.h", ["SpellCastTargetFlags", "SpellTargetSelectionCategories", "SpellTargetReferenceTypes", "SpellTargetObjectTypes", "SpellTargetCheckTypes", "SpellTargetDirectionTypes", "SpellEffectImplicitTargetTypes", "SpellSpecificType", "SpellCustomAttributes"]],
  ["game/Spells/Spell.h", ["SpellCastFlags", "SpellState", "SpellEffectHandleMode", "SpellRangeFlag"]],
  ["game/Entities/Unit/UnitDefines.h", ["UnitState", "UnitFlags", "UnitFlags2", "UnitMoveType", "UnitStandStateType", "ShapeshiftForm"]],
  ["game/Entities/Unit/Unit.h", ["UnitModifierFlatType", "UnitModifierPctType", "UnitMods", "BaseModGroup", "BaseModType", "DamageEffectType", "CurrentSpellTypes", "WeaponAttackType"]],
];
const values = new Map<string, number>();
const out: string[] = [
  "/** Generated by `src/tools/gen-spell-enums.ts` from AzerothCore `SharedDefines.h`, `DBCEnums.h`, `SpellDefines.h`, `SpellAuraDefines.h`, `SpellMgr.h`, `SpellInfo.h`, `Spell.h`, `UnitDefines.h`, and `Unit.h` (3.3.5a). */",
  "",
];
function evalExpr(expr: string, prev: number): number {
  let e = expr.replace(/\/\/.*$/, "").trim();
  e = e.replace(/(0x[0-9a-fA-F]+|\d+)(u|U|ul|UL|ULL|ull|LL|ll|f)\b/g, "$1");
  e = e.replace(/uint32\(([^)]*)\)/g, "($1)");
  e = e.replace(/0x[0-9a-fA-F]+|\d+(?:\.\d+)?|[A-Za-z_][A-Za-z0-9_]*(?:::[A-Za-z_][A-Za-z0-9_]*)?/g, (name) => {
    if (/^[0-9]/.test(name)) return name;
    const bare = name.includes("::") ? name.split("::")[1]! : name;
    if (!values.has(bare)) throw new Error(`unknown ${name} in ${expr}`);
    return `(${values.get(bare)})`;
  });
  // eslint-disable-next-line no-new-func
  const value = Function(`"use strict"; return (${e});`)() as number;
  return value < 0 ? value : value >>> 0 === value ? value : value;
}
for (const [file, enums] of wanted) {
  const text = await Bun.file(`${root}/${file}`).text();
  for (const name of enums) {
    const re = new RegExp(`enum (?:class )?${name}\\b[^{]*\\{([\\s\\S]*?)\\n\\};`);
    const match = re.exec(text);
    if (!match) throw new Error(`enum ${name} not found in ${file}`);
    const body = match[1]!.replace(/\/\*[\s\S]*?\*\//g, "");
    out.push(`// ${name}`);
    let prev = -1;
    const joined = body.split("\n").map((l) => l.replace(/\/\/.*$/, "")).filter((l) => !l.trim().startsWith("#")).join(" ");
    for (const part of joined.split(",")) {
        const item = part.trim();
        if (!item) continue;
        const [lhs, ...rhs] = item.split("=");
        const key = lhs!.trim();
        if (!/^[A-Za-z_][A-Za-z0-9_]*$/.test(key)) throw new Error(`bad key ${item} in ${name}`);
        const value = rhs.length ? evalExpr(rhs.join("="), prev) : prev + 1;
        values.set(key, value);
        prev = value;
        if (values.has(`__emitted_${key}`)) continue;
        values.set(`__emitted_${key}`, 1);
        const literal = value >= 0x100 && Number.isInteger(value) && value > 0 ? `0x${value.toString(16).padStart(8, "0")}` : String(value);
        out.push(`export const ${key} = ${literal};`);
    }
    out.push("");
  }
}
await Bun.write(new URL("../spells/enums.ts", import.meta.url).pathname, out.join("\n"));

