/** Writes `src/spells/target-data.ts` from AzerothCore `SpellInfo.cpp`: `bun src/tools/gen-spell-target-data.ts`. */
const src = await Bun.file(new URL("../../azerothcore/src/server/game/Spells/SpellInfo.cpp", import.meta.url).pathname).text();
const targetBlock = src.slice(src.indexOf("SpellImplicitTargetInfo::_data ="), src.indexOf("SpellEffectInfo::SpellEffectInfo("));
const rows = [...targetBlock.matchAll(/\{(TARGET_OBJECT_TYPE_\w+),\s*(TARGET_REFERENCE_TYPE_\w+),\s*(TARGET_SELECT_CATEGORY_\w+),\s*(TARGET_CHECK_\w+),\s*(TARGET_DIR_\w+)\}/g)];
if (rows.length !== 111) throw new Error(`targets ${rows.length}`);
const effectBlock = src.slice(src.indexOf("SpellEffectInfo::_data ="));
const effects = [...effectBlock.slice(0, effectBlock.indexOf("} };")).matchAll(/\{(EFFECT_IMPLICIT_TARGET_\w+),\s*(TARGET_OBJECT_TYPE_\w+)\}/g)];
if (effects.length !== 165) throw new Error(`effects ${effects.length}`);
const lines = [
  "/** `SpellImplicitTargetInfo::_data` and `SpellEffectInfo::_data`, generated by `src/tools/gen-spell-target-data.ts` from AzerothCore `SpellInfo.cpp`. */",
  "import {",
  ...[...new Set([...rows.flatMap((r) => r.slice(1, 6)), ...effects.flatMap((r) => r.slice(1, 3))])].sort().map((n) => `  ${n},`),
  "} from \"./enums.ts\";",
  "",
  "export type ImplicitTargetData = { objectType: number; referenceType: number; selectionCategory: number; checkType: number; directionType: number };",
  "export type EffectTargetData = { implicitTargetType: number; usedTargetObjectType: number };",
  "",
  "/** Indexed by `Targets`. */",
  "export const IMPLICIT_TARGETS: readonly ImplicitTargetData[] = [",
  ...rows.map((r, i) => `  { objectType: ${r[1]}, referenceType: ${r[2]}, selectionCategory: ${r[3]}, checkType: ${r[4]}, directionType: ${r[5]} }, // ${i}`),
  "];",
  "",
  "/** Indexed by `SpellEffects`. */",
  "export const EFFECT_TARGETS: readonly EffectTargetData[] = [",
  ...effects.map((r, i) => `  { implicitTargetType: ${r[1]}, usedTargetObjectType: ${r[2]} }, // ${i}`),
  "];",
  "",
];
await Bun.write(new URL("../spells/target-data.ts", import.meta.url).pathname, lines.join("\n"));
