/** Writes `src/spells/enums.ts` from the AzerothCore headers: `bun src/tools/gen-spell-enums.ts`. */
import { CppEnums, type EnumSource } from "./cpp-enums.ts";

const wanted: EnumSource[] = [
  ["server/shared/SharedDefines.h", ["SpellSchools", "SpellSchoolMask", "AuraStateType", "Mechanics", "DispelType", "SpellImmunity", "SpellHitType", "SpellDmgClass", "SpellPreventionType", "CreatureType", "CreatureTypeFlags", "SpellFamilyNames", "DiminishingGroup", "DiminishingReturnsType", "Powers", "SpellCategory", "Stats"]],
  ["server/shared/DataStores/DBCEnums.h", ["SpellCategoryFlags"]],
  ["server/game/Spells/SpellDefines.h", ["SpellModOp", "SpellInterruptFlags", "SpellChannelInterruptFlags", "SpellAuraInterruptFlags", "SpellValueMod", "SpellFacingFlags", "TriggerCastFlags"]],
  ["server/game/Spells/Auras/SpellAuraDefines.h", ["AURA_FLAGS", "AuraEffectHandleModes", "AuraObjectType", "AuraRemoveMode"]],
  ["server/game/Spells/SpellMgr.h", ["SpellLinkedType", "SpellGroupStackRule", "SpellFamilyFlag"]],
  ["server/game/Spells/SpellInfo.h", ["SpellCastTargetFlags", "SpellTargetSelectionCategories", "SpellTargetReferenceTypes", "SpellTargetObjectTypes", "SpellTargetCheckTypes", "SpellTargetDirectionTypes", "SpellEffectImplicitTargetTypes", "SpellSpecificType", "SpellCustomAttributes"]],
  ["server/game/Spells/Spell.h", ["SpellCastFlags", "SpellState", "SpellEffectHandleMode", "SpellRangeFlag"]],
  ["server/game/Entities/Unit/UnitDefines.h", ["UnitState", "UnitFlags", "UnitFlags2", "UnitMoveType", "UnitStandStateType", "ShapeshiftForm"]],
  ["server/game/Entities/Unit/Unit.h", ["UnitModifierFlatType", "UnitModifierPctType", "UnitMods", "BaseModGroup", "BaseModType", "DamageEffectType", "CurrentSpellTypes", "WeaponAttackType"]],
];
const out: string[] = [
  "/** Generated by `src/tools/gen-spell-enums.ts` from AzerothCore `SharedDefines.h`, `DBCEnums.h`, `SpellDefines.h`, `SpellAuraDefines.h`, `SpellMgr.h`, `SpellInfo.h`, `Spell.h`, `UnitDefines.h`, and `Unit.h` (3.3.5a). */",
  "",
  ...(await new CppEnums().emit(wanted)),
];
await Bun.write(new URL("../spells/enums.ts", import.meta.url).pathname, out.join("\n"));
