/**
 * Writes the enums the chat command system reads from the AzerothCore headers: `bun src/tools/gen-command-enums.ts`.
 * `Language.h` (acore_string ids), `RBAC.h`, `SharedDefines.h` / `Common.h`, and `Player.h`.
 */
import { CppEnums, type EnumSource } from "./cpp-enums.ts";

const outputs: [target: string, sources: EnumSource[]][] = [
  ["../game/Miscellaneous/Language.ts", [["server/game/Miscellaneous/Language.h", ["BroadcastTextIds", "AcoreStrings"]]]],
  ["../game/Accounts/RBACDefines.ts", [["server/game/Accounts/RBAC.h", ["RBACPermissions", "RBACCommandResult"]]]],
  [
    "../shared/SharedDefines.ts",
    [
      ["common/Common.h", ["AccountTypes", "AccountFlag", "LocaleConstant"]],
      [
        "server/shared/SharedDefines.h",
        [
          "Expansions",
          "Gender",
          "Races",
          "Classes",
          "ReputationRank",
          "FactionTemplates",
          "MoneyConstants",
          "ItemQualities",
          "Language",
          "TeamId",
          "Team",
          "ServerSideVisibilityType",
          "ChatMsg",
          "ChatLinkColors",
          "Emote",
        ],
      ],
    ],
  ],
  [
    "../game/Entities/Player/PlayerDefines.ts",
    [["server/game/Entities/Player/Player.h", ["PlayerFlags", "PlayerExtraFlags", "AtLoginFlags", "TeleportToOptions", "PlayerChatTag", "CharDeleteMethod", "PlayerCommandStates"]]],
  ],
];

for (const [target, sources] of outputs) {
  const headers = sources.map(([file]) => `\`${file.split("/").pop()}\``).join(", ");
  const extra = target === "../shared/SharedDefines.ts" ? ["// Common.h", "export const DEFAULT_LOCALE = LOCALE_enUS;", "", "// SharedDefines.h", "export const MAX_CHAT_MSG_TYPE = 0x34;", ""] : [];
  const lines = [`/** Generated by \`src/tools/gen-command-enums.ts\` from AzerothCore ${headers} (3.3.5a). */`, "", ...(await new CppEnums().emit(sources)), ...extra];
  await Bun.write(new URL(target, import.meta.url).pathname, lines.join("\n"));
}
